---
sidebar: sidebar 
permalink: upgrade/concept_element_upgrade_overview.html 
summary: 'È possibile mantenere aggiornato il sistema di archiviazione SolidFire Element dopo l"implementazione aggiornando tutti i componenti di archiviazione NetApp .' 
keywords: netapp, solidfire upgrade, vcp upgrade, element upgrade, vsphere upgrade 
---
= Panoramica della sequenza di aggiornamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile mantenere aggiornato il sistema di archiviazione SolidFire Element dopo l'implementazione aggiornando in sequenza tutti i componenti di archiviazione NetApp .

Questi componenti includono servizi di gestione, NetApp Hybrid Cloud Control, software Element, nodo di gestione e (a seconda dell'installazione) Element Plug-in per vCenter Server.

[NOTE]
====
* A partire da novembre 2023, non sarà più possibile avviare l'aggiornamento di un componente tramite NetApp Hybrid Cloud Control o REST API, poiché i certificati delle chiavi di firma (privati ​​e pubblici) sono scaduti il ​​5 novembre 2023.  Puoi aggirare questo problemalink:task_hcc_upgrade_management_node.html["esecuzione di un aggiornamento sul posto del nodo di gestione"] alla versione 12.8 prima di utilizzare NetApp Hybrid Cloud Control o REST API per aggiornare i servizi di gestione, il software Element e il firmware di storage.
+
Se si sta distribuendo un nuovo nodo di gestione con la versione 12.8, è possibile utilizzare NetApp Hybrid Cloud Control o REST API per eseguire gli aggiornamenti dei componenti nell'ordine elencato in<<sys_upgrade,sequenza di aggiornamento del sistema>> .

* I seguenti nodi non sono supportati.  Se si tenta di aggiornare uno di questi nodi a una versione di Element non supportata, verrà visualizzato un errore che indica che il nodo non è supportato da Element 12.x:
+
** A partire dai nodi di archiviazione Element 12.8, SF4805, SF9605, SF19210 e SF38410.
** A partire dall'elemento 12.7, nodi di archiviazione SF2405 e SF9608 e nodi FC FC0025 e SF-FCN-01.


* A partire da Element 12.5, NetApp HealthTools non è più supportato per gli aggiornamenti software di Element.  Se stai utilizzando Element 11.0 o 11.1, devi prima https://docs.netapp.com/us-en/element-software-123/upgrade/task_hcc_upgrade_element_software.html#upgrade-element-software-at-connected-sites-using-healthtools["aggiorna a Element 12.3 utilizzando HealthTools"^] e poi eseguire l'aggiornamento a Element 12.5 o versione successiva utilizzando NetApp Hybrid Cloud Control.


====
IL<<sys_upgrade,sequenza di aggiornamento del sistema>> Il contenuto descrive le attività necessarie per completare un aggiornamento del sistema di archiviazione all-flash SolidFire .  Idealmente, queste procedure vengono eseguite come parte di una sequenza di aggiornamento più ampia e non in modo isolato.  Se è necessario un aggiornamento o un upgrade basato sui componenti, consultare i prerequisiti della procedura per garantire che vengano affrontate ulteriori complessità.

ILlink:task_sf_upgrade_all_vsphere.html["Sequenza di aggiornamento di vSphere"] incluso il contenuto Element Plug-in per vCenter Server descrive i passaggi aggiuntivi pre e post aggiornamento necessari per reinstallare Element Plug-in per vCenter Server.

.Prima di iniziare
* Stai eseguendo il nodo di gestione 11.3 o versione successiva.  Le versioni più recenti del nodo di gestione hanno un'architettura modulare che fornisce servizi individuali.
+

TIP: Per verificare la versione, accedi al tuo nodo di gestione e visualizza il numero di versione dell'elemento nel banner di accesso.  Se non hai 11.3, vedilink:task_hcc_upgrade_management_node.html["Aggiorna il tuo nodo di gestione"] .

* Hai aggiornato i tuoi servizi di gestione almeno alla versione 2.1.326.
+
Gli aggiornamenti tramite NetApp Hybrid Cloud Control non sono disponibili nelle versioni precedenti del pacchetto di servizi.

* Hai verificato che l'ora di sistema su tutti i nodi sia sincronizzata e che NTP sia configurato correttamente per il cluster di archiviazione e i nodi.  Ogni nodo deve essere configurato con un nameserver DNS nell'interfaccia utente Web per nodo(`https://[IP address]:442` ) senza errori di cluster irrisolti correlati allo sfasamento temporale.
* Hai programmato tempo sufficiente per il tuolink:task_hcc_upgrade_element_software.html#element-upgrade-time["Software Element"] Elink:task_hcc_upgrade_storage_firmware.html#storage-firmware-upgrade["firmware di archiviazione"] aggiornamenti.  Quando si esegue l'aggiornamento al software Element 12.5 o versione successiva, il tempo necessario per l'aggiornamento varia a seconda della versione del software Element e degli aggiornamenti del firmware.




== [[sys_upgrade]]Sequenza di aggiornamento del sistema

È possibile utilizzare la seguente sequenza per aggiornare il sistema di archiviazione all-flash NetApp SolidFire per Element 12.5 o versioni successive.

.Passi
. link:task_hcc_upgrade_element_prechecks.html["Eseguire controlli sullo stato di integrità dell'archiviazione Element prima di aggiornare l'archiviazione"].
. link:task_hcc_upgrade_management_node.html["(Facoltativo) Aggiorna il tuo nodo di gestione"].
+

NOTE: Non è più necessario aggiornare il sistema operativo del nodo di gestione per aggiornare il software Element sul cluster di archiviazione. Se il nodo di gestione è versione 11.3 o successiva, è sufficiente aggiornare i servizi di gestione alla versione più recente per eseguire gli aggiornamenti di Element utilizzando NetApp Hybrid Cloud Control. Seguire la procedura di aggiornamento del nodo di gestione per il proprio scenario se è necessario aggiornare il sistema operativo del nodo di gestione per altri motivi, ad esempio per correggere problemi di sicurezza.

. link:task_hcc_update_management_services.html["Aggiorna i servizi di gestione da Hybrid Cloud Control"].
+
[IMPORTANT]
====
** Il bundle dei servizi di gestione 2.27 include Element Plug-in per vCenter Server 5.5, compatibile solo con il nodo di gestione 12.8. Quando si esegue l'aggiornamento ai servizi di gestione 2.27, è necessario modificare la sequenza di aggiornamento e aggiornare il bundle dei servizi di gestione _dopo_ l'aggiornamento a Element 12.8 per garantire la compatibilità tra il nodo di gestione e i servizi di gestione.
** Se si esegue l'aggiornamento ai servizi di gestione dalla versione 2.21.61 alla versione 2.26.40, è necessario aggiornare il bundle dei servizi di gestione _prima_ di eseguire l'aggiornamento a Element 12.8.


====
+

IMPORTANT: Se si aggiornano i servizi di gestione alla versione 2.16 o successiva e si esegue un nodo di gestione dalla versione 11.3 alla 11.8, sarà necessario aumentare la RAM della VM del nodo di gestione prima di aggiornare i servizi di gestione.

. link:task_hcc_upgrade_element_software.html["Aggiorna il software Element e il firmware di archiviazione"].
. link:task_hcc_upgrade_storage_firmware.html["(Facoltativo) Aggiorna solo il firmware dell'archiviazione Element"].
+

NOTE: È possibile eseguire questa attività quando diventa disponibile un nuovo aggiornamento del firmware di archiviazione al di fuori di una versione principale.

. link:task_vcp_upgrade_plugin.html["Aggiorna il tuo Element Plug-in per vCenter Server"].


[discrete]
== Trova maggiori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]

