---
sidebar: sidebar 
permalink: upgrade/task_hcc_upgrade_storage_firmware.html 
summary: Come parte di un aggiornamento del sistema NetApp SolidFire , aggiorni il firmware associato ai tuoi nodi di storage. 
keywords: netapp, element, hcc, firmware, storage firmware 
---
= Aggiorna il firmware di archiviazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A partire da Element 12.0 e dalla versione 2.14 dei servizi di gestione, è possibile eseguire aggiornamenti solo del firmware sui nodi di storage utilizzando l'interfaccia utente di controllo NetApp Hybrid Cloud e l'API REST.  Questa procedura non aggiorna il software Element e consente di aggiornare il firmware di archiviazione al di fuori di una versione principale di Element.

.Cosa ti servirà
* *Privilegi di amministratore*: disponi delle autorizzazioni di amministratore del cluster di archiviazione per eseguire l'aggiornamento.
* *Sincronizzazione dell'ora di sistema*: hai verificato che l'ora di sistema su tutti i nodi sia sincronizzata e che NTP sia configurato correttamente per il cluster di archiviazione e i nodi.  Ogni nodo deve essere configurato con un nameserver DNS nell'interfaccia utente Web per nodo(`https://[IP address]:442` ) senza guasti di cluster irrisolti correlati allo sfasamento temporale.
* *Porte di sistema*: se si utilizza NetApp Hybrid Cloud Control per gli aggiornamenti, è necessario assicurarsi che le porte necessarie siano aperte. Vederelink:../storage/reference_prereq_network_port_requirements.html["Porte di rete"] per maggiori informazioni.
* *Nodo di gestione*: per l'interfaccia utente e l'API NetApp Hybrid Cloud Control, il nodo di gestione nel tuo ambiente esegue la versione 11.3.
* *Servizi di gestione*: Hai aggiornato il tuo pacchetto di servizi di gestione all'ultima versione.



IMPORTANT: Per i nodi di archiviazione H610S che eseguono il software Element versione 12.0, è necessario applicare la D-patch SUST-909 prima di eseguire l'aggiornamento al bundle firmware di archiviazione 2.27.  Contattare l'assistenza NetApp per ottenere la D-patch prima di effettuare l'aggiornamento. Vederelink:http://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.27.html["Note sulla versione 2.27 del pacchetto firmware di archiviazione"^] .


IMPORTANT: Prima di aggiornare il firmware sui nodi di archiviazione, è necessario eseguire l'aggiornamento al pacchetto di servizi di gestione più recente.  Se stai aggiornando il software Element alla versione 12.2 o successiva, per procedere è necessario disporre dei servizi di gestione 2.14.60 o successivi.

* *Stato del cluster*: sono stati eseguiti controlli di integrità. Vederelink:task_hcc_upgrade_element_prechecks.html["Eseguire controlli di integrità dell'archiviazione Element prima di aggiornare l'archiviazione"] .
* *Controller di gestione della scheda base (BMC) aggiornato per i nodi H610S*: hai aggiornato la versione BMC per i tuoi nodi H610S. Vederelink:https://docs.netapp.com/us-en/hci/docs/rn_H610S_BMC_3.84.07.html["note di rilascio e istruzioni di aggiornamento"^] .



NOTE: Per una matrice completa del firmware e del driver firmware per l'hardware, vederelink:../hardware/fw_storage_nodes.html["versioni del firmware di archiviazione supportate per i nodi di archiviazione SolidFire"] .

[[storage-firmware-upgrade]]
* *Tempo di esecuzione dell'aggiornamento*: hai programmato tempo sufficiente per eseguire l'aggiornamento.  Quando si esegue l'aggiornamento al software Element 12.5 o versione successiva, la durata del processo di aggiornamento varia a seconda della versione corrente del software Element e degli aggiornamenti del firmware.
+
[cols="20,20,20,20,20"]
|===
| Nodo di archiviazione | Versione attuale del software Element | Tempo approssimativo di installazione del software e del firmware per nodo^1^ | Tempo approssimativo di sincronizzazione dei dati per nodo^2^ | Tempo di aggiornamento totale approssimativo per nodo 


| Tutti i nodi SolidFire e NetApp serie H con firmware aggiornato^3^ | 12.x | 15 minuti | da 10 a 15 minuti | da 20 a 30 minuti 


| H610S e H410S | 12.x e 11.8 | 60 minuti | da 30 a 60 minuti | da 90 a 120 minuti 


| H610S | 11.7 e precedenti | 90 minuti | da 40 a 70 minuti | Da 130 a 160 minuti Devi anche https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/H_Series/NetApp_H610S_storage_node_power_off_and_on_procedure["eseguire uno spegnimento completo del nodo e la disconnessione dell'alimentazione"^] per ogni nodo H610S. 
|===
+
^1^Per una matrice completa del firmware e del driver firmware per il tuo hardware, vedilink:../hardware/fw_storage_nodes.html["versioni del firmware di archiviazione supportate per i nodi di archiviazione SolidFire"] .

+
^2^Se si combina un cluster con un carico IOPS di scrittura elevato con un tempo di aggiornamento del firmware più lungo, il tempo di sincronizzazione dei dati aumenterà.

+
^3^ I seguenti nodi non sono supportati.  Se si tenta di aggiornare uno di questi nodi a una versione di Element non supportata, verrà visualizzato un errore che indica che il nodo non è supportato da Element 12.x:

+
** A partire dai nodi di archiviazione Element 12.8, SF4805, SF9605, SF19210 e SF38410.
** A partire dall'elemento 12.7, nodi di archiviazione SF2405 e SF9608 e nodi FC FC0025 e SF-FCN-01.


* *Contratto di licenza con l'utente finale (EULA)*: a partire dalla versione 2.20.69 dei servizi di gestione, è necessario accettare e salvare l'EULA prima di utilizzare l'interfaccia utente o l'API NetApp Hybrid Cloud Control per aggiornare il firmware di storage:
+
.. Aprire l'indirizzo IP del nodo di gestione in un browser web:
+
[listing]
----
https://<ManagementNodeIP>
----
.. Accedi a NetApp Hybrid Cloud Control fornendo le credenziali di amministratore del cluster di storage.
.. Selezionare *Aggiorna* nella parte in alto a destra dell'interfaccia.
.. Viene visualizzato l'EULA.  Scorri verso il basso, seleziona *Accetto per gli aggiornamenti attuali e futuri* e seleziona *Salva*.




.Opzioni di aggiornamento
Scegli una delle seguenti opzioni di aggiornamento del firmware di archiviazione:

* <<Utilizzare l'interfaccia utente di controllo NetApp Hybrid Cloud per aggiornare il firmware di storage>>
* <<Utilizzare l'API NetApp Hybrid Cloud Control per aggiornare il firmware di storage>>




== Utilizzare l'interfaccia utente di controllo NetApp Hybrid Cloud per aggiornare il firmware di storage

È possibile utilizzare l'interfaccia utente di controllo NetApp Hybrid Cloud per aggiornare il firmware dei nodi di storage nel cluster.

.Cosa ti servirà
* Se il nodo di gestione non è connesso a Internet, è necessario https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab/download/62654/Storage_Firmware_Bundle["scaricato il pacchetto firmware di archiviazione"^] .



CAUTION: Per potenziali problemi durante l'aggiornamento dei cluster di storage utilizzando NetApp Hybrid Cloud Control e le relative soluzioni alternative, vedere https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Potential_issues_and_workarounds_when_running_storage_upgrades_using_NetApp_Hybrid_Cloud_Control["Articolo della Knowledge Base"^] .


TIP: Il processo di aggiornamento richiede circa 30 minuti per nodo di archiviazione.  Se si aggiorna un cluster di archiviazione Element a un firmware di archiviazione più recente della versione 2.76, i singoli nodi di archiviazione si riavvieranno durante l'aggiornamento solo se è stato scritto un nuovo firmware sul nodo.

.Passi
. Aprire l'indirizzo IP del nodo di gestione in un browser web:
+
[listing]
----
https://<ManagementNodeIP>
----
. Accedi a NetApp Hybrid Cloud Control fornendo le credenziali di amministratore del cluster di storage.
. Selezionare *Aggiorna* nella parte in alto a destra dell'interfaccia.
. Nella pagina *Aggiornamenti*, seleziona *Archiviazione*.
+
[NOTE]
====
Nella scheda *Archiviazione* sono elencati i cluster di archiviazione che fanno parte dell'installazione.  Se un cluster non è accessibile da NetApp Hybrid Cloud Control, non verrà visualizzato nella pagina *Aggiornamenti*.  Se disponi di cluster che eseguono Element 12.0 o versioni successive, per questi cluster verrà elencata la versione corrente del bundle del firmware.  Se i nodi di un singolo cluster hanno versioni firmware diverse o man mano che l'aggiornamento procede, nella colonna *Versione attuale del bundle firmware* verrà visualizzato *Multiplo*.  È possibile selezionare *Multiplo* per passare alla pagina *Nodi* e confrontare le versioni del firmware.  Se tutti i cluster eseguono versioni di Element precedenti alla 12.0, non verranno visualizzate informazioni sui numeri di versione del bundle del firmware.

Se il cluster è aggiornato e/o non sono disponibili pacchetti di aggiornamento, le schede *Elemento* e *Solo firmware* non vengono visualizzate.  Queste schede non vengono visualizzate nemmeno quando è in corso un aggiornamento.  Se viene visualizzata la scheda *Elemento*, ma non la scheda *Solo firmware*, non sono disponibili pacchetti firmware.

====
. Selezionare la freccia a discesa accanto al cluster che si sta aggiornando.
. Seleziona *Sfoglia* per caricare il pacchetto di aggiornamento che hai scaricato.
. Attendi il completamento del caricamento.  Una barra di avanzamento mostra lo stato del caricamento.
+

CAUTION: Il caricamento del file andrà perso se si esce dalla finestra del browser.

+
Una volta caricato e convalidato correttamente il file, verrà visualizzato un messaggio sullo schermo.  La convalida potrebbe richiedere diversi minuti.  Se in questa fase si esce dalla finestra del browser, il caricamento del file viene mantenuto.

. Selezionare *Solo firmware* e scegliere tra le versioni di aggiornamento disponibili.
. Seleziona *Inizia aggiornamento*.
+

TIP: Lo *Stato dell'aggiornamento* cambia durante l'aggiornamento per riflettere lo stato del processo.  Cambia anche in risposta alle azioni intraprese, ad esempio sospendendo l'aggiornamento o se l'aggiornamento restituisce un errore. Vedere<<Modifiche allo stato dell'aggiornamento>> .

+

NOTE: Mentre l'aggiornamento è in corso, puoi uscire dalla pagina e tornarci in un secondo momento per continuare a monitorare i progressi.  La pagina non aggiorna dinamicamente lo stato e la versione corrente se la riga del cluster è compressa.  Per aggiornare la tabella è necessario espandere la riga del cluster oppure è possibile aggiornare la pagina.



Una volta completato l'aggiornamento, sarà possibile scaricare i registri.



=== Modifiche allo stato dell'aggiornamento

Ecco i diversi stati mostrati nella colonna *Stato aggiornamento* nell'interfaccia utente prima, durante e dopo il processo di aggiornamento:

[cols="2*"]
|===
| Stato di aggiornamento | Descrizione 


| Aggiornato | Il cluster è stato aggiornato all'ultima versione disponibile di Element oppure il firmware è stato aggiornato all'ultima versione. 


| Impossibile rilevare | Questo stato viene visualizzato quando l'API del servizio di archiviazione restituisce uno stato di aggiornamento che non è presente nell'elenco enumerato dei possibili stati di aggiornamento. 


| Versioni disponibili | Sono disponibili versioni più recenti del firmware Element e/o di archiviazione per l'aggiornamento. 


| In corso | L'aggiornamento è in corso.  Una barra di avanzamento mostra lo stato dell'aggiornamento.  I messaggi sullo schermo mostrano anche gli errori a livello di nodo e visualizzano l'ID di ciascun nodo nel cluster man mano che l'aggiornamento procede.  È possibile monitorare lo stato di ciascun nodo utilizzando l'interfaccia utente Element o il plug-in NetApp Element per l'interfaccia utente vCenter Server. 


| Aggiornamento in pausa | Puoi scegliere di mettere in pausa l'aggiornamento.  A seconda dello stato del processo di aggiornamento, l'operazione di pausa può avere esito positivo o negativo.  Verrà visualizzato un messaggio nell'interfaccia utente che chiede di confermare l'operazione di pausa.  Per garantire che il cluster si trovi in una posizione sicura prima di sospendere un aggiornamento, potrebbero essere necessarie fino a due ore affinché l'operazione di aggiornamento venga completamente sospesa.  Per riprendere l'aggiornamento, seleziona *Riprendi*. 


| In pausa | Hai messo in pausa l'aggiornamento.  Selezionare *Riprendi* per riprendere il processo. 


| Errore | Si è verificato un errore durante l'aggiornamento.  È possibile scaricare il registro degli errori e inviarlo al supporto NetApp .  Dopo aver risolto l'errore, puoi tornare alla pagina e selezionare *Riprendi*.  Quando si riprende l'aggiornamento, la barra di avanzamento torna indietro per alcuni minuti mentre il sistema esegue il controllo dello stato e verifica lo stato attuale dell'aggiornamento. 
|===


== Cosa succede se un aggiornamento non riesce utilizzando NetApp Hybrid Cloud Control

Se un'unità o un nodo si guasta durante un aggiornamento, l'interfaccia utente di Element mostrerà gli errori del cluster.  Il processo di aggiornamento non passa al nodo successivo e attende la risoluzione degli errori del cluster.  La barra di avanzamento nell'interfaccia utente mostra che l'aggiornamento è in attesa della risoluzione degli errori del cluster.  In questa fase, selezionare *Pausa* nell'interfaccia utente non funzionerà, perché l'aggiornamento attende che il cluster sia integro.  Sarà necessario contattare il supporto NetApp per ricevere assistenza nell'indagine sul guasto.

NetApp Hybrid Cloud Control ha un periodo di attesa preimpostato di tre ore, durante il quale può verificarsi uno dei seguenti scenari:

* Gli errori del cluster vengono risolti entro la finestra temporale di tre ore e l'aggiornamento riprende.  In questo scenario non è necessario intraprendere alcuna azione.
* Il problema persiste dopo tre ore e lo stato dell'aggiornamento mostra *Errore* con un banner rosso.  Dopo aver risolto il problema, puoi riprendere l'aggiornamento selezionando *Riprendi*.
* Il supporto NetApp ha stabilito che l'aggiornamento deve essere interrotto temporaneamente per adottare misure correttive prima della scadenza delle tre ore.  Il supporto utilizzerà l'API per annullare l'aggiornamento.



CAUTION: L'interruzione dell'aggiornamento del cluster durante l'aggiornamento di un nodo potrebbe comportare la rimozione non corretta delle unità dal nodo.  Se le unità vengono rimosse in modo improprio, aggiungerle nuovamente durante un aggiornamento richiederà l'intervento manuale del supporto NetApp .  Il nodo potrebbe impiegare più tempo per eseguire gli aggiornamenti del firmware o le attività di sincronizzazione post-aggiornamento.  Se l'aggiornamento sembra bloccato, contattare il supporto NetApp per ricevere assistenza.



== Utilizzare l'API NetApp Hybrid Cloud Control per aggiornare il firmware di storage

È possibile utilizzare le API per aggiornare i nodi di archiviazione in un cluster alla versione più recente del software Element.  Puoi utilizzare lo strumento di automazione che preferisci per eseguire le API.  Il flusso di lavoro API qui documentato utilizza come esempio l'interfaccia utente dell'API REST disponibile sul nodo di gestione.

.Passi
. Scaricare il pacchetto di aggiornamento del firmware di archiviazione su un dispositivo accessibile al nodo di gestione; andare al software Element https://mysupport.netapp.com/site/products/all/details/element-software/downloads-tab["pagina dei download"^] e scaricare l'immagine del firmware di archiviazione più recente.
. Caricare il pacchetto di aggiornamento del firmware di archiviazione sul nodo di gestione:
+
.. Aprire l'interfaccia utente dell'API REST del nodo di gestione sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/package-repository/1/
----
.. Seleziona *Autorizza* e completa quanto segue:
+
... Immettere il nome utente e la password del cluster.
... Inserisci l'ID cliente come `mnode-client` .
... Selezionare *Autorizza* per iniziare una sessione.
... Chiudere la finestra di autorizzazione.


.. Dall'interfaccia utente dell'API REST, seleziona *POST /packages*.
.. Seleziona *Provalo*.
.. Selezionare *Sfoglia* e selezionare il pacchetto di aggiornamento.
.. Selezionare *Esegui* per avviare il caricamento.
.. Dalla risposta, copia e salva l'ID del pacchetto(`"id"` ) per utilizzarlo in una fase successiva.


. Verificare lo stato del caricamento.
+
.. Dall'interfaccia utente dell'API REST, seleziona *GET​ /packages​/{id}​/status*.
.. Seleziona *Provalo*.
.. Inserisci l'ID del pacchetto firmware copiato nel passaggio precedente in *id*.
.. Selezionare *Esegui* per avviare la richiesta di stato.
+
La risposta indica `state` COME `SUCCESS` una volta completato.



. Individuare l'ID della risorsa di installazione:
+
.. Aprire l'interfaccia utente dell'API REST del nodo di gestione sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Seleziona *Autorizza* e completa quanto segue:
+
... Immettere il nome utente e la password del cluster.
... Inserisci l'ID cliente come `mnode-client` .
... Selezionare *Autorizza* per iniziare una sessione.
... Chiudere la finestra di autorizzazione.


.. Dall'interfaccia utente dell'API REST, seleziona *GET /installations*.
.. Seleziona *Provalo*.
.. Selezionare *Esegui*.
.. Dalla risposta, copia l'ID della risorsa di installazione(`id` ).
+
[listing, subs="+quotes"]
----
*"id": "abcd01e2-xx00-4ccf-11ee-11f111xx9a0b",*
"management": {
  "errors": [],
  "inventory": {
    "authoritativeClusterMvip": "10.111.111.111",
    "bundleVersion": "2.14.19",
    "managementIp": "10.111.111.111",
    "version": "1.4.12"
----
.. Dall'interfaccia utente dell'API REST, seleziona *GET /installations/{id}*.
.. Seleziona *Provalo*.
.. Incolla l'ID della risorsa di installazione nel campo *id*.
.. Selezionare *Esegui*.
.. Dalla risposta, copia e salva l'ID del cluster di archiviazione(`"id"` ) del cluster che intendi aggiornare per utilizzarlo in un passaggio successivo.
+
[listing, subs="+quotes"]
----
"storage": {
  "errors": [],
  "inventory": {
    "clusters": [
      {
        "clusterUuid": "a1bd1111-4f1e-46zz-ab6f-0a1111b1111x",
        *"id": "a1bd1111-4f1e-46zz-ab6f-a1a1a111b012",*
----


. Eseguire l'aggiornamento del firmware di archiviazione:
+
.. Aprire l'interfaccia utente dell'API REST di archiviazione sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/storage/1/
----
.. Seleziona *Autorizza* e completa quanto segue:
+
... Immettere il nome utente e la password del cluster.
... Inserisci l'ID cliente come `mnode-client` .
... Selezionare *Autorizza* per iniziare una sessione.
... Chiudi la finestra.


.. Selezionare *POST /aggiornamenti*.
.. Seleziona *Provalo*.
.. Immettere l'ID del pacchetto di aggiornamento nel campo dei parametri.
.. Immettere l'ID del cluster di archiviazione nel campo dei parametri.
.. Selezionare *Esegui* per avviare l'aggiornamento.
+
La risposta dovrebbe indicare lo stato come `initializing` :

+
[listing, subs="+quotes"]
----
{
  "_links": {
    "collection": "https://localhost:442/storage/upgrades",
    "self": "https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1",
    "log": https://localhost:442/storage/upgrades/3fa85f64-1111-4562-b3fc-2c963f66abc1/log
  },
  "storageId": "114f14a4-1a1a-11e9-9088-6c0b84e200b4",
  "upgradeId": "334f14a4-1a1a-11e9-1055-6c0b84e2001b4",
  "packageId": "774f14a4-1a1a-11e9-8888-6c0b84e200b4",
  "config": {},
  *"state": "initializing",*
  "status": {
    "availableActions": [
      "string"
    ],
    "message": "string",
    "nodeDetails": [
      {
        "message": "string",
        "step": "NodePreStart",
        "nodeID": 0,
        "numAttempt": 0
      }
    ],
    "percent": 0,
    "step": "ClusterPreStart",
    "timestamp": "2020-04-21T22:10:57.057Z",
    "failedHealthChecks": [
      {
        "checkID": 0,
        "name": "string",
        "displayName": "string",
        "passed": true,
        "kb": "string",
        "description": "string",
        "remedy": "string",
        "severity": "string",
        "data": {},
        "nodeID": 0
      }
    ]
  },
  "taskId": "123f14a4-1a1a-11e9-7777-6c0b84e123b2",
  "dateCompleted": "2020-04-21T22:10:57.057Z",
  "dateCreated": "2020-04-21T22:10:57.057Z"
}
----
.. Copia l'ID di aggiornamento(`"upgradeId"` ) che fa parte della risposta.


. Verificare l'avanzamento e i risultati dell'aggiornamento:
+
.. Selezionare *GET ​/upgrades/{upgradeId}*.
.. Seleziona *Provalo*.
.. Inserisci l'ID di aggiornamento del passaggio precedente in *upgradeId*.
.. Selezionare *Esegui*.
.. Se durante l'aggiornamento si verificano problemi o si verificano requisiti particolari, procedere come segue:
+
[cols="2*"]
|===
| Opzione | Passi 


| È necessario correggere i problemi di integrità del cluster dovuti a `failedHealthChecks` messaggio nel corpo della risposta.  a| 
... Andare all'articolo specifico della Knowledge Base elencato per ciascun problema oppure eseguire la soluzione specificata.
... Se viene specificata una KB, completare la procedura descritta nell'articolo della KB pertinente.
... Dopo aver risolto i problemi del cluster, ripetere l'autenticazione se necessario e selezionare *PUT ​/upgrades/{upgradeId}*.
... Seleziona *Provalo*.
... Inserisci l'ID di aggiornamento del passaggio precedente in *upgradeId*.
... Entra `"action":"resume"` nel corpo della richiesta.
+
[listing]
----
{
  "action": "resume"
}
----
... Selezionare *Esegui*.




| È necessario sospendere l'aggiornamento perché la finestra di manutenzione sta per chiudersi o per un altro motivo.  a| 
... Se necessario, ripetere l'autenticazione e selezionare *PUT ​/upgrades/{upgradeId}*.
... Seleziona *Provalo*.
... Inserisci l'ID di aggiornamento del passaggio precedente in *upgradeId*.
... Entra `"action":"pause"` nel corpo della richiesta.
+
[listing]
----
{
  "action": "pause"
}
----
... Selezionare *Esegui*.


|===
.. Eseguire l'API *GET ​/upgrades/{upgradeId}* più volte, secondo necessità, fino al completamento del processo.
+
Durante l'aggiornamento, il `status` indica `running` se non si riscontrano errori.  Man mano che ogni nodo viene aggiornato, il `step` il valore cambia in `NodeFinished` .

+
L'aggiornamento è terminato con successo quando `percent` il valore è `100` e il `state` indica `finished` .





[discrete]
== Trova maggiori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]

