---
sidebar: sidebar 
permalink: mnode/task_mnode_configure_proxy_server.html 
summary: Se il cluster si trova dietro un server proxy, è necessario configurare le impostazioni del proxy per raggiungere una rete pubblica. 
keywords: netapp, Element, mnode, api, management node, add proxy, proxy server 
---
= Configurare un server proxy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se il cluster si trova dietro un server proxy, è necessario configurare le impostazioni del proxy in modo da poter raggiungere una rete pubblica.

Un server proxy viene utilizzato per i collettori di telemetria e le connessioni tunnel inverse.  È possibile abilitare e configurare un server proxy tramite l'interfaccia utente dell'API REST se non è stato già configurato un server proxy durante l'installazione o l'aggiornamento.  È anche possibile modificare le impostazioni del server proxy esistente o disabilitare un server proxy.

Il comando per configurare un server proxy aggiorna e restituisce le impostazioni proxy correnti per il nodo di gestione.  Le impostazioni proxy vengono utilizzate da Active IQ, dal servizio di monitoraggio NetApp e da altre utilità software Element installate sul nodo di gestione, incluso il tunnel di supporto inverso per il supporto NetApp .

.Prima di iniziare
* Dovresti conoscere le informazioni sull'host e sulle credenziali del server proxy che stai configurando.
* Assicurati che la versione del tuo cluster esegua il software NetApp Element 11.3 o versione successiva.
* Assicurarsi di aver distribuito un nodo di gestione che esegue la versione 11.3 o successiva.
* (Nodo di gestione 12.0 e versioni successive) Hai aggiornato NetApp Hybrid Cloud Control alla versione 2.16 dei servizi di gestione prima di configurare un server proxy.


.Passi
. Accedi all'interfaccia utente dell'API REST sul nodo di gestione immettendo l'indirizzo IP del nodo di gestione seguito da `/mnode` :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
. Seleziona *Autorizza* o qualsiasi icona a forma di lucchetto e completa quanto segue:
+
.. Immettere il nome utente e la password del cluster.
.. Inserisci l'ID cliente come `mnode-client` .
.. Selezionare *Autorizza* per iniziare una sessione.
.. Chiudi la finestra.


. Selezionare *METTI /impostazioni*.
. Seleziona *Provalo*.
. Per abilitare un server proxy, è necessario impostare `use_proxy` al vero.  Immettere l'IP o il nome host e le destinazioni della porta proxy.
+
Il nome utente proxy, la password proxy e la porta SSH sono facoltativi e devono essere omessi se non utilizzati.

+
[listing]
----
{
"proxy_ip_or_hostname": "[IP or name]",
"use_proxy": [true/false],
"proxy_username": "[username]",
"proxy_password": "[password]",
"proxy_port": [port value],
"proxy_ssh_port": [port value: default is 443]
}
----
. Selezionare *Esegui*.



NOTE: A seconda dell'ambiente, potrebbe essere necessario riavviare il nodo di gestione.

[discrete]
== Trova maggiori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]

