---
sidebar: sidebar 
permalink: mnode/task_mnode_edit_vcenter_assets.html 
summary: 'È possibile modificare i controller dei nodi di gestione vCenter tramite l"interfaccia utente dell"API REST.' 
keywords: netapp, mnode, management node, rest api, Element 
---
= Visualizza o modifica le risorse del controller esistenti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile visualizzare informazioni sui controller VMware vCenter esistenti e modificarli nella configurazione del nodo di gestione utilizzando l'API REST.  I controller sono istanze VMware vCenter registrate sul nodo di gestione per l'installazione di NetApp SolidFire .

.Prima di iniziare
* Assicurati che la versione del tuo cluster esegua il software NetApp Element 11.3 o versione successiva.
* Assicurarsi di aver distribuito un nodo di gestione che esegue la versione 11.3 o successiva.




== Accedi all'API REST dei servizi di gestione

.Passi
. Accedi all'interfaccia utente dell'API REST per i servizi di gestione immettendo l'indirizzo IP del nodo di gestione seguito da `/vcenter/1/` :
+
[listing]
----
https://<ManagementNodeIP>/vcenter/1/
----
. Seleziona *Autorizza* o qualsiasi icona a forma di lucchetto e completa quanto segue:
+
.. Immettere il nome utente e la password del cluster.
.. Inserisci l'ID cliente come `mnode-client` .
.. Selezionare *Autorizza* per iniziare una sessione.
.. Chiudi la finestra.






== Visualizza le informazioni memorizzate sui controller esistenti

È possibile elencare i controller vCenter esistenti registrati nel nodo di gestione e visualizzare le informazioni archiviate su di essi utilizzando l'API REST.

.Passi
. Selezionare *GET /compute/controllers*.
. Seleziona *Provalo*.
. Selezionare *Esegui*.
+
L'API restituisce un elenco di tutti i controller vCenter noti, insieme all'indirizzo IP, all'ID del controller, al nome host e all'ID utente utilizzati per comunicare con ciascun controller.

. Se si desidera conoscere lo stato di connessione di un particolare controller, copiare l'ID del controller da `id` campo di quel controller negli appunti e vedere<<Visualizza lo stato di un controller esistente>> .




== Visualizza lo stato di un controller esistente

È possibile visualizzare lo stato di tutti i controller vCenter esistenti registrati nel nodo di gestione.  L'API restituisce uno stato che indica se NetApp Hybrid Cloud Control può connettersi al controller vCenter, nonché il motivo di tale stato.

.Passi
. Selezionare *GET /compute/controllers/{controller_id}/status*.
. Seleziona *Provalo*.
. Inserisci l'ID del controller copiato in precedenza nel `controller_id` parametro.
. Selezionare *Esegui*.
+
L'API restituisce lo stato di questo specifico controller vCenter, insieme al motivo di tale stato.





== Modifica le proprietà memorizzate di un controller

È possibile modificare il nome utente o la password memorizzati per uno qualsiasi dei controller vCenter esistenti registrati con il nodo di gestione.  Non è possibile modificare l'indirizzo IP memorizzato di un controller vCenter esistente.

.Passi
. Selezionare *PUT /compute/controllers/{controller_id}*.
. Immettere l'ID del controller di un controller vCenter nel `controller_id` parametro.
. Seleziona *Provalo*.
. Modificare uno dei seguenti parametri nel campo *Corpo della richiesta*:
+
|===
| Parametro | Tipo | Descrizione 


| `userId` | corda | Modificare l'ID utente utilizzato per comunicare con il controller vCenter (l'utente deve disporre di privilegi di amministratore). 


| `password` | corda | Modificare la password utilizzata per comunicare con il controller vCenter. 
|===
. Selezionare *Esegui*.
+
L'API restituisce informazioni aggiornate sul controller.



[discrete]
== Trova maggiori informazioni

* link:task_mnode_add_assets.html["Aggiungere una risorsa controller al nodo di gestione"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]

