---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_activeIQ.html 
summary: 'È possibile utilizzare il nodo di gestione (mNode) per abilitare Active IQ per l"archiviazione all-flash SolidFire .' 
keywords: netapp, Element, api, enable, active iq, activeiq 
---
= Abilita il monitoraggio Active IQ e NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile abilitare il monitoraggio dell'archiviazione Active IQ se non lo si è già fatto durante l'installazione o l'aggiornamento.  Potrebbe essere necessario utilizzare questa procedura se non è stato configurato SolidFire Active IQ durante l'installazione di un sistema di archiviazione all-flash SolidFire .

Il servizio di raccolta Active IQ inoltra i dati di configurazione e le metriche delle prestazioni del cluster basate sul software Element a SolidFire Active IQ per la creazione di report storici e il monitoraggio delle prestazioni quasi in tempo reale.  Il servizio di monitoraggio NetApp consente l'inoltro degli errori del cluster di storage a vCenter per la notifica degli avvisi.

.Prima di iniziare
* Alcune funzioni di Active IQ, ad esempio la qualità del servizio (QoS), richiedono Element 11.3 o versioni successive per funzionare correttamente.  Per verificare di essere in grado di utilizzare tutte le funzioni di Active IQ , NetApp consiglia quanto segue:
+
** Il cluster di archiviazione esegue il software NetApp Element 11.3 o versione successiva.
** Hai distribuito un nodo di gestione che esegue la versione 11.3 o successiva.


* Hai accesso a Internet.  Il servizio di raccolta Active IQ non può essere utilizzato da siti oscuri privi di connettività esterna.


.Passi
. Ottieni l'ID risorsa di base per l'installazione:
+
.. Aprire l'interfaccia utente dell'API REST del servizio di inventario sul nodo di gestione:
+
[listing]
----
https://<ManagementNodeIP>/inventory/1/
----
.. Seleziona *Autorizza* e completa quanto segue:
+
... Immettere il nome utente e la password del cluster.
... Inserisci l'ID cliente come `mnode-client` .
... Selezionare *Autorizza* per iniziare una sessione.
... Chiudi la finestra.


.. Dall'interfaccia utente dell'API REST, seleziona *GET ​/installations*.
.. Seleziona *Provalo*.
.. Selezionare *Esegui*.
.. Dal corpo della risposta del codice 200, copiare il `id` per l'installazione.
+
[listing, subs="+quotes"]
----
{
  "installations": [
    {
      "_links": {
        "collection": "https://10.111.211.111/inventory/1/installations",
        "self": "https://10.111.217.111/inventory/1/installations/abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x"
      },
      *"id": "abcd01e2-ab00-1xxx-91ee-12f111xxc7x0x",*
----
+

NOTE: L'installazione presenta una configurazione di risorse di base creata durante l'installazione o l'aggiornamento.



. Attiva la telemetria:
+
.. Accedi all'interfaccia utente dell'API del servizio mnode sul nodo di gestione immettendo l'indirizzo IP del nodo di gestione seguito da `/mnode` :
+
[listing]
----
https://<ManagementNodeIP>/mnode
----
.. Seleziona *Autorizza* o qualsiasi icona a forma di lucchetto e completa quanto segue:
+
... Immettere il nome utente e la password del cluster.
... Inserisci l'ID cliente come `mnode-client` .
... Selezionare *Autorizza* per iniziare una sessione.
... Chiudi la finestra.


.. Configura la risorsa di base:
+
... Selezionare *PUT /assets/{asset_id}*.
... Seleziona *Provalo*.
... Inserire quanto segue nel payload JSON:
+
[listing]
----
{
"telemetry_active": true
"config": {}
}
----
... Inserire l'ID base del passaggio precedente in *asset_ID*.
... Selezionare *Esegui*.
+
Il servizio Active IQ viene riavviato automaticamente ogni volta che vengono modificate le risorse.  La modifica delle risorse comporta un breve ritardo prima che le impostazioni vengano applicate.





. Se non lo hai già fatto, aggiungi una risorsa del controller vCenter per NetApp Hybrid Cloud Control alle risorse note del nodo di gestione:
+

NOTE: Per i servizi di monitoraggio NetApp è necessaria una risorsa controller.

+
.. Selezionare *POST /assets/{asset_id}/controllers* per aggiungere una sotto-risorsa del controller.
.. Seleziona *Provalo*.
.. Inserisci l'ID della risorsa di base padre che hai copiato negli appunti nel campo *asset_id*.
.. Inserire i valori di carico utile richiesti con `type` COME `vCenter` e credenziali vCenter.
+
[listing]
----
{
"username": "string",
"password": "string",
"ip": "string",
"type": "vCenter",
"host_name": "string",
"config": {}
}
----
+

NOTE: `ip`è l'indirizzo IP di vCenter.

.. Selezionare *Esegui*.




[discrete]
== Trova maggiori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]

