---
sidebar: sidebar 
permalink: mnode/task_mnode_enable_remote_support_connections.html 
summary: 'È possibile utilizzare il nodo di gestione per abilitare l"accesso al supporto NetApp per la risoluzione dei problemi.' 
keywords: netapp, mnode, management node, connect to support, support tunnel, rst 
---
= Avvia una sessione di supporto NetApp remota
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Se hai bisogno di supporto tecnico per il tuo sistema di storage all-flash SolidFire , il supporto NetApp può connettersi in remoto al tuo sistema.  Per avviare una sessione e ottenere l'accesso remoto, il supporto NetApp può aprire una connessione SSH (Reverse Secure Shell) al tuo ambiente.

È possibile aprire una porta TCP per una connessione tunnel inversa SSH con il supporto NetApp .  Questa connessione consente al supporto NetApp di accedere al nodo di gestione.

.Prima di iniziare
* Per i servizi di gestione 2.18 e versioni successive, la funzionalità di accesso remoto è disabilitata per impostazione predefinita sul nodo di gestione.  Per abilitare la funzionalità di accesso remoto, vedere https://docs.netapp.com/us-en/element-software/mnode/task_mnode_ssh_management.html["Gestire la funzionalità SSH sul nodo di gestione"] .
* Se il nodo di gestione si trova dietro un server proxy, nel file sshd.config sono richieste le seguenti porte TCP:
+
[cols="15,25,60"]
|===
| porta TCP | Descrizione | Direzione di connessione 


| 443 | Chiamate API/HTTPS per l'inoltro inverso delle porte tramite tunnel di supporto aperto all'interfaccia utente Web | Nodo di gestione per nodi di archiviazione 


| 22 | Accesso di accesso SSH | Da nodo di gestione a nodi di archiviazione o da nodi di archiviazione a nodo di gestione 
|===


.Passi
* Accedi al tuo nodo di gestione e apri una sessione terminale.
* Al prompt, immettere quanto segue:
+
`rst -r  sfsupport.solidfire.com -u element -p <port_number>`

* Per chiudere il tunnel di supporto remoto, immettere quanto segue:
+
`rst --killall`

* (Facoltativo) Disabilita https://docs.netapp.com/us-en/element-software/mnode/task_mnode_ssh_management.html["funzionalità di accesso remoto"] Ancora.
+

NOTE: Se non lo si disabilita, SSH rimane abilitato sul nodo di gestione.  La configurazione abilitata per SSH persiste sul nodo di gestione attraverso aggiornamenti e upgrade finché non viene disabilitata manualmente.





== Trova maggiori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]

