---
sidebar: sidebar 
permalink: mnode/task_mnode_ssh_management.html 
summary: 'È possibile disabilitare e abilitare la funzionalità SSH sul nodo di gestione utilizzando l"interfaccia utente NetApp Hybrid Cloud Control o l"interfaccia utente dell"API REST oppure determinare lo stato della funzionalità di connessione del supporto SSH utilizzando l"interfaccia utente dell"API REST.' 
keywords: netapp, mnode, management node, ssh, disable, enable, rest api, hybrid, cloud, control, hcc 
---
= Gestire la funzionalità SSH sul nodo di gestione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
È possibile disattivare, riattivare o determinare lo stato della funzionalità SSH sul nodo di gestione (mNode) utilizzando l'API REST.  Capacità SSH che forniscelink:task_mnode_enable_remote_support_connections.html["Accesso alla sessione del tunnel di supporto remoto (RST) del supporto NetApp"] è disabilitato per impostazione predefinita sui nodi di gestione che eseguono i servizi di gestione 2.18 o versioni successive.

A partire da Management Services 2.20.69, è possibile abilitare e disabilitare la funzionalità SSH sul nodo di gestione utilizzando l'interfaccia utente di controllo NetApp Hybrid Cloud.

.Cosa ti servirà
* * Autorizzazioni NetApp Hybrid Cloud Control*: hai le autorizzazioni di amministratore.
* *Autorizzazioni di amministratore del cluster*: disponi delle autorizzazioni di amministratore sul cluster di archiviazione.
* *Software Element*: il cluster esegue il software NetApp Element 11.3 o versione successiva.
* *Nodo di gestione*: hai distribuito un nodo di gestione che esegue la versione 11.3 o successiva.
* *Aggiornamenti sui servizi di gestione*:
+
** Per utilizzare l'interfaccia utente di controllo NetApp Hybrid Cloud, è necessario aggiornare https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["pacchetto di servizi di gestione"^] alla versione 2.20.69 o successiva.
** Per utilizzare l'interfaccia utente dell'API REST, è necessario aggiornare il proprio https://mysupport.netapp.com/site/products/all/details/mgmtservices/downloads-tab["pacchetto di servizi di gestione"^] alla versione 2.17.




.Opzioni
* <<Disabilitare o abilitare la funzionalità SSH sul nodo di gestione utilizzando l'interfaccia utente di controllo NetApp Hybrid Cloud>>


Dopo aver effettuato l'accesso, puoi eseguire una qualsiasi delle seguenti attività:link:task_mnode_api_get_authorizationtouse.html["autenticare"] :

* <<Disabilitare o abilitare la funzionalità SSH sul nodo di gestione tramite API>>
* <<Determinare lo stato della capacità SSH sul nodo di gestione utilizzando le API>>




== Disabilitare o abilitare la funzionalità SSH sul nodo di gestione utilizzando l'interfaccia utente di controllo NetApp Hybrid Cloud

È possibile disattivare o riattivare la funzionalità SSH sul nodo di gestione.  Capacità SSH che forniscelink:task_mnode_enable_remote_support_connections.html["Accesso alla sessione del tunnel di supporto remoto (RST) del supporto NetApp"] è disabilitato per impostazione predefinita sui nodi di gestione che eseguono i servizi di gestione 2.18 o versioni successive.  La disabilitazione di SSH non termina né disconnette le sessioni client SSH esistenti al nodo di gestione.  Se si disabilita SSH e si sceglie di riabilitarlo in un secondo momento, è possibile farlo tramite l'interfaccia utente di controllo NetApp Hybrid Cloud.


NOTE: Per abilitare o disabilitare l'accesso al supporto tramite SSH per un cluster di archiviazione, è necessario utilizzarelink:../storage/task_system_manage_cluster_enable_and_disable_support_access.html["Pagina delle impostazioni del cluster dell'interfaccia utente dell'elemento"] .

.Passi
. Dalla Dashboard, seleziona il menu delle opzioni in alto a destra e seleziona *Configura*.
. Nella schermata *Supporto accesso per nodo di gestione*, attiva l'interruttore per abilitare SSH del nodo di gestione.
. Dopo aver completato la risoluzione dei problemi, nella schermata *Supporto accesso per nodo di gestione*, attiva l'interruttore per disabilitare SSH del nodo di gestione.




== Disabilitare o abilitare la funzionalità SSH sul nodo di gestione tramite API

È possibile disattivare o riattivare la funzionalità SSH sul nodo di gestione.  Capacità SSH che forniscelink:task_mnode_enable_remote_support_connections.html["Accesso alla sessione del tunnel di supporto remoto (RST) del supporto NetApp"] è disabilitato per impostazione predefinita sui nodi di gestione che eseguono i servizi di gestione 2.18 o versioni successive.  La disabilitazione di SSH non termina né disconnette le sessioni client SSH esistenti al nodo di gestione.  Se disabiliti SSH e decidi di riabilitarlo in un secondo momento, puoi farlo utilizzando la stessa API.

.comando API
Per i servizi di gestione 2.18 o successivi:

[listing]
----
curl -k -X PUT "https://<<ManagementNodeIP>/mnode/2/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----
Per i servizi di gestione 2.17 o precedenti:

[listing]
----
curl -X PUT "https://<ManagementNodeIP>/mnode/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----

NOTE: Puoi trovare il portatore `${TOKEN}` utilizzato dal comando API quando silink:task_mnode_api_get_authorizationtouse.html["autorizzare"] .  Il portatore `${TOKEN}` è nella risposta del ricciolo.

.Passaggi dell'interfaccia utente dell'API REST
. Accedi all'interfaccia utente dell'API REST per il servizio API del nodo di gestione immettendo l'indirizzo IP del nodo di gestione seguito da `/mnode/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Seleziona *Autorizza* e completa quanto segue:
+
.. Immettere il nome utente e la password del cluster.
.. Inserisci l'ID cliente come `mnode-client` .
.. Selezionare *Autorizza* per iniziare una sessione.
.. Chiudi la finestra.


. Dall'interfaccia utente dell'API REST, selezionare *PUT /settings​/ssh*.
+
.. Seleziona *Provalo*.
.. Imposta il parametro *abilitato* su `false` per disabilitare SSH o `true` per riattivare la funzionalità SSH precedentemente disabilitata.
.. Selezionare *Esegui*.






== Determinare lo stato della capacità SSH sul nodo di gestione utilizzando le API

È possibile determinare se la funzionalità SSH è abilitata o meno sul nodo di gestione utilizzando un'API del servizio del nodo di gestione.  SSH è disabilitato per impostazione predefinita sui nodi di gestione che eseguono servizi di gestione versione 2.18 o successiva.

.comando API
Per i servizi di gestione 2.18 o successivi:

[listing]
----
curl -k -X PUT "https://<<ManagementNodeIP>/mnode/2/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----
Per i servizi di gestione 2.17 o precedenti:

[listing]
----
curl -X PUT "https://<ManagementNodeIP>/mnode/settings/ssh?enabled=<false/true>" -H  "accept: application/json" -H  "Authorization: Bearer ${TOKEN}"
----

NOTE: Puoi trovare il portatore `${TOKEN}` utilizzato dal comando API quando silink:task_mnode_api_get_authorizationtouse.html["autorizzare"] .  Il portatore `${TOKEN}` è nella risposta del ricciolo..

.Passaggi dell'interfaccia utente dell'API REST
. Accedi all'interfaccia utente dell'API REST per il servizio API del nodo di gestione immettendo l'indirizzo IP del nodo di gestione seguito da `/mnode/` :
+
[listing]
----
https://<ManagementNodeIP>/mnode/
----
. Seleziona *Autorizza* e completa quanto segue:
+
.. Immettere il nome utente e la password del cluster.
.. Inserisci l'ID cliente come `mnode-client` .
.. Selezionare *Autorizza* per iniziare una sessione.
.. Chiudi la finestra.


. Dall'interfaccia utente dell'API REST, seleziona *GET /settings​/ssh*.
+
.. Seleziona *Provalo*.
.. Selezionare *Esegui*.




[discrete]
== Trova maggiori informazioni

* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]

