= Trova maggiori informazioni
:allow-uri-read: 


È possibile modificare il certificato SSL predefinito e la chiave privata del nodo di archiviazione nel cluster utilizzando l'API NetApp Element .

Quando viene creato un cluster software NetApp Element , il cluster crea un certificato Secure Sockets Layer (SSL) autofirmato univoco e una chiave privata che vengono utilizzati per tutte le comunicazioni HTTPS tramite l'interfaccia utente Element, l'interfaccia utente per nodo o le API.  Il software Element supporta sia i certificati autofirmati sia i certificati emessi e verificati da un'autorità di certificazione (CA) attendibile.

È possibile utilizzare i seguenti metodi API per ottenere maggiori informazioni sul certificato SSL predefinito e apportare modifiche.

* *OttieniCertificatoSSL*
+
Puoi usare illink:../api/reference_element_api_getsslcertificate.html["Metodo GetSSLCertificate"] per recuperare informazioni sul certificato SSL attualmente installato, compresi tutti i dettagli del certificato.

* *SetSSLCertificate*
+
Puoi usare illink:../api/reference_element_api_setsslcertificate.html["Metodo SetSSLCertificate"] per impostare i certificati SSL del cluster e per nodo sul certificato e sulla chiave privata forniti.  Il sistema convalida il certificato e la chiave privata per impedire che venga applicato un certificato non valido.

* *RimuoviCertificatoSSL*
+
ILlink:../api/reference_element_api_removesslcertificate.html["Metodo RemoveSSLCertificate"] rimuove il certificato SSL e la chiave privata attualmente installati.  Il cluster genera quindi un nuovo certificato autofirmato e una chiave privata.




NOTE: Il certificato SSL del cluster viene applicato automaticamente a tutti i nuovi nodi aggiunti al cluster.  Qualsiasi nodo rimosso dal cluster torna a essere un certificato autofirmato e tutte le informazioni sui certificati e sulle chiavi definite dall'utente vengono rimosse dal nodo.



== Trova maggiori informazioni

* link:../mnode/reference_change_mnode_default_ssl_certificate.html["Modificare il certificato SSL predefinito del nodo di gestione"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/What_are_the_requirements_around_setting_custom_SSL_certificates_in_Element_Software%3F["Quali sono i requisiti per l'impostazione di certificati SSL personalizzati in Element Software?"^]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]

