---
permalink: concepts/concept_solidfire_concepts_accounts_and_permissions.html 
sidebar: sidebar 
keywords: solidfire, element, cluster admin, storage, account, authoritative cluster 
summary: Per amministrare e fornire accesso alle risorse di archiviazione sul tuo sistema, dovrai configurare gli account per le risorse di sistema. 
---
= Account e permessi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Per amministrare e fornire accesso alle risorse di archiviazione sul tuo sistema, dovrai configurare gli account per le risorse di sistema.

Utilizzando Element Storage puoi creare e gestire i seguenti tipi di account:

* <<Account amministratore del cluster di archiviazione,Account utente amministratore per il cluster di archiviazione>>
* <<Account utente,Account utente per l'accesso al volume di archiviazione>>
* <<Account utente autorevoli del cluster,Account utente cluster autorevoli per NetApp Hybrid Cloud Control>>




== Account amministratore del cluster di archiviazione

In un cluster di storage che esegue il software NetApp Element possono esistere due tipi di account amministratore:

* *Account amministratore del cluster primario*: questo account amministratore viene creato quando viene creato il cluster.  Questo account è l'account amministrativo principale con il livello di accesso più elevato al cluster.  Questo account è analogo all'utente root in un sistema Linux.  Puoi modificare la password per questo account amministratore.
* *Account amministratore del cluster*: è possibile concedere a un account amministratore del cluster un intervallo limitato di accesso amministrativo per eseguire attività specifiche all'interno di un cluster.  Le credenziali assegnate a ciascun account amministratore del cluster vengono utilizzate per autenticare le richieste API e Element UI all'interno del sistema di archiviazione.



NOTE: Per accedere ai nodi attivi in un cluster tramite l'interfaccia utente per nodo è necessario un account amministratore del cluster locale (non LDAP).  Per accedere a un nodo che non fa ancora parte di un cluster non sono necessarie le credenziali dell'account.

Puoilink:../storage/concept_system_manage_manage_cluster_administrator_users.html["gestire gli account degli amministratori del cluster"] creando, eliminando e modificando gli account degli amministratori del cluster, cambiando la password degli amministratori del cluster e configurando le impostazioni LDAP per gestire l'accesso al sistema per gli utenti.



== Account utente

Gli account utente vengono utilizzati per controllare l'accesso alle risorse di storage su una rete basata sul software NetApp Element .  È necessario almeno un account utente prima di poter creare un volume.

Quando si crea un volume, questo viene assegnato a un account.  Se hai creato un volume virtuale, l'account è il contenitore di archiviazione.

Ecco alcune considerazioni aggiuntive:

* L'account contiene l'autenticazione CHAP necessaria per accedere ai volumi ad esso assegnati.
* A un account possono essere assegnati fino a 2000 volumi, ma un volume può appartenere a un solo account.
* Gli account utente possono essere gestiti dal punto di estensione NetApp Element Management.




== Account utente autorevoli del cluster

Gli account utente autorevoli del cluster possono eseguire l'autenticazione su qualsiasi risorsa di storage associata all'istanza di NetApp Hybrid Cloud Control di nodi e cluster.  Con questo account puoi gestire volumi, account, gruppi di accesso e altro ancora su tutti i cluster.

Gli account utente autorevoli vengono gestiti tramite l'opzione Gestione utenti nel menu in alto a destra in NetApp Hybrid Cloud Control.

ILlink:../concepts/concept_intro_clusters.html#authoritative-storage-clusters["cluster di archiviazione autorevole"] è il cluster di storage utilizzato da NetApp Hybrid Cloud Control per autenticare gli utenti.

Tutti gli utenti creati sul cluster di storage autorevole possono accedere a NetApp Hybrid Cloud Control.  Gli utenti creati su altri cluster di archiviazione _non_ possono accedere a Hybrid Cloud Control.

* Se il nodo di gestione ha un solo cluster di archiviazione, questo è il cluster autorevole.
* Se il nodo di gestione ha due o più cluster di storage, uno di questi cluster viene assegnato come cluster autorevole e solo gli utenti di quel cluster possono accedere a NetApp Hybrid Cloud Control.


Sebbene molte funzionalità di NetApp Hybrid Cloud Control funzionino con più cluster di storage, l'autenticazione e l'autorizzazione presentano delle limitazioni necessarie.  La limitazione relativa all'autenticazione e all'autorizzazione è che gli utenti del cluster autorevole possono eseguire azioni su altri cluster collegati a NetApp Hybrid Cloud Control anche se non sono utenti degli altri cluster di storage.  Prima di procedere con la gestione di più cluster di archiviazione, è necessario assicurarsi che gli utenti definiti sui cluster autorevoli siano definiti su tutti gli altri cluster di archiviazione con le stesse autorizzazioni.  È possibile gestire gli utenti da NetApp Hybrid Cloud Control.



== Conti di volume

Gli account specifici del volume sono specifici solo del cluster di archiviazione su cui sono stati creati.  Questi account consentono di impostare autorizzazioni su volumi specifici nella rete, ma non hanno alcun effetto al di fuori di tali volumi.

Gli account dei volumi vengono gestiti all'interno della tabella NetApp Hybrid Cloud Control Volumes.
