---
permalink: concepts/concept_solidfire_concepts_nodes.html 
sidebar: sidebar 
keywords: what is, node, management node, storage node, fibre channel, state, pending, active 
summary: 'I nodi sono l"hardware raggruppato in un cluster a cui si può accedere come risorse di archiviazione a blocchi o di elaborazione.' 
---
= Nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I nodi sono risorse hardware o virtuali raggruppate in un cluster per fornire capacità di elaborazione e di archiviazione a blocchi.

Il software NetApp Element definisce vari ruoli dei nodi per un cluster.  I tipi di ruoli dei nodi sono i seguenti:

* <<Nodo di gestione>>
* <<Nodo di archiviazione>>
* <<Nodo Fibre Channel>>


<<Stati operativi del nodo,Stati dei nodi>>variano a seconda dell'associazione del cluster.



== Nodo di gestione

Un nodo di gestione è una macchina virtuale utilizzata per aggiornare e fornire servizi di sistema, tra cui monitoraggio e telemetria, gestire risorse e impostazioni del cluster, eseguire test e utilità di sistema e abilitare l'accesso al supporto NetApp per la risoluzione dei problemi.link:../concepts/concept_intro_management_node.html["Saperne di più"]



== Nodo di archiviazione

Un nodo di archiviazione SolidFire è un server contenente una raccolta di unità che comunicano tra loro tramite l'interfaccia di rete Bond10G.  Le unità nel nodo contengono spazio di blocchi e metadati per l'archiviazione e la gestione dei dati.  Ogni nodo contiene un'immagine di fabbrica del software NetApp Element .

I nodi di archiviazione presentano le seguenti caratteristiche:

* Ogni nodo ha un nome univoco.  Se un nome di nodo non viene specificato da un amministratore, il valore predefinito è SF-XXXX, dove XXXX rappresenta quattro caratteri casuali generati dal sistema.
* Ogni nodo ha la propria cache di scrittura NVRAM(non-volatile random access memory) ad alte prestazioni per migliorare le prestazioni complessive del sistema e ridurre la latenza di scrittura.
* Ogni nodo è collegato a due reti, una di archiviazione e una di gestione, ciascuna con due collegamenti indipendenti per garantire ridondanza e prestazioni.  Ogni nodo richiede un indirizzo IP su ogni rete.
* È possibile creare un cluster con nuovi nodi di archiviazione oppure aggiungere nodi di archiviazione a un cluster esistente per aumentare la capacità e le prestazioni di archiviazione.
* È possibile aggiungere o rimuovere nodi dal cluster in qualsiasi momento senza interrompere il servizio.




== Nodo Fibre Channel

I nodi SolidFire Fibre Channel forniscono connettività a uno switch Fibre Channel, al quale è possibile collegare i client Fibre Channel.  I nodi Fibre Channel fungono da convertitore di protocollo tra i protocolli Fibre Channel e iSCSI; ciò consente di aggiungere la connettività Fibre Channel a qualsiasi cluster SolidFire nuovo o esistente.

I nodi Fibre Channel presentano le seguenti caratteristiche:

* Gli switch Fibre Channel gestiscono lo stato della struttura, garantendo interconnessioni ottimizzate.
* Il traffico tra due porte passa solo attraverso gli switch e non viene trasmesso ad altre porte.
* Il guasto di una porta è isolato e non influisce sul funzionamento delle altre porte.
* In una struttura possono comunicare simultaneamente più coppie di porte.




== Stati operativi del nodo

Un nodo può trovarsi in uno dei diversi stati, a seconda del livello di configurazione.

* *Disponibile*
+
Il nodo non ha alcun nome di cluster associato e non fa ancora parte di un cluster.

* *In attesa di*
+
Il nodo è configurato e può essere aggiunto a un cluster designato.

+
Per accedere al nodo non è richiesta l'autenticazione.

* *In attesa di attivazione*
+
Il sistema sta installando il software Element compatibile sul nodo.  Una volta completato, il nodo passerà allo stato Attivo.

* *Attivo*
+
Il nodo partecipa a un cluster.

+
Per modificare il nodo è richiesta l'autenticazione.



In ognuno di questi stati, alcuni campi sono di sola lettura.



== Trova maggiori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]

