---
permalink: storage/concept_data_manage_volumes_quality_of_service_policies.html 
sidebar: sidebar 
keywords: qos policies, manage, volumes, create, edit, delete 
summary: 'Una policy di qualità del servizio \(QoS\) consente di creare e salvare un"impostazione di qualità del servizio standardizzata che può essere applicata a molti volumi.  È possibile creare, modificare ed eliminare i criteri QoS dalla pagina Criteri QoS nella scheda Gestione.' 
---
= Gestire le politiche di qualità del servizio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un criterio di qualità del servizio (QoS) consente di creare e salvare un'impostazione di qualità del servizio standardizzata che può essere applicata a molti volumi.  È possibile creare, modificare ed eliminare i criteri QoS dalla pagina Criteri QoS nella scheda Gestione.


NOTE: Se si utilizzano criteri QoS, non utilizzare QoS personalizzati su un volume.  La QoS personalizzata sovrascriverà e regolerà i valori dei criteri QoS per le impostazioni QoS del volume.

https://www.youtube.com/embed/q9VCBRDtrnI?rel=0["Video NetApp : Criteri di qualità del servizio SolidFire"]

Vederelink:../concepts/concept_data_manage_volumes_solidfire_quality_of_service.html["Prestazioni e qualità del servizio"] .

* Creare una policy QoS
* Modifica una policy QoS
* Eliminare una policy QoS




== Creare una policy QoS

È possibile creare criteri QoS e applicarli durante la creazione dei volumi.

. Selezionare *Gestione* > *Criteri QoS*.
. Fare clic su *Crea criterio QoS*.
. Inserisci il *Nome della polizza*.
. Immettere i valori **MIN IOPS**, *MAX IOPS* e *Burst IOPS*.
. Fare clic su *Crea criterio QoS*.




== Modifica una policy QoS

È possibile modificare il nome di un criterio QoS esistente o modificare i valori associati al criterio.  La modifica di una policy QoS influisce su tutti i volumi associati alla policy.

. Selezionare *Gestione* > *Criteri QoS*.
. Fare clic sull'icona Azioni per il criterio QoS che si desidera modificare.
. Nel menu che si apre, seleziona **Modifica**.
. Nella finestra di dialogo *Modifica criterio QoS*, modificare le seguenti proprietà come richiesto:
+
** Nome della polizza
** IOPS minimi
** IOPS massimi
** IOPS a raffica


. Fare clic su *Salva modifiche*.




== Eliminare una policy QoS

È possibile eliminare un criterio QoS se non è più necessario.  Quando si elimina un criterio QoS, tutti i volumi associati al criterio mantengono le impostazioni QoS ma non vengono più associati al criterio.


NOTE: Se invece si sta tentando di dissociare un volume da una policy QoS, è possibile modificare le impostazioni QoS per quel volume in personalizzate.

. Selezionare *Gestione* > *Criteri QoS*.
. Fare clic sull'icona Azioni per il criterio QoS che si desidera eliminare.
. Nel menu che appare, seleziona *Elimina*.
. Conferma l'azione.




== Trova maggiori informazioni

* link:task_data_manage_volumes_remove_a_qos_policy_association_of_a_volume.html["Rimuovere l'associazione della policy QoS di un volume"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]

