---
permalink: storage/concept_data_protection_volume_snapshot_backup_operations.html 
sidebar: sidebar 
keywords: volume snapshot, backup operations, back up volume snapshot, cluster, object store 
summary: 'È possibile utilizzare la funzionalità di backup integrata per eseguire il backup di uno snapshot del volume.  È possibile eseguire il backup degli snapshot da un cluster SolidFire a un archivio oggetti esterno o a un altro cluster SolidFire .  Quando si esegue il backup di uno snapshot in un archivio oggetti esterno, è necessario disporre di una connessione all"archivio oggetti che consenta operazioni di lettura/scrittura.' 
---
= Eseguire il backup di uno snapshot del volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare la funzionalità di backup integrata per eseguire il backup di uno snapshot del volume.  È possibile eseguire il backup degli snapshot da un cluster SolidFire a un archivio oggetti esterno o a un altro cluster SolidFire .  Quando si esegue il backup di uno snapshot in un archivio oggetti esterno, è necessario disporre di una connessione all'archivio oggetti che consenta operazioni di lettura/scrittura.

* link:task_data_protection_back_up_a_volume_snapshot_to_an_amazon_s3_object_store.html["Eseguire il backup di uno snapshot del volume in un archivio oggetti Amazon S3"]
* link:task_data_protection_back_up_a_volume_snapshot_to_openstack_swift.html["Eseguire il backup di uno snapshot del volume in un archivio oggetti OpenStack Swift"]
* link:task_data_protection_back_up_volume_to_solidfire.html["Eseguire il backup di uno snapshot del volume su un cluster SolidFire"]

