---
permalink: storage/concept_system_manage_virtual_manage_virtual_networks.html 
sidebar: sidebar 
keywords: virtual networks, manage, traffic, clients, vlan tagging 
summary: 'La rete virtuale nello storage SolidFire consente di connettere a un unico cluster il traffico tra più client che si trovano su reti logiche separate.  Le connessioni al cluster sono separate nello stack di rete tramite l"uso del tagging VLAN.' 
---
= Gestire reti virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La rete virtuale nello storage SolidFire consente di connettere a un unico cluster il traffico tra più client che si trovano su reti logiche separate.  Le connessioni al cluster sono separate nello stack di rete tramite l'uso del tagging VLAN.



== Trova maggiori informazioni

* xref:task_system_manage_virtual_add_a_virtual_network.adoc[Aggiungi una rete virtuale]
* xref:task_system_manage_virtual_enable_virtual_routing_and_forwarding.adoc[Abilita il routing e l'inoltro virtuali]
* xref:task_system_manage_virtual_edit_a_virtual_network.adoc[Modifica una rete virtuale]
* xref:task_system_manage_virtual_edit_vrf_vlans.adoc[Modifica VLAN VRF]
* xref:task_system_manage_virtual_delete_a_virtual_network.adoc[Elimina una rete virtuale]

