---
permalink: storage/concept_system_manage_nodes_cluster_capacity_in_a_mixed_node_environment.html 
sidebar: sidebar 
keywords: nodes, mixed environment, capacity, cluster capacity, mixed nodes, encrypted, non-encrypted, threshold 
summary: È possibile combinare diversi tipi di nodi in un cluster.  Le serie SF 2405, 3010, 4805, 6010, 9605, 9010, 19210, 38410 e la serie H possono coesistere in un cluster. 
---
= Capacità del cluster in un ambiente di nodi misti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile combinare diversi tipi di nodi in un cluster.  Le serie SF 2405, 3010, 4805, 6010, 9605, 9010, 19210, 38410 e la serie H possono coesistere in un cluster.

La serie H è composta dai nodi H610S-1, H610S-2, H610S-4 e H410S.  Questi nodi supportano sia 10GbE che 25GbE.

È meglio non mescolare nodi crittografati e non crittografati.  In un cluster con nodi misti, nessun nodo può essere più grande del 33 percento della capacità totale del cluster.  Ad esempio, in un cluster con quattro nodi SF-Series 4805, il nodo più grande che può essere aggiunto da solo è un SF-Series 9605.  La soglia di capacità del cluster viene calcolata in base alla potenziale perdita del nodo più grande in questa situazione.

A seconda della versione del software Element, i seguenti nodi di archiviazione della serie SF non sono supportati:

[cols="40,40"]
|===
| A partire da... | Nodo di archiviazione non supportato... 


| Elemento 12.8  a| 
* SF4805
* SF9605
* SF19210
* SF38410




| Elemento 12.7  a| 
* SF2405
* SF9608




| Elemento 12.0  a| 
* SF3010
* SF6010
* SF9010


|===
Se si tenta di aggiornare uno di questi nodi a una versione di Element non supportata, verrà visualizzato un errore che indica che il nodo non è supportato da Element 12.x.
