---
permalink: storage/concept_monitor_understand_cluster_fullness_levels.html 
sidebar: sidebar 
keywords: cluster fullness levels, understanding, fullness levels 
summary: 'Il cluster che esegue il software Element genera errori del cluster per avvisare l"amministratore dello storage quando la capacità del cluster sta esaurendo.  Esistono tre livelli di riempimento del cluster, tutti visualizzati nell"interfaccia utente NetApp Element : avviso, errore e critico.' 
---
= Comprendere i livelli di pienezza del cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il cluster che esegue il software Element genera errori del cluster per avvisare l'amministratore dello storage quando la capacità del cluster sta esaurendo.  Esistono tre livelli di riempimento del cluster, tutti visualizzati nell'interfaccia utente NetApp Element : avviso, errore e critico.

Il sistema utilizza il codice di errore BlockClusterFull per avvisare che lo spazio di archiviazione dei blocchi del cluster è pieno.  È possibile visualizzare i livelli di gravità del riempimento del cluster dalla scheda Avvisi dell'interfaccia utente dell'elemento.

L'elenco seguente include informazioni sui livelli di gravità di BlockClusterFull:

* *Avvertimento*
+
Si tratta di un avviso configurabile dal cliente che viene visualizzato quando la capacità del blocco del cluster si avvicina al livello di gravità dell'errore.  Per impostazione predefinita, questo livello è impostato al tre percento al di sotto del livello di errore e può essere regolato tramite l'interfaccia utente e l'API di Element.  È necessario aggiungere ulteriore capacità o liberarne altra il prima possibile.

* *Errore*
+
Quando il cluster si trova in questo stato, se un nodo viene perso, non ci sarà capacità sufficiente nel cluster per ricostruire la protezione dei dati Double Helix.  La creazione di nuovi volumi, i cloni e gli snapshot sono tutti bloccati mentre il cluster si trova in questo stato.  Questo non è uno stato sicuro o consigliato per nessun cluster. È necessario aggiungere ulteriore capacità o liberare capacità immediatamente.

* *Critico*
+
Questo errore critico si è verificato perché il cluster è consumato al 100%.  Si trova in uno stato di sola lettura e non è possibile stabilire nuove connessioni iSCSI con il cluster.  Una volta raggiunta questa fase, è necessario liberare o aggiungere immediatamente altra capacità.



Il sistema utilizza il codice di errore MetadataClusterFull per avvisare che lo spazio di archiviazione dei metadati del cluster è pieno.  È possibile visualizzare la quantità di spazio disponibile per i metadati del cluster nella sezione Capacità del cluster nella pagina Panoramica della scheda Report nell'interfaccia utente dell'elemento.

L'elenco seguente include informazioni sui livelli di gravità MetadataClusterFull:

* *Avvertimento*
+
Si tratta di un avviso configurabile dal cliente che viene visualizzato quando la capacità dei metadati del cluster si avvicina al livello di gravità dell'errore.  Per impostazione predefinita, questo livello è impostato al tre percento al di sotto del livello di errore e può essere regolato tramite l'API Element.  È necessario aggiungere ulteriore capacità o liberarne altra il prima possibile.

* *Errore*
+
Quando il cluster si trova in questo stato, se un nodo viene perso, non ci sarà capacità sufficiente nel cluster per ricostruire la protezione dei dati Double Helix.  La creazione di nuovi volumi, i cloni e gli snapshot sono tutti bloccati mentre il cluster si trova in questo stato.  Questo non è uno stato sicuro o consigliato per nessun cluster. È necessario aggiungere ulteriore capacità o liberare capacità immediatamente.

* *Critico*
+
Questo errore critico si è verificato perché il cluster è consumato al 100%.  Si trova in uno stato di sola lettura e non è possibile stabilire nuove connessioni iSCSI con il cluster.  Una volta raggiunta questa fase, è necessario liberare o aggiungere immediatamente altra capacità.




NOTE: Quanto segue si applica alle soglie dei cluster a due nodi:

* L'errore di completezza dei metadati è inferiore del 20% al livello critico.
* L'errore di riempimento del blocco è pari a 1 unità di blocco (inclusa la capacità bloccata) al di sotto del livello critico, ovvero la capacità è pari a due unità di blocco al di sotto del livello critico.

