---
permalink: storage/concept_intro_fibre_channel_nodes.html 
sidebar: sidebar 
keywords: fibre channel nodes, fibre channel switch, clients, protcols, iSCSi protocols, clusters, interconnections, fc, FC, connectivity, fibre channel connectivity, fibre channel nodes, fibre channel protocol 
summary: I nodi SolidFire Fibre Channel forniscono connettività a uno switch Fibre Channel, al quale è possibile collegare i client Fibre Channel.  I nodi Fibre Channel fungono da convertitore di protocollo tra i protocolli Fibre Channel e iSCSI; ciò consente di aggiungere la connettività Fibre Channel a qualsiasi cluster SolidFire nuovo o esistente. 
---
= Nodi Fibre Channel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I nodi SolidFire Fibre Channel forniscono connettività a uno switch Fibre Channel, al quale è possibile collegare i client Fibre Channel.  I nodi Fibre Channel fungono da convertitore di protocollo tra i protocolli Fibre Channel e iSCSI; ciò consente di aggiungere la connettività Fibre Channel a qualsiasi cluster SolidFire nuovo o esistente.

I nodi Fibre Channel presentano le seguenti caratteristiche:

* Gli switch Fibre Channel gestiscono lo stato della struttura, garantendo interconnessioni ottimizzate.
* Il traffico tra due porte passa solo attraverso gli switch e non viene trasmesso ad altre porte.
* Il guasto di una porta è isolato e non influisce sul funzionamento delle altre porte.
* In una struttura possono comunicare simultaneamente più coppie di porte.

