---
permalink: storage/concept_system_manage_key_external_key_management_api_commands.html 
sidebar: sidebar 
keywords: ekm, api commands, key providers 
summary: Elenco di tutte le API disponibili per la gestione e la configurazione di EKM. 
---
= Comandi API di gestione delle chiavi esterne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Elenco di tutte le API disponibili per la gestione e la configurazione di EKM.

Utilizzato per stabilire una relazione di fiducia tra il cluster e i server esterni di proprietà del cliente:

* Crea coppia di chiavi pubbliche e private
* Ottieni richiesta di firma del certificato del client


Utilizzato per definire i dettagli specifici dei server esterni di proprietà del cliente:

* CreateKeyServerKmip
* ModifyKeyServerKmip
* DeleteKeyServerKmip
* GetKeyServerKmip
* ListKeyServersKmip
* TestKeyServerKmip


Utilizzato per creare e gestire i fornitori di chiavi che gestiscono server di chiavi esterni:

* CreateKeyProviderKmip
* DeleteKeyProviderKmip
* AggiungiKeyServerAlProviderKmip
* RemoveKeyServerFromProviderKmip
* GetKeyProviderKmip
* ListKeyProvidersKmip
* RekeySoftwareEncryptionAtRestMasterKey
* TestKeyProviderKmip


Per informazioni sui metodi API, vedere link:../api/concept_element_api_about_the_api.html["Informazioni di riferimento API"].
