---
permalink: storage/concept_system_manage_key_get_started_with_external_key_management.html 
sidebar: sidebar 
keywords: kmip, master key, key management, encryption at rest, software encryption at rest, ekm, ak, eks, seds 
summary: 'La gestione delle chiavi esterne \(EKM\) fornisce una gestione sicura delle chiavi di autenticazione \(AK\) in combinazione con un server di chiavi esterno esterno al cluster \(EKS\).  Gli AK vengono utilizzati per bloccare e sbloccare le unità SED (Self Encrypting Drive) quando la crittografia a riposo è abilitata sul cluster.' 
---
= Inizia con la gestione delle chiavi esterne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La gestione delle chiavi esterne (EKM) garantisce una gestione sicura delle chiavi di autenticazione (AK) in combinazione con un server di chiavi esterne (EKS) esterno al cluster.  Gli AK vengono utilizzati per bloccare e sbloccare le unità auto-crittografanti (SED) quandolink:../concepts/concept_solidfire_concepts_security.html["crittografia a riposo"] è abilitato sul cluster.  L'EKS garantisce la generazione e l'archiviazione sicura degli AK.  Il cluster utilizza il protocollo KMIP (Key Management Interoperability Protocol), un protocollo standard definito da OASIS, per comunicare con l'EKS.

* link:task_system_manage_key_set_up_external_key_management.html["Impostare la gestione esterna"]
* link:task_system_manage_rekey_software_ear_master_key.html["Crittografia software di reimpostazione della chiave principale a riposo"]
* link:concept_system_manage_key_recover_inaccessible_or_invalid_authentication_keys["Recupera le chiavi di autenticazione inaccessibili o non valide"]
* link:concept_system_manage_key_external_key_management_api_commands.html["Comandi API di gestione delle chiavi esterne"]


[discrete]
== Trova maggiori informazioni

* link:../api/reference_element_api_createcluster.html["API CreateCluster che può essere utilizzata per abilitare la crittografia del software a riposo"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti NetApp SolidFire ed Element"^]

