---
permalink: storage/concept_system_manage_manage_cluster_administrator_users.html 
sidebar: sidebar 
keywords: element, solidfire, cluster admin, account, create, change, configure, administrator access, edit permissions, change passwords 
summary: 'È possibile gestire gli account degli amministratori del cluster per un sistema di archiviazione SolidFire .  Le funzioni di gestione dell"amministratore del cluster disponibili includono la creazione, l"eliminazione e la modifica degli account dell"amministratore del cluster, la modifica della password dell"amministratore del cluster e la configurazione delle impostazioni LDAP per gestire l"accesso al sistema per gli utenti.' 
---
= Gestire gli account utente dell'amministratore del cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile gestire gli account degli amministratori del cluster per un sistema di archiviazione SolidFire creando, eliminando e modificando gli account degli amministratori del cluster, cambiando la password degli amministratori del cluster e configurando le impostazioni LDAP per gestire l'accesso al sistema per gli utenti.



== Tipi di account amministratore del cluster di archiviazione

In un cluster di storage che esegue il software NetApp Element possono esistere due tipi di account amministratore: l'account amministratore del cluster primario e un account amministratore del cluster.

* *Account amministratore del cluster primario*
+
Questo account amministratore viene creato quando viene creato il cluster.  Questo account è l'account amministrativo principale con il livello di accesso più elevato al cluster.  Questo account è analogo all'utente root in un sistema Linux.  Puoi modificare la password per questo account amministratore.

* *Account amministratore del cluster*
+
È possibile concedere a un account amministratore del cluster un intervallo limitato di accessi amministrativi per eseguire attività specifiche all'interno di un cluster.  Le credenziali assegnate a ciascun account amministratore del cluster vengono utilizzate per autenticare le richieste API e Element UI all'interno del sistema di archiviazione.




NOTE: Per accedere ai nodi attivi in un cluster tramite l'interfaccia utente per nodo è necessario un account amministratore del cluster locale (non LDAP).  Per accedere a un nodo che non fa ancora parte di un cluster non sono necessarie le credenziali dell'account.



== Visualizza i dettagli dell'amministratore del cluster

. Per creare un account amministratore del cluster a livello di cluster (non LDAP), eseguire le seguenti operazioni:
+
.. Fare clic su *Utenti* > *Amministratori cluster*.


. Nella pagina Amministratori cluster della scheda Utenti, è possibile visualizzare le seguenti informazioni.
+
** *ID*: Numero sequenziale assegnato all'account dell'amministratore del cluster.
** *Nome utente*: il nome assegnato all'account dell'amministratore del cluster al momento della sua creazione.
** *Accesso*: le autorizzazioni utente assegnate all'account utente. Valori possibili:
+
*** Leggere
*** segnalazione
*** nodi
*** unità
*** volumi
*** conti
*** amministratori del cluster
*** amministratore
*** supportoAdmin




+
[NOTE]
====
Tutte le autorizzazioni sono disponibili per il tipo di accesso amministratore.

Sono disponibili tipi di accesso tramite l'API che non sono disponibili nell'interfaccia utente di Element.

====
+
** *Tipo*: Tipo di amministratore del cluster. Valori possibili:
+
*** Grappolo
*** Ldap


** *Attributi*: se l'account dell'amministratore del cluster è stato creato utilizzando l'API Element, questa colonna mostra tutte le coppie nome-valore impostate utilizzando tale metodo.
+
Vederelink:../api/concept_element_api_about_the_api.html["Riferimento API del software NetApp Element"] .







== Crea un account amministratore del cluster

È possibile creare nuovi account di amministratore del cluster con autorizzazioni per consentire o limitare l'accesso ad aree specifiche del sistema di archiviazione.  Quando si impostano le autorizzazioni dell'account amministratore del cluster, il sistema concede diritti di sola lettura per tutte le autorizzazioni non assegnate all'amministratore del cluster.

Se si desidera creare un account amministratore del cluster LDAP, assicurarsi che LDAP sia configurato sul cluster prima di iniziare.

link:concept_system_manage_manage_ldap.html["Abilita l'autenticazione LDAP con l'interfaccia utente Element"]

In seguito è possibile modificare i privilegi dell'account amministratore del cluster per la creazione di report, nodi, unità, volumi, account e accesso a livello di cluster.  Quando si abilita un'autorizzazione, il sistema assegna l'accesso in scrittura per quel livello.  Il sistema concede all'utente amministratore l'accesso in sola lettura per i livelli non selezionati.

In seguito è anche possibile rimuovere qualsiasi account utente amministratore del cluster creato da un amministratore di sistema.  Non è possibile rimuovere l'account amministratore del cluster primario creato al momento della creazione del cluster.

. Per creare un account amministratore del cluster a livello di cluster (non LDAP), eseguire le seguenti operazioni:
+
.. Fare clic su *Utenti* > *Amministratori cluster*.
.. Fare clic su *Crea amministratore cluster*.
.. Selezionare il tipo di utente *Cluster*.
.. Inserisci un nome utente e una password per l'account e conferma la password.
.. Seleziona le autorizzazioni utente da applicare all'account.
.. Selezionare la casella di controllo per accettare il Contratto di licenza con l'utente finale.
.. Fare clic su *Crea amministratore cluster*.


. Per creare un account amministratore del cluster nella directory LDAP, eseguire le seguenti azioni:
+
.. Fare clic su *Cluster* > *LDAP*.
.. Assicurarsi che l'autenticazione LDAP sia abilitata.
.. Fare clic su *Test autenticazione utente* e copiare il nome distinto visualizzato per l'utente o per uno dei gruppi di cui l'utente è membro, in modo da poterlo incollare in seguito.
.. Fare clic su *Utenti* > *Amministratori cluster*.
.. Fare clic su *Crea amministratore cluster*.
.. Selezionare il tipo di utente LDAP.
.. Nel campo Nome distinto, seguire l'esempio nella casella di testo per immettere un nome distinto completo per l'utente o il gruppo.  In alternativa, incollalo dal nome distinto che hai copiato in precedenza.
+
Se il nome distinto fa parte di un gruppo, qualsiasi utente membro di quel gruppo sul server LDAP avrà le autorizzazioni di questo account amministratore.

+
Per aggiungere utenti o gruppi LDAP Cluster Admin, il formato generale del nome utente è "`LDAP:<Nome distinto completo>`".

.. Seleziona le autorizzazioni utente da applicare all'account.
.. Selezionare la casella di controllo per accettare il Contratto di licenza con l'utente finale.
.. Fare clic su *Crea amministratore cluster*.






== Modifica le autorizzazioni dell'amministratore del cluster

È possibile modificare i privilegi dell'account amministratore del cluster per la creazione di report, nodi, unità, volumi, account e accesso a livello di cluster.  Quando si abilita un'autorizzazione, il sistema assegna l'accesso in scrittura per quel livello.  Il sistema concede all'utente amministratore l'accesso in sola lettura per i livelli non selezionati.

. Fare clic su *Utenti* > *Amministratori cluster*.
. Fare clic sull'icona Azioni relativa all'amministratore del cluster che si desidera modificare.
. Fare clic su *Modifica*.
. Seleziona le autorizzazioni utente da applicare all'account.
. Fare clic su *Salva modifiche*.




== Cambiare le password per gli account degli amministratori del cluster

È possibile utilizzare l'interfaccia utente di Element per modificare le password degli amministratori del cluster.

. Fare clic su *Utenti* > *Amministratori cluster*.
. Fare clic sull'icona Azioni relativa all'amministratore del cluster che si desidera modificare.
. Fare clic su *Modifica*.
. Nel campo Cambia password, inserisci una nuova password e confermala.
. Fare clic su *Salva modifiche*.


.Informazioni correlate
* link:../api/reference_element_api_app_b_access_control.html["Scopri i tipi di accesso disponibili per le API Element"]
* link:concept_system_manage_manage_ldap.html["Abilita l'autenticazione LDAP con l'interfaccia utente Element"]
* link:concept_system_manage_manage_ldap.html["Disabilitare LDAP"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]

