---
permalink: storage/reference_system_manage_fips_ssl_cipher_changes.html 
sidebar: sidebar 
keywords: fips, ssl ciphers, 140-2, encryption algorithms 
summary: I cifrari SSL sono algoritmi di crittografia utilizzati dagli host per stabilire una comunicazione sicura.  Esistono cifrari standard supportati dal software Element e cifrari non standard quando è abilitata la modalità FIPS 140-2. 
---
= Cifrari SSL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I cifrari SSL sono algoritmi di crittografia utilizzati dagli host per stabilire una comunicazione sicura.  Esistono cifrari standard supportati dal software Element e cifrari non standard quando è abilitata la modalità FIPS 140-2.

Gli elenchi seguenti forniscono i cifrari Secure Socket Layer (SSL) standard supportati dal software Element e i cifrari SSL supportati quando è abilitata la modalità FIPS 140-2:

* *FIPS 140-2 disabilitato*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A

+
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_IDEA_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_RC4_128_MD5 (rsa 2048) - C

+
TLS_RSA_WITH_RC4_128_SHA (rsa 2048) - C

+
TLS_RSA_WITH_SEED_CBC_SHA (rsa 2048) - A

* *FIPS 140-2 abilitato*
+
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (dh 2048) - A

+
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 2048) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (sect571r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A

+
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (sect571r1) - A

+
TLS_RSA_WITH_3DES_EDE_CBC_SHA (rsa 2048) - C

+
TLS_RSA_WITH_AES_128_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_AES_128_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_128_GCM_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_CBC_SHA256 (rsa 2048) - A

+
TLS_RSA_WITH_AES_256_GCM_SHA384 (rsa 2048) - A





== Trova maggiori informazioni

xref:task_system_manage_fips_enable_fips_140_2_for_https.adoc[Abilita FIPS 140-2 per HTTPS sul tuo cluster]
