---
permalink: storage/task_data_manage_vvol_create_a_storage_container.html 
sidebar: sidebar 
keywords: storage container, create 
summary: 'È possibile creare contenitori di archiviazione nell"interfaccia utente di Element e individuarli in vCenter.  È necessario creare almeno un contenitore di archiviazione per iniziare il provisioning delle macchine virtuali supportate da VVol.' 
---
= Creare un contenitore di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare contenitori di archiviazione nell'interfaccia utente di Element e individuarli in vCenter.  È necessario creare almeno un contenitore di archiviazione per iniziare il provisioning delle macchine virtuali supportate da VVol.

Hai abilitato la funzionalità VVols nell'interfaccia utente Element per il cluster.

. Selezionare *VVols* > *Contenitori di archiviazione*.
. Fare clic sul pulsante *Crea contenitori di archiviazione*.
. Immettere le informazioni sul contenitore di archiviazione nella finestra di dialogo *Crea un nuovo contenitore di archiviazione*:
+
.. Immettere un nome per il contenitore di archiviazione.
.. Configurare i segreti dell'iniziatore e della destinazione per CHAP.
+

TIP: Lasciare vuoti i campi Impostazioni CHAP per generare automaticamente i segreti.

.. Fare clic sul pulsante *Crea contenitore di archiviazione*.


. Verificare che il nuovo contenitore di archiviazione appaia nell'elenco nella sotto-scheda *Contenitori di archiviazione*.
+

NOTE: Poiché un ID account NetApp Element viene creato automaticamente e assegnato al contenitore di archiviazione, non è necessario creare manualmente un account.


