---
permalink: storage/task_snapmirror_performing_failback_when_source_volume_no_longer_exists.html 
sidebar: sidebar 
keywords: element, ui, failback, perform, source, volume, snapmirror, dr, disaster, recovery 
summary: 'È possibile risincronizzare il volume di origine originale ed eseguire il failback utilizzando l"interfaccia utente NetApp Element .  Questa sezione si applica agli scenari in cui il volume sorgente originale è andato perso ma il cluster originale è ancora intatto.  Per istruzioni su come ripristinare un nuovo cluster, consultare la documentazione sul sito di supporto NetApp .' 
---
= Eseguire un failback quando il volume di origine non esiste più
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile risincronizzare il volume di origine originale ed eseguire il failback utilizzando l'interfaccia utente NetApp Element .  Questa sezione si applica agli scenari in cui il volume sorgente originale è andato perso ma il cluster originale è ancora intatto.  Per istruzioni su come ripristinare un nuovo cluster, consultare la documentazione sul sito di supporto NetApp .

.Cosa ti servirà
* Si è verificata un'interruzione della relazione di replica tra i volumi Element e ONTAP .
* Il volume Element è irrimediabilmente perso.
* Il nome del volume originale risulta NON TROVATO.


.Passi
. Nell'interfaccia utente dell'elemento, individua la relazione che hai interrotto per eseguire il failover.
+
*Migliore pratica:* prendi nota della politica SnapMirror e pianifica i dettagli della relazione interrotta originariamente.  Queste informazioni saranno necessarie per ricreare la relazione.

. Fare clic sull'icona *Azioni* e quindi su *Risincronizzazione inversa*.
. Conferma l'azione.
+

NOTE: L'operazione Reverse Resync crea una nuova relazione in cui i ruoli del volume di origine originale e del volume di destinazione vengono invertiti (ciò determina due relazioni poiché la relazione originale persiste).  Poiché il volume originale non esiste più, il sistema crea un nuovo volume Element con lo stesso nome e le stesse dimensioni del volume di origine originale.  Al nuovo volume viene assegnata una policy QoS predefinita denominata sm-recovery ed è associato a un account predefinito denominato sm-recovery.  Sarà necessario modificare manualmente l'account e la policy QoS per tutti i volumi creati da SnapMirror per sostituire i volumi di origine originali che sono stati distrutti.

+
I dati dell'ultimo snapshot vengono trasferiti al nuovo volume come parte dell'operazione di risincronizzazione inversa.  È possibile continuare ad accedere e scrivere dati sul volume attivo sul lato di destinazione, ma sarà necessario disconnettere tutti gli host dal volume attivo ed eseguire un aggiornamento SnapMirror prima di ripristinare la relazione primaria originale in un passaggio successivo.  Dopo aver completato la risincronizzazione inversa e aver verificato che non vi siano sessioni attive connesse al volume sul lato di destinazione e che i dati più recenti si trovino sul volume primario originale, continuare con i passaggi seguenti per completare il failback e riattivare il volume primario originale:

. Fare clic sull'icona *Azioni* della relazione inversa creata durante l'operazione di risincronizzazione inversa e fare clic su *Interrompi*.
. Fare clic sull'icona *Azioni* della relazione originale, in cui il volume di origine non esiste, e fare clic su *Elimina*.
. Fare clic sull'icona *Azioni* della relazione inversa, che è stata interrotta nel passaggio 4, e fare clic su *Risincronizzazione inversa*.
. In questo modo si invertono l'origine e la destinazione e si ottiene una relazione con lo stesso volume di origine e lo stesso volume di destinazione della relazione originale.
. Fare clic sull'icona *Azioni* e su *Modifica* per aggiornare questa relazione con le impostazioni di pianificazione e i criteri QoS originali di cui si è preso nota.
. Ora è possibile eliminare in sicurezza la relazione inversa che hai risincronizzato al passaggio 6.




== Trova maggiori informazioni

xref:concept_snapmirror_failback_scenarios.adoc[Scenari di failback SnapMirror]
