---
permalink: storage/task-element-replication-make-destination-volume-writeable.html 
sidebar: sidebar 
keywords: ontap, cli, make, destination, volume, write 
summary: È necessario rendere scrivibile il volume di destinazione prima di poter fornire dati dal volume ai client.  È possibile utilizzare il comando snapmirror quiesce per interrompere i trasferimenti pianificati verso la destinazione, il comando snapmirror abort per interrompere i trasferimenti in corso e il comando snapmirror break per rendere la destinazione scrivibile. 
---
= Rendere scrivibile il volume di destinazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando un disastro disabilita il sito primario per una relazione SnapMirror DR, è possibile fornire dati dal volume di destinazione con un'interruzione minima.  È possibile riattivare il volume di origine quando il servizio viene ripristinato nel sito primario.

È necessario rendere scrivibile il volume di destinazione prima di poter fornire dati dal volume ai client.  Puoi usare il `snapmirror quiesce` comando per interrompere i trasferimenti programmati verso la destinazione, il `snapmirror abort` comando per interrompere i trasferimenti in corso e il `snapmirror break` comando per rendere scrivibile la destinazione.

.Informazioni su questo compito
È necessario specificare il percorso sorgente dell'elemento nel modulo `<hostip:>/lun/<name>` , dove "`lun`" è la stringa effettiva "`lun`" e `name` è il nome del volume Element.

.Passi
. Interrompere i trasferimenti programmati verso la destinazione:
+
`snapmirror quiesce -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente interrompe i trasferimenti pianificati tra il volume di origine `0005` all'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` SU `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Interrompere i trasferimenti in corso verso la destinazione:
+
`snapmirror abort -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente interrompe i trasferimenti in corso tra il volume di origine `0005` all'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` SU `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror abort -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----
. Interrompere la relazione SnapMirror DR:
+
`snapmirror break -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente interrompe la relazione tra il volume di origine `0005` all'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` SU `svm_backup` e il volume di destinazione `volA_dst` SU `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror break -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----

