---
permalink: storage/task_data_protection_back_up_volume_to_openstack_swift.html 
sidebar: sidebar 
keywords: volume backup, openstack swift object store 
summary: È possibile eseguire il backup dei volumi su archivi di oggetti esterni compatibili con OpenStack Swift. 
---
= Eseguire il backup di un volume in un archivio oggetti OpenStack Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eseguire il backup dei volumi su archivi di oggetti esterni compatibili con OpenStack Swift.

. Fare clic su *Gestione* > *Volumi*.
. Fare clic sull'icona Azioni relativa al volume di cui eseguire il backup.
. Nel menu visualizzato, fare clic su *Backup su*.
. Nella finestra di dialogo *Backup integrato*, in *Backup su*, selezionare *Swift*.
. Selezionare un formato dati in *Formato dati*:
+
** *Nativo*: formato compresso leggibile solo dai sistemi di archiviazione SolidFire .
** *Non compresso*: formato non compresso compatibile con altri sistemi.


. Immettere un URL da utilizzare per accedere all'archivio oggetti nel campo *URL*.
. Inserisci un nome utente per l'account nel campo *Nome utente*.
. Inserisci la chiave di autenticazione per l'account nel campo *Chiave di autenticazione*.
. Immettere il contenitore in cui archiviare il backup nel campo *Contenitore*.
. *Facoltativo*: inserisci un'etichetta con il nome da aggiungere al prefisso nel campo *Etichetta con il nome*.
. Fare clic su *Inizia a leggere*.

