---
permalink: storage/task-element-replication-enable-snapmirror-cluster.html 
sidebar: sidebar 
keywords: ontap, cli, enable, snapmirror, element, cluster 
summary: 'È necessario abilitare SnapMirror sul cluster Element prima di poter creare una relazione di replica.  È possibile eseguire questa attività solo nell"interfaccia utente Web del software Element o utilizzando i metodi API.' 
---
= Abilita SnapMirror sul cluster Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario abilitare SnapMirror sul cluster Element prima di poter creare una relazione di replica. È possibile eseguire questa attività solo nell'interfaccia utente Web del software Element o utilizzando link:../api/reference_element_api_enablefeature.html["Metodo API"].

.Prima di iniziare
* Il cluster Element deve eseguire il software NetApp Element versione 10.1 o successiva.
* SnapMirror può essere abilitato solo per i cluster Element utilizzati con volumi NetApp ONTAP .


.Informazioni su questo compito
Il sistema Element è dotato di SnapMirror disabilitato per impostazione predefinita.  SnapMirror non viene abilitato automaticamente come parte di una nuova installazione o di un aggiornamento.

[NOTE]
====
Una volta abilitato, SnapMirror non può essere disabilitato.  È possibile disattivare la funzionalità SnapMirror e ripristinare le impostazioni predefinite solo restituendo il cluster all'immagine di fabbrica.

====
.Passi
. Fare clic su *Cluster* > *Impostazioni*.
. Trova le impostazioni specifiche del cluster per SnapMirror.
. Fare clic su *Abilita SnapMirror*.

