---
permalink: storage/task_data_manage_vol_access_group_create_a_volume_access_group.html 
sidebar: sidebar 
keywords: volume access group, create, initiators 
summary: 'È possibile creare gruppi di accesso al volume mappando gli iniziatori a una raccolta di volumi per un accesso protetto.  È quindi possibile concedere l"accesso ai volumi nel gruppo con un segreto di avvio CHAP dell"account e un segreto di destinazione.' 
---
= Creare un gruppo di accesso al volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare gruppi di accesso al volume mappando gli iniziatori a una raccolta di volumi per un accesso protetto.  È quindi possibile concedere l'accesso ai volumi nel gruppo con un segreto di avvio CHAP dell'account e un segreto di destinazione.

Se si utilizza CHAP basato sull'iniziatore, è possibile aggiungere credenziali CHAP per un singolo iniziatore in un gruppo di accesso al volume, garantendo maggiore sicurezza.  Ciò consente di applicare questa opzione ai gruppi di accesso al volume già esistenti.

.Passi
. Fare clic su *Gestione* > *Gruppi di accesso*.
. Fare clic su *Crea gruppo di accesso*.
. Immettere un nome per il gruppo di accesso al volume nel campo *Nome*.
. Aggiungere un iniziatore al gruppo di accesso al volume in uno dei seguenti modi:
+
[cols="25,75"]
|===
| Opzione | Descrizione 


 a| 
Aggiunta di un iniziatore Fibre Channel
 a| 
.. In Aggiungi iniziatori, seleziona un iniziatore Fibre Channel esistente dall'elenco Iniziatori Fibre Channel non associati.
.. Fare clic su *Aggiungi iniziatore FC*.
+

NOTE: È possibile creare un iniziatore durante questo passaggio facendo clic sul collegamento *Crea iniziatore*, inserendo un nome per l'iniziatore e facendo clic su *Crea*.  Dopo averlo creato, il sistema aggiunge automaticamente l'iniziatore all'elenco Iniziatori.



Un esempio del formato è il seguente:

[listing]
----
5f:47:ac:c0:5c:74:d4:02
----


 a| 
Aggiunta di un iniziatore iSCSI
 a| 
In Aggiungi iniziatori, seleziona un iniziatore esistente dall'elenco Iniziatori.  *Nota:* puoi creare un iniziatore durante questo passaggio cliccando sul link *Crea iniziatore*, immettendo un nome per l'iniziatore e cliccando su *Crea*.  Dopo averlo creato, il sistema aggiunge automaticamente l'iniziatore all'elenco Iniziatori.

Un esempio del formato è il seguente:

[listing]
----
iqn.2010-01.com.solidfire:c2r9.fc0.2100000e1e09bb8b
----

TIP: È possibile trovare l'IQN dell'iniziatore per ciascun volume selezionando *Visualizza dettagli* nel menu Azioni per il volume nell'elenco *Gestione* > *Volumi* > *Attivi*.

Quando si modifica un iniziatore, è possibile impostare l'attributo requiredCHAP su True, consentendo di impostare il segreto dell'iniziatore di destinazione.  Per maggiori dettagli, vedere le informazioni API sul metodo API ModifyInitiator.

link:../api/concept_element_api_about_the_api.html["Gestisci l'archiviazione con l'API Element"]

|===
. *Facoltativo:* aggiungere altri iniziatori secondo necessità.
. In Aggiungi volumi, seleziona un volume dall'elenco *Volumi*.
+
Il volume viene visualizzato nell'elenco *Volumi allegati*.

. *Facoltativo:* aggiungere altri volumi secondo necessità.
. Fare clic su *Crea gruppo di accesso*.




== Trova maggiori informazioni

xref:task_data_manage_vol_access_group_add_volumes.adoc[Aggiungere volumi a un gruppo di accesso]
