---
permalink: storage/task_system_manage_virtual_edit_a_virtual_network.html 
sidebar: sidebar 
keywords: virtual network, edit, ip address block, vlan attributes 
summary: 'È possibile modificare gli attributi VLAN, come il nome VLAN, la netmask e la dimensione dei blocchi di indirizzi IP.  Il tag VLAN e SVIP non possono essere modificati per una VLAN.  L"attributo gateway non è un parametro valido per le VLAN non VRF.' 
---
= Modifica una rete virtuale
:allow-uri-read: 
:url-peak: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/How_to_determine_which_VLAN_IP%27s_are_in_use_and_which_nodes_those_IP%27s_are_assigned_to_in_Element
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare gli attributi VLAN, come il nome VLAN, la netmask e la dimensione dei blocchi di indirizzi IP.  Il tag VLAN e SVIP non possono essere modificati per una VLAN.  L'attributo gateway non è un parametro valido per le VLAN non VRF.

Se sono presenti sessioni iSCSI, di replica remota o di altra rete, la modifica potrebbe non riuscire.

Quando si gestisce la dimensione degli intervalli di indirizzi IP VLAN, è necessario tenere presenti le seguenti limitazioni:

* È possibile rimuovere gli indirizzi IP solo dall'intervallo di indirizzi IP iniziale assegnato al momento della creazione della VLAN.
* È possibile rimuovere un blocco di indirizzi IP aggiunto dopo l'intervallo di indirizzi IP iniziale, ma non è possibile ridimensionare un blocco IP rimuovendo gli indirizzi IP.
* Quando si tenta di rimuovere indirizzi IP, dall'intervallo di indirizzi IP iniziale o da un blocco IP, utilizzati dai nodi del cluster, l'operazione potrebbe non riuscire.
* Non è possibile riassegnare specifici indirizzi IP in uso ad altri nodi del cluster.


È possibile aggiungere un blocco di indirizzi IP utilizzando la seguente procedura:

. Selezionare *Cluster* > *Rete*.
. Selezionare l'icona Azioni per la VLAN che si desidera modificare.
. Selezionare *Modifica*.
. Nella finestra di dialogo *Modifica VLAN*, immettere i nuovi attributi per la VLAN.
. Selezionare *Aggiungi un blocco* per aggiungere un blocco non continuo di indirizzi IP per la rete virtuale.
. Selezionare *Salva modifiche*.


.Collegamento agli articoli della Knowledge Base sulla risoluzione dei problemi
Collegamento agli articoli della Knowledge Base per assistenza nella risoluzione dei problemi relativi alla gestione degli intervalli di indirizzi IP della VLAN.

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Duplicate_IP_warning_after_adding_a_storage_node_in_VLAN_on_Element_cluster["Avviso di IP duplicato dopo l'aggiunta di un nodo di archiviazione nella VLAN sul cluster Element"^]
* https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/How_to_determine_which_VLAN_IP%27s_are_in_use_and_which_nodes_those_IP%27s_are_assigned_to_in_Element["Come determinare quali IP VLAN sono in uso e a quali nodi sono assegnati tali IP in Element"^]

