---
permalink: storage/task_data_protection_restore_volume_from_backup_on_amazon_s3.html 
sidebar: sidebar 
keywords: volume restore, amazon s3 object store 
summary: È possibile ripristinare un volume da un backup su un archivio oggetti Amazon S3. 
---
= Ripristina un volume dal backup su un archivio oggetti Amazon S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ripristinare un volume da un backup su un archivio oggetti Amazon S3.

. Fare clic su *Segnalazione* > *Registro eventi*.
. Individua l'evento di backup che ha creato il backup che devi ripristinare.
. Nella colonna *Dettagli* dell'evento, fare clic su *Mostra dettagli*.
. Copia le informazioni del manifesto negli appunti.
. Fare clic su *Gestione* > *Volumi*.
. Fare clic sull'icona Azioni per il volume che si desidera ripristinare.
. Nel menu visualizzato, fare clic su *Ripristina da*.
. Nella finestra di dialogo *Ripristino integrato*, in *Ripristina da*, selezionare *S3*.
. Selezionare l'opzione corrispondente al backup in *Formato dati*:
+
** *Nativo*: formato compresso leggibile solo dai sistemi di archiviazione SolidFire .
** *Non compresso*: formato non compresso compatibile con altri sistemi.


. Immettere un nome host da utilizzare per accedere all'archivio oggetti nel campo *Nome host*.
. Immettere un ID chiave di accesso per l'account nel campo *ID chiave di accesso*.
. Inserisci la chiave di accesso segreta per l'account nel campo *Chiave di accesso segreta*.
. Immettere il bucket S3 in cui archiviare il backup nel campo *Bucket S3*.
. Incolla le informazioni del manifesto nel campo *Manifesto*.
. Fare clic su *Avvia scrittura*.

