---
permalink: storage/task_data_protection_restore_volume_from_backup_on_openstack_swift.html 
sidebar: sidebar 
keywords: volume restore, openstack swift object store 
summary: È possibile ripristinare un volume da un backup su un archivio oggetti OpenStack Swift. 
---
= Ripristina un volume dal backup su un archivio oggetti OpenStack Swift
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ripristinare un volume da un backup su un archivio oggetti OpenStack Swift.

. Fare clic su *Segnalazione* > *Registro eventi*.
. Individua l'evento di backup che ha creato il backup che devi ripristinare.
. Nella colonna *Dettagli* dell'evento, fare clic su *Mostra dettagli*.
. Copia le informazioni del manifesto negli appunti.
. Fare clic su *Gestione* > *Volumi*.
. Fare clic sull'icona Azioni per il volume che si desidera ripristinare.
. Nel menu visualizzato, fare clic su *Ripristina da*.
. Nella finestra di dialogo *Ripristino integrato*, in *Ripristina da*, selezionare *Swift*.
. Selezionare l'opzione corrispondente al backup in *Formato dati*:
+
** *Nativo*: formato compresso leggibile solo dai sistemi di archiviazione SolidFire .
** *Non compresso*: formato non compresso compatibile con altri sistemi.


. Immettere un URL da utilizzare per accedere all'archivio oggetti nel campo *URL*.
. Inserisci un nome utente per l'account nel campo *Nome utente*.
. Inserisci la chiave di autenticazione per l'account nel campo *Chiave di autenticazione*.
. Immettere il nome del contenitore in cui è archiviato il backup nel campo *Contenitore*.
. Incolla le informazioni del manifesto nel campo *Manifesto*.
. Fare clic su *Avvia scrittura*.

