---
permalink: storage/task_snapmirror_transfer_or_one_time_migration_from_ontap_to_element.html 
sidebar: sidebar 
keywords: element, ui, transfer, perform, source, volume, snapmirror, dr, disaster, recovery, one-time, migration 
summary: 'In genere, quando si utilizza SnapMirror per il disaster recovery da un cluster di storage SolidFire che esegue il software NetApp Element al software ONTAP , Element è l"origine e ONTAP la destinazione.  Tuttavia, in alcuni casi il sistema di archiviazione ONTAP può fungere da origine e Element da destinazione.' 
---
= Eseguire un trasferimento o una migrazione una tantum da ONTAP a Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In genere, quando si utilizza SnapMirror per il disaster recovery da un cluster di storage SolidFire che esegue il software NetApp Element al software ONTAP , Element è l'origine e ONTAP la destinazione.  Tuttavia, in alcuni casi il sistema di archiviazione ONTAP può fungere da origine e Element da destinazione.

* Esistono due scenari:
+
** Non esiste alcuna relazione precedente di disaster recovery.  Seguire tutti i passaggi di questa procedura.
** Esiste una precedente relazione di disaster recovery, ma non tra i volumi utilizzati per questa mitigazione.  In questo caso, seguire solo i passaggi 3 e 4 riportati di seguito.




.Cosa ti servirà
* Il nodo di destinazione dell'elemento deve essere reso accessibile a ONTAP.
* Il volume Element deve essere stato abilitato per la replica SnapMirror .


È necessario specificare il percorso di destinazione dell'elemento nel formato hostip:/lun/<id_number>, dove lun è la stringa effettiva "`lun`" e id_number è l'ID del volume dell'elemento.

.Passi
. Utilizzando ONTAP, creare la relazione con il cluster Element:
+
[listing]
----
snapmirror create -source-path SVM:volume|cluster://SVM/volume
-destination-path hostip:/lun/name -type XDP -schedule schedule -policy
    policy
----
+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst
-destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
. Verificare che la relazione SnapMirror sia stata creata utilizzando il comando ONTAP snapmirror show.
+
Per informazioni sulla creazione di una relazione di replica, consultare la documentazione ONTAP e per la sintassi completa dei comandi, consultare la pagina man ONTAP .

. Utilizzando il `ElementCreateVolume` API, crea il volume di destinazione e imposta la modalità di accesso al volume di destinazione su SnapMirror:
+
Crea un volume Element utilizzando l'API Element

+
[listing]
----
{
   "method": "CreateVolume",
   "params": {
        "name": "SMTargetVolumeTest2",
        "accountID": 1,
        "totalSize": 100000000000,
        "enable512e": true,
        "attributes": {},
        "qosPolicyID": 1,
        "enableSnapMirrorReplication": true,
        "access": "snapMirrorTarget"
    },
    "id": 1
}
----
. Inizializzare la relazione di replicazione utilizzando ONTAP `snapmirror initialize` comando:
+
[listing]
----
snapmirror initialize -source-path hostip:/lun/name
-destination-path SVM:volume|cluster://SVM/volume
----

