---
permalink: storage/task_data_protection_clone_a_volume_from_a_snapshot.html 
sidebar: sidebar 
keywords: clone volume from snapshot, volume snapshots, clone 
summary: È possibile creare un nuovo volume da uno snapshot di un volume.  Quando si esegue questa operazione, il sistema utilizza le informazioni dello snapshot per clonare un nuovo volume utilizzando i dati contenuti nel volume al momento della creazione dello snapshot.  Questo processo memorizza le informazioni su altri snapshot del volume nel volume appena creato. 
---
= Clonare un volume da uno snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile creare un nuovo volume da uno snapshot di un volume.  Quando si esegue questa operazione, il sistema utilizza le informazioni dello snapshot per clonare un nuovo volume utilizzando i dati contenuti nel volume al momento della creazione dello snapshot.  Questo processo memorizza le informazioni su altri snapshot del volume nel volume appena creato.

. Fare clic su *Protezione dati* > *Snapshot*.
. Fare clic sull'icona *Azioni* per lo snapshot che si desidera utilizzare per il clone del volume.
. Nel menu visualizzato, fare clic su *Clona volume da snapshot*.
. Immettere un *Nome volume* nella finestra di dialogo *Clona volume da snapshot*.
. Selezionare una *Dimensione totale* e le unità di misura per il nuovo volume.
. Selezionare un tipo di *Accesso* per il volume.
. Selezionare un *Account* dall'elenco da associare al nuovo volume.
. Fare clic su *Avvia clonazione*.

