---
permalink: storage/task_post_deploy_credential_change_ipmi_password.html 
sidebar: sidebar 
keywords: ipmi, password, intelligent platform management interface, netapp, element, h410s, h610s 
summary: 'È possibile modificare la password predefinita dell"amministratore dell"Intelligent Platform Management Interface (IPMI) non appena si ottiene l"accesso IPMI remoto al nodo.  Potrebbe essere opportuno farlo se ci sono aggiornamenti di installazione.' 
---
= Cambia la password IPMI predefinita per i nodi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile modificare la password predefinita dell'amministratore dell'Intelligent Platform Management Interface (IPMI) non appena si ottiene l'accesso IPMI remoto al nodo.  Potrebbe essere opportuno farlo se ci sono aggiornamenti di installazione.

Per i dettagli sulla configurazione dell'accesso IPM per i nodi, vederelink:https://docs.netapp.com/us-en/hci/docs/hci_prereqs_final_prep.html["Configurare IPMI per ogni nodo"^] .

È possibile modificare la password IPM per questi nodi:

* Nodi H410S
* Nodi H610S




== Modificare la password IPMI predefinita per i nodi H410S

È necessario modificare la password predefinita per l'account amministratore IPMI su ciascun nodo di archiviazione non appena si configura la porta di rete IPMI.

.Cosa ti servirà
Dovresti aver configurato l'indirizzo IP IPMI per ciascun nodo di archiviazione.

.Passi
. Aprire un browser Web su un computer in grado di raggiungere la rete IPMI e andare all'indirizzo IP IPMI del nodo.
. Inserisci il nome utente `ADMIN` e password `ADMIN` nel prompt di accesso.
. Dopo aver effettuato l'accesso, fare clic sulla scheda *Configurazione*.
. Fare clic su *Utenti*.
. Seleziona il `ADMIN` utente e fare clic su *Modifica utente*.
. Selezionare la casella di controllo *Cambia password*.
. Inserisci una nuova password nei campi *Password* e *Conferma password*.
. Fare clic su *Modifica*, quindi su *OK*.
. Ripetere questa procedura per tutti gli altri nodi H410S con password IPMI predefinite.




== Modificare la password IPMI predefinita per i nodi H610S

È necessario modificare la password predefinita per l'account amministratore IPMI su ciascun nodo di archiviazione non appena si configura la porta di rete IPMI.

.Cosa ti servirà
Dovresti aver configurato l'indirizzo IP IPMI per ciascun nodo di archiviazione.

.Passi
. Aprire un browser Web su un computer in grado di raggiungere la rete IPMI e andare all'indirizzo IP IPMI del nodo.
. Inserisci il nome utente `root` e password `calvin` nel prompt di accesso.
. Dopo aver effettuato l'accesso, clicca sull'icona di navigazione del menu in alto a sinistra della pagina per aprire il cassetto della barra laterale.
. Fare clic su *Impostazioni*.
. Fare clic su *Gestione utenti*.
. Selezionare l'utente *Amministratore* dall'elenco.
. Abilitare la casella di controllo *Cambia password*.
. Inserisci una nuova password complessa nei campi *Password* e *Conferma password*.
. Fare clic su *Salva* in fondo alla pagina.
. Ripetere questa procedura per tutti gli altri nodi H610S con password IPMI predefinite.




== Trova maggiori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]

