---
permalink: storage/task_data_manage_vol_access_group_add_multiple_initiators.html 
sidebar: sidebar 
keywords: initiator, add to volume access group, access groups, add multiple initiators, create initiator 
summary: 'È possibile aggiungere più iniziatori a un gruppo di accesso al volume esistente per consentire l"accesso ai volumi nel gruppo di accesso al volume con o senza la necessità dell"autenticazione CHAP.' 
---
= Aggiungere più iniziatori a un gruppo di accesso al volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile aggiungere più iniziatori a un gruppo di accesso al volume esistente per consentire l'accesso ai volumi nel gruppo di accesso al volume con o senza la necessità dell'autenticazione CHAP.

Quando si aggiungono iniziatori a un gruppo di accesso al volume, gli iniziatori hanno accesso a tutti i volumi in quel gruppo di accesso al volume.


TIP: È possibile trovare l'iniziatore per ciascun volume facendo clic sull'icona Azioni e quindi su *Visualizza dettagli* per il volume nell'elenco dei volumi attivi.

È possibile aggiungere più iniziatori a un gruppo di accesso al volume esistente per abilitare l'accesso ai volumi e assegnare credenziali CHAP univoche per ciascun iniziatore all'interno di tale gruppo di accesso al volume.  Ciò consente di applicare questa opzione ai gruppi di accesso al volume già esistenti.

È possibile assegnare attributi CHAP basati sull'iniziatore utilizzando una chiamata API.  Per aggiungere un nome account CHAP e credenziali per ogni iniziatore, è necessario utilizzare la chiamata API ModifyInitiator per rimuovere e aggiungere l'accesso e gli attributi CHAP.

Per i dettagli, vederelink:../api/concept_element_api_about_the_api.html["Gestisci l'archiviazione con l'API Element"] .

.Passi
. Fare clic su *Gestione* > *Iniziatori*.
. Seleziona gli iniziatori che desideri aggiungere a un gruppo di accesso.
. Fare clic sul pulsante *Azioni in blocco*.
. Fare clic su *Aggiungi al gruppo di accesso al volume*.
. Nella finestra di dialogo Aggiungi al gruppo di accesso al volume, selezionare un gruppo di accesso dall'elenco *Gruppo di accesso al volume*.
. Fare clic su *Aggiungi*.

