---
permalink: storage/task_data_manage_vol_access_group_remove_volumes.html 
sidebar: sidebar 
keywords: access group, remove volumes from, initiators, chap 
summary: Quando si rimuove un volume da un gruppo di accesso, il gruppo non ha più accesso a quel volume. 
---
= Rimuovere volumi da un gruppo di accesso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Quando si rimuove un volume da un gruppo di accesso, il gruppo non ha più accesso a quel volume.

La modifica delle impostazioni CHAP in un account o la rimozione di iniziatori o volumi da un gruppo di accesso può causare la perdita imprevista dell'accesso degli iniziatori ai volumi.  Per verificare che l'accesso al volume non venga perso inaspettatamente, disconnettersi sempre dalle sessioni iSCSI che saranno interessate da una modifica dell'account o del gruppo di accesso e verificare che gli iniziatori possano riconnettersi ai volumi dopo aver completato eventuali modifiche alle impostazioni dell'iniziatore e del cluster.

. Fare clic su *Gestione* > *Gruppi di accesso*.
. Fare clic sull'icona Azioni per il gruppo di accesso da cui si desidera rimuovere i volumi.
. Fare clic su *Modifica*.
. In Aggiungi volumi nella finestra di dialogo *Modifica gruppo di accesso al volume*, fare clic sulla freccia nell'elenco *Volumi collegati*.
. Selezionare il volume che si desidera rimuovere dall'elenco e fare clic sull'icona *x* per rimuovere il volume dall'elenco.
+
È possibile rimuovere altri volumi ripetendo questo passaggio.

. Fare clic su *Salva modifiche*.

