---
permalink: storage/task-element-replication-resynchronize-data-protection-relationship.html 
sidebar: sidebar 
keywords: ontap, cli, update, replication, relationship, manually 
summary: Potrebbe essere necessario aggiornare manualmente una relazione di replica se un aggiornamento non riesce a causa di un errore di rete. 
---
= Risincronizzare una relazione di replicazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario risincronizzare una relazione di replica dopo aver reso scrivibile un volume di destinazione, dopo che un aggiornamento non riesce perché non esiste una copia Snapshot comune sui volumi di origine e di destinazione oppure se si desidera modificare i criteri di replica per la relazione.

.Informazioni su questo compito
Sebbene la risincronizzazione non richieda un trasferimento della linea di base, può richiedere molto tempo.  Potresti voler eseguire la risincronizzazione nelle ore non di punta.

È necessario specificare il percorso sorgente dell'elemento nel modulo `<hostip:>/lun/<name>` , dove "`lun`" è la stringa effettiva "`lun`" e `name` è il nome del volume Element.

.Fare un passo
. Risincronizzare i volumi di origine e di destinazione:
+
`snapmirror resync -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume> -type XDP -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente risincronizza la relazione tra il volume di origine `0005` all'indirizzo IP 10.0.0.11 e al volume di destinazione `volA_dst` SU `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror resync -source-path 10.0.0.11:/lun/0005 -policy MirrorLatest -destination-path svm_backup:volA_dst
----

