---
permalink: storage/task_data_manage_vvol_enable_virtual_volumes.html 
sidebar: sidebar 
keywords: virtual volumes, enable, functionality on the cluster, vvols 
summary: 'È necessario abilitare manualmente la funzionalità vSphere Virtual Volumes \(VVols\) tramite il software NetApp Element .  Il sistema software Element è dotato di funzionalità VVols disabilitata per impostazione predefinita e non viene abilitata automaticamente come parte di una nuova installazione o di un aggiornamento.  L"abilitazione della funzionalità VVols è un"attività di configurazione che deve essere eseguita una sola volta.' 
---
= Abilita volumi virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario abilitare manualmente la funzionalità vSphere Virtual Volumes (VVols) tramite il software NetApp Element .  Il sistema software Element è dotato di funzionalità VVols disabilitata per impostazione predefinita e non viene abilitata automaticamente come parte di una nuova installazione o di un aggiornamento.  L'abilitazione della funzionalità VVols è un'attività di configurazione che deve essere eseguita una sola volta.

.Cosa ti servirà
* Il cluster deve eseguire Element 9.0 o versione successiva.
* Il cluster deve essere connesso a un ambiente ESXi 6.0 o successivo compatibile con VVols.
* Se si utilizza Element 11.3 o versione successiva, il cluster deve essere connesso a un ambiente ESXi 6.0 aggiornamento 3 o versione successiva.



IMPORTANT: L'abilitazione della funzionalità vSphere Virtual Volumes modifica in modo permanente la configurazione del software Element.  È opportuno abilitare la funzionalità VVols solo se il cluster è connesso a un ambiente compatibile con VMware ESXi VVols.  È possibile disattivare la funzionalità VVols e ripristinare le impostazioni predefinite solo restituendo il cluster all'immagine di fabbrica, eliminando così tutti i dati presenti sul sistema.

.Passi
. Selezionare *Cluster* > *Impostazioni*.
. Trova le impostazioni specifiche del cluster per i volumi virtuali.
. Fare clic su *Abilita volumi virtuali*.
. Fare clic su *Sì* per confermare la modifica alla configurazione dei volumi virtuali.
+
La scheda *VVols* viene visualizzata nell'interfaccia utente di Element.

+

NOTE: Quando la funzionalità VVols è abilitata, il cluster SolidFire avvia il provider VASA, apre la porta 8444 per il traffico VASA e crea endpoint di protocollo che possono essere rilevati da vCenter e da tutti gli host ESXi.

. Copiare l'URL del provider VASA dalle impostazioni dei volumi virtuali (VVol) in *Cluster* > *Impostazioni*.  Utilizzerai questo URL per registrare il provider VASA in vCenter.
. Creare un contenitore di archiviazione in *VVols* > *Contenitori di archiviazione*.
+

NOTE: È necessario creare almeno un contenitore di archiviazione affinché le VM possano essere fornite a un datastore VVol.

. Selezionare *VVols* > *Endpoint protocollo*.
. Verificare che sia stato creato un endpoint del protocollo per ciascun nodo del cluster.
+

NOTE: In vSphere sono necessarie ulteriori attività di configurazione.  Consultare la _Guida alla configurazione di VMware vSphere Virtual Volumes for SolidFire Storage_ per registrare il provider VASA in vCenter, creare e gestire datastore VVol e gestire l'archiviazione in base ai criteri.





== Trova maggiori informazioni

https://www.netapp.com/pdf.html?item=/media/10516-tr4642pdf.pdf["Guida alla configurazione di VMware vSphere Virtual Volumes per SolidFire Storage"^]
