---
permalink: storage/task_data_protection_clone_multiple_volumes_from_a_group_snapshot.html 
sidebar: sidebar 
keywords: multiple volumes, group snapshot, clone, create, data protection 
summary: È possibile clonare un gruppo di volumi da uno snapshot di gruppo in un dato momento.  Questa operazione richiede che esista già uno snapshot di gruppo dei volumi, poiché lo snapshot di gruppo viene utilizzato come base per creare i volumi.  Dopo aver creato i volumi, è possibile utilizzarli come qualsiasi altro volume nel sistema. 
---
= Clonazione di più volumi da uno snapshot di gruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile clonare un gruppo di volumi da uno snapshot di gruppo in un dato momento.  Questa operazione richiede che esista già uno snapshot di gruppo dei volumi, poiché lo snapshot di gruppo viene utilizzato come base per creare i volumi.  Dopo aver creato i volumi, è possibile utilizzarli come qualsiasi altro volume nel sistema.

Le dimensioni del volume e il carico attuale del cluster influiscono sul tempo necessario per completare un'operazione di clonazione.

. Fare clic su *Protezione dati* > *Snapshot di gruppo*.
. Fare clic sull'icona Azioni per lo snapshot di gruppo che si desidera utilizzare per i cloni del volume.
. Nel menu visualizzato, selezionare *Clona volumi da snapshot di gruppo*.
. Immettere un *Nuovo prefisso nome volume* nella finestra di dialogo *Clona volumi da snapshot di gruppo*.
+
Il prefisso viene applicato a tutti i volumi creati dallo snapshot del gruppo.

. *Facoltativo:* seleziona un account diverso a cui apparterrà il clone.
+
Se non si seleziona un account, il sistema assegna i nuovi volumi all'account del volume corrente.

. *Facoltativo:* selezionare un metodo di accesso diverso per i volumi nel clone.
+
Se non si seleziona un metodo di accesso, il sistema utilizza l'accesso al volume corrente.

. Fare clic su *Avvia clonazione*.

