---
permalink: storage/task_data_protection_delete_a_snapshot.html 
sidebar: sidebar 
keywords: snapshot, delete, volume snapshot, storage cluster, remove snapshot 
summary: È possibile eliminare uno snapshot del volume da un cluster di archiviazione che esegue il software Element.  Quando si elimina uno snapshot, il sistema lo rimuove immediatamente. 
---
= Elimina uno snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile eliminare uno snapshot del volume da un cluster di archiviazione che esegue il software Element.  Quando si elimina uno snapshot, il sistema lo rimuove immediatamente.

È possibile eliminare gli snapshot replicati dal cluster di origine.  Se uno snapshot è in fase di sincronizzazione con il cluster di destinazione quando lo elimini, la replica di sincronizzazione viene completata e lo snapshot viene eliminato dal cluster di origine.  Lo snapshot non viene eliminato dal cluster di destinazione.

È anche possibile eliminare gli snapshot replicati sulla destinazione dal cluster di destinazione.  Lo snapshot eliminato viene conservato in un elenco di snapshot eliminati sulla destinazione finché il sistema non rileva che lo snapshot è stato eliminato sul cluster di origine.  Quando la destinazione rileva che hai eliminato lo snapshot di origine, interrompe la replica dello snapshot.

Quando si elimina uno snapshot dal cluster di origine, lo snapshot del cluster di destinazione non viene influenzato (vale anche il contrario).

. Fare clic su *Protezione dati* > *Snapshot*.
. Fare clic sull'icona *Azioni* relativa allo snapshot che si desidera eliminare.
. Nel menu che appare, seleziona *Elimina*.
. Conferma l'azione.

