---
permalink: storage/task_system_manage_cluster_ntp_configure_to_listen_for_ntp_broadcasts.html 
sidebar: sidebar 
keywords: ntp, broadcasts, server, config, server list, broadcast client 
summary: 'Utilizzando la modalità broadcast, è possibile istruire ciascun nodo in un cluster ad ascoltare sulla rete i messaggi broadcast Network Time Protocol \(NTP\) da un server specifico.' 
---
= Configurare il cluster per ascoltare le trasmissioni NTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Utilizzando la modalità broadcast, è possibile istruire ciascun nodo di un cluster ad ascoltare sulla rete i messaggi broadcast NTP (Network Time Protocol) provenienti da un server specifico.

L'NTP viene utilizzato per sincronizzare gli orologi su una rete.  La connessione a un server NTP interno o esterno dovrebbe essere parte della configurazione iniziale del cluster.

.Cosa ti servirà
* Per configurare questa impostazione è necessario disporre dei privilegi di amministratore del cluster.
* È necessario configurare un server NTP sulla rete come server broadcast.


.Passi
. Fare clic su *Cluster* > *Impostazioni*.
. Inserire nell'elenco dei server il server o i server NTP che utilizzano la modalità broadcast.
. In Impostazioni Network Time Protocol, seleziona *Sì* per utilizzare un client broadcast.
. Per impostare il client broadcast, nel campo *Server*, immettere il server NTP configurato in modalità broadcast.
. Fare clic su *Salva modifiche*.




== Trova maggiori informazioni

* link:../storage/task_system_manage_cluster_ntp_configure.html["Configurare i server Network Time Protocol affinché il cluster esegua le query"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]

