---
permalink: storage/task-element-replication-reactivate-original-source-volume.html 
sidebar: sidebar 
keywords: ontap,cli, reactivate, original, source, volume 
summary: È possibile ristabilire la relazione di protezione dei dati originale tra i volumi di origine e di destinazione quando non è più necessario fornire dati dalla destinazione. 
---
= Riattivare il volume sorgente originale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile ristabilire la relazione di protezione dei dati originale tra i volumi di origine e di destinazione quando non è più necessario fornire dati dalla destinazione.

.Informazioni su questo compito
La procedura seguente presuppone che la linea di base nel volume sorgente originale sia intatta.  Se la linea di base non è intatta, è necessario creare e inizializzare la relazione tra il volume da cui si stanno fornendo i dati e il volume di origine originale prima di eseguire la procedura.

È necessario specificare il percorso sorgente dell'elemento nel modulo `<hostip:>/lun/<name>` , dove "`lun`" è la stringa effettiva "`lun`" e `name` è il nome del volume Element.

A partire da ONTAP 9.4, le copie snapshot di una LUN create durante la distribuzione dei dati dalla destinazione ONTAP vengono replicate automaticamente quando l'origine dell'elemento viene riattivata.

Le regole di replicazione sono le seguenti:

* Sono supportati solo i LUN iSCSI.
* Non è possibile replicare più di una LUN da un volume ONTAP a un volume Element.
* Non è possibile replicare una LUN da un volume ONTAP a più volumi Element.


.Passi
. Elimina la relazione di protezione dei dati originale:
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente elimina la relazione tra il volume sorgente originale, `0005` all'indirizzo IP 10.0.0.11 e il volume da cui vengono forniti i dati, `volA_dst` SU `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror delete -source-path 10.0.0.11:/lun/0005 -policy MirrorLatest -destination-path svm_backup:volA_dst
----
. Invertire la relazione originale di protezione dei dati:
+
`snapmirror resync -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
Sebbene la risincronizzazione non richieda un trasferimento della linea di base, può richiedere molto tempo.  Potresti voler eseguire la risincronizzazione nelle ore non di punta.

+
L'esempio seguente inverte la relazione tra il volume sorgente originale, `0005` all'indirizzo IP 10.0.0.11 e il volume da cui vengono forniti i dati, `volA_dst` SU `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Aggiorna la relazione invertita:
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
[NOTE]
====
Il comando fallisce se non esiste una copia snapshot comune sull'origine e sulla destinazione.  Utilizzo `snapmirror initialize` per reinizializzare la relazione.

====
+
L'esempio seguente aggiorna la relazione tra il volume da cui si stanno fornendo i dati, `volA_dst` SU `svm_backup` e il volume sorgente originale, `0005` all'indirizzo IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Interrompere i trasferimenti programmati per la relazione invertita:
+
`snapmirror quiesce -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente interrompe i trasferimenti pianificati tra il volume da cui si stanno fornendo i dati, `volA_dst` SU `svm_backup` e il volume sorgente originale, `0005` all'indirizzo IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Interrompere i trasferimenti in corso per la relazione invertita:
+
`snapmirror abort -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente interrompe i trasferimenti in corso tra il volume da cui si stanno fornendo i dati, `volA_dst` SU `svm_backup` e il volume sorgente originale, `0005` all'indirizzo IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Interrompi la relazione inversa:
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente interrompe la relazione tra il volume da cui si stanno fornendo i dati, `volA_dst` SU `svm_backup` e il volume sorgente originale, `0005` all'indirizzo IP 10.0.0.11:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005
----
. Eliminare la relazione di protezione dei dati invertita:
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume> -destination-path <hostip:>/lun/<name> -policy <policy>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente elimina la relazione invertita tra il volume sorgente originale, `0005` all'indirizzo IP 10.0.0.11 e il volume da cui vengono forniti i dati, `volA_dst` SU `svm_backup` :

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path 10.0.0.11:/lun/0005 -policy MirrorLatest
----
. Ripristinare il rapporto originale di protezione dei dati:
+
`snapmirror resync -source-path <hostip:>/lun/<name> -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
Per la sintassi completa dei comandi, vedere la pagina man.

+
L'esempio seguente ristabilisce la relazione tra il volume sorgente originale, `0005` all'indirizzo IP 10.0.0.11 e il volume di destinazione originale, `volA_dst` SU `svm_backup` :

+
[listing]
----
cluster_dst::> snapmirror resync -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst
----


.Dopo aver finito
Utilizzare il `snapmirror show` comando per verificare che la relazione SnapMirror sia stata creata.  Per la sintassi completa dei comandi, vedere la pagina man.
