---
permalink: storage/task_intro_view_api_activity_in_real_time.html 
sidebar: sidebar 
keywords: solidfire api, element api, element os, element, viewing the API log, viewing API calls 
summary: 'Il sistema Element utilizza l"API NetApp Element come base per le sue caratteristiche e funzionalità.  L"interfaccia utente Element consente di visualizzare vari tipi di attività API in tempo reale sul sistema mentre si utilizza l"interfaccia.  Grazie al registro API, puoi visualizzare l"attività API di sistema avviata dall"utente e in background, nonché le chiamate API effettuate sulla pagina che stai visualizzando.' 
---
= Visualizza l'attività API
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema Element utilizza l'API NetApp Element come base per le sue caratteristiche e funzionalità.  L'interfaccia utente Element consente di visualizzare vari tipi di attività API in tempo reale sul sistema mentre si utilizza l'interfaccia.  Grazie al registro API, puoi visualizzare l'attività API di sistema avviata dall'utente e in background, nonché le chiamate API effettuate sulla pagina che stai visualizzando.

È possibile utilizzare il registro API per identificare quali metodi API vengono utilizzati per determinate attività e vedere come utilizzare i metodi e gli oggetti API per creare applicazioni personalizzate.

Per informazioni su ciascun metodo, vedere link:../api/concept_element_api_about_the_api.html["Riferimento API di Element Software"].

. Dalla barra di navigazione dell'interfaccia utente dell'elemento, fare clic su *Registro API*.
. Per modificare il tipo di attività API visualizzata nella finestra Registro API, procedere come segue:
+
.. Selezionare *Richieste* per visualizzare il traffico delle richieste API.
.. Selezionare *Risposte* per visualizzare il traffico di risposta API.
.. Filtra i tipi di traffico API selezionando una delle seguenti opzioni:
+
*** *Avviato dall'utente*: traffico API generato dalle tue attività durante questa sessione dell'interfaccia utente web.
*** *Background Polling*: traffico API generato dall'attività del sistema in background.
*** *Pagina corrente*: traffico API generato dalle attività sulla pagina che stai visualizzando.








== Trova maggiori informazioni

* link:../api/concept_element_api_about_the_api.html["Gestione dello storage con l'API Element"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/us-en/vcp/index.html["Plug-in NetApp Element per vCenter Server"^]

