---
permalink: storage/task_data_protection_using_volume_snapshots.html 
sidebar: sidebar 
keywords: data protection, volume snapshots, roll back volume, replicate snapshots 
summary: Uno snapshot del volume è una copia di un volume effettuata in un dato momento.  È possibile acquisire uno snapshot di un volume e utilizzarlo in un secondo momento se è necessario riportare un volume allo stato in cui si trovava al momento della creazione dello snapshot. 
---
= Utilizzare snapshot del volume per la protezione dei dati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Uno snapshot del volume è una copia di un volume effettuata in un dato momento.  È possibile acquisire uno snapshot di un volume e utilizzarlo in un secondo momento se è necessario riportare un volume allo stato in cui si trovava al momento della creazione dello snapshot.

Gli snapshot sono simili ai cloni di volume.  Tuttavia, gli snapshot sono semplicemente repliche dei metadati del volume, quindi non è possibile montarli o scriverci sopra.  La creazione di uno snapshot del volume richiede inoltre solo una piccola quantità di risorse di sistema e spazio, il che rende la creazione di snapshot più rapida della clonazione.

È possibile acquisire un'istantanea di un singolo volume o di un set di volumi.

Facoltativamente, replicare gli snapshot su un cluster remoto e utilizzarli come copia di backup del volume.  Ciò consente di ripristinare un volume a un punto specifico nel tempo utilizzando lo snapshot replicato.  In alternativa, è possibile creare un clone di un volume da uno snapshot replicato.



== Trova maggiori informazioni

* xref:task_data_protection_use_individual_volume_snapshots.adoc[Utilizzare snapshot di volumi individuali per la protezione dei dati]
* xref:task_data_protection_use_group_snapshots_for_data_protection.adoc[Utilizzo di snapshot di gruppo per attività di protezione dei dati]
* xref:task_data_protection_schedule_a_snapshot_task.adoc[Pianificazione di uno snapshot]

