---
permalink: storage/task_system_manage_virtual_enable_virtual_routing_and_forwarding.html 
sidebar: sidebar 
keywords: virtual routing, forwarding, enable, vrf, storage networks, create a vlan 
summary: 'È possibile abilitare il routing e l"inoltro virtuali \(VRF\), che consentono a più istanze di una tabella di routing di esistere in un router e di funzionare simultaneamente.  Questa funzionalità è disponibile solo per le reti di archiviazione.' 
---
= Abilita il routing e l'inoltro virtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile abilitare il routing e l'inoltro virtuali (VRF), che consente a più istanze di una tabella di routing di esistere in un router e di funzionare simultaneamente.  Questa funzionalità è disponibile solo per le reti di archiviazione.

È possibile abilitare VRF solo al momento della creazione di una VLAN.  Se si desidera tornare a non-VRF, è necessario eliminare e ricreare la VLAN.

. Fare clic su *Cluster* > *Rete*.
. Per abilitare VRF su una nuova VLAN, selezionare *Crea VLAN*.
+
.. Inserire le informazioni rilevanti per il nuovo VRF/VLAN.  Vedere Aggiunta di una rete virtuale.
.. Selezionare la casella di controllo *Abilita VRF*.
.. *Facoltativo*: Inserisci un gateway.


. Fare clic su *Crea VLAN*.




== Trova maggiori informazioni

xref:task_system_manage_virtual_add_a_virtual_network.adoc[Aggiungi una rete virtuale]
