---
permalink: api/reference_element_api_disablefeature.html 
sidebar: sidebar 
keywords: SNMP,disable,disabling,DisableFeature,vvols,virtual volumes 
summary: È possibile utilizzare il metodo DisableFeature per disabilitare VolumeLoadBalanceOnActualIOPS. 
---
= DisabilitaFunzionalità
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `DisableFeature` metodo per disabilitare il `VolumeLoadBalanceOnActualIOPS` caratteristica. `VolumeLoadBalanceOnActualIOPS` è disabilitato per impostazione predefinita.

[NOTE]
====
Se si tenta di disattivare un'altra funzionalità, ad esempio VVols, viene visualizzato il seguente messaggio di errore:

[listing]
----
{"error":{"code":500,"message":"VolumeLoadBalanceOnActualIOPS is the only feature that can be disabled","name":"xAPINotPermitted"},"id":null}
----
====


== Parametro

Questo metodo ha il seguente parametro di input.

[cols="1a,3a,1a,1a,1a"]
|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
caratteristica
 a| 
Disattivare una funzionalità del cluster.  Valore possibile:

* `VolumeLoadBalanceOnActualIOPS`: Disabilita il bilanciamento delle sezioni sugli IOPS effettivi anziché sugli IOPS minimi.

 a| 
corda
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo non ha valori di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "DisableFeature",
    "params": {
        "feature" : "VolumeLoadBalanceOnActualIOPS"
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Nuovo dalla versione

12,8
