---
permalink: api/concept_element_api_ldap_api_methods.html 
sidebar: sidebar 
keywords: ldap,api,methods 
summary: 'È possibile utilizzare il protocollo Lightweight Directory Access Protocol (LDAP) per autenticare l"accesso all"archiviazione Element.  I metodi API LDAP descritti in questa sezione consentono di configurare l"accesso LDAP al cluster di archiviazione.' 
---
= Metodi API LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il protocollo LDAP (Lightweight Directory Access Protocol) per autenticare l'accesso allo storage Element.  I metodi API LDAP descritti in questa sezione consentono di configurare l'accesso LDAP al cluster di archiviazione.

* xref:reference_element_api_addldapclusteradmin.adoc[AggiungiLdapClusterAdmin]
* xref:reference_element_api_enableldapauthentication.adoc[Abilita autenticazione LDAP]
* xref:reference_element_api_disableldapauthentication.adoc[Disabilita l'autenticazione LDAP]
* xref:reference_element_api_getldapconfiguration.adoc[OttieniLdapConfiguration]
* xref:reference_element_api_testldapauthentication.adoc[TestLdapAuthentication]




== Trova maggiori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti NetApp SolidFire ed Element"^]

