---
permalink: api/concept_element_api_administrator_api_methods.html 
sidebar: sidebar 
keywords: API,administration,method,administrator 
summary: 'È possibile utilizzare i metodi API dell"amministratore per creare, modificare, visualizzare e rimuovere gli amministratori del cluster di archiviazione e assegnare livelli di accesso e privilegi a coloro che hanno accesso a un cluster di archiviazione.' 
---
= Metodi API dell'amministratore
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare i metodi API dell'amministratore per creare, modificare, visualizzare e rimuovere gli amministratori del cluster di archiviazione e assegnare livelli di accesso e privilegi a coloro che hanno accesso a un cluster di archiviazione.

* xref:reference_element_api_addclusteradmin.adoc[AggiungiClusterAdmin]
* xref:reference_element_api_getcurrentclusteradmin.adoc[OttieniCurrentClusterAdmin]
* xref:reference_element_api_getloginbanner.adoc[OttieniLoginBanner]
* xref:reference_element_api_listclusteradmins.adoc[ListClusterAdmins]
* xref:reference_element_api_modifyclusteradmin.adoc[ModificaClusterAdmin]
* xref:reference_element_api_removeclusteradmin.adoc[RimuoviClusterAdmin]
* xref:reference_element_api_setloginbanner.adoc[ImpostaLoginBanner]




== Trova maggiori informazioni

* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti NetApp SolidFire ed Element"^]

