---
permalink: api/reference_element_api_deletestoragecontainers.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,delete,deleting,vvol,DeleteStorageContainers 
summary: 'È possibile utilizzare il metodo DeleteStorageContainers per rimuovere contemporaneamente dal sistema fino a 2000 contenitori di archiviazione Virtual Volume \(VVol\).  I contenitori di archiviazione rimossi non devono contenere VVol.' 
---
= Elimina contenitori di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `DeleteStorageContainers` Metodo per rimuovere contemporaneamente dal sistema fino a 2000 contenitori di archiviazione Virtual Volume (VVol).  I contenitori di archiviazione rimossi non devono contenere VVol.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
storageContainerIDs
 a| 
Un elenco di ID dei contenitori di archiviazione da eliminare.  È possibile specificare fino a 2000 ID nell'elenco.
 a| 
matrice UUID
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo non ha valori di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "DeleteStorageContainers",
    "params": {
        "storageContainerIDs" : ["a9ec1138-e386-4a44-90d7-b9acbbc05176"]
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {}
}
----


== Nuovo dalla versione

9,6
