---
permalink: api/reference_element_api_modifygroupsnapshot.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,group,snapshot,modifygroupsnapshot 
summary: 'È possibile utilizzare ModifyGroupSnapshot per modificare gli attributi di un gruppo di snapshot.  È possibile utilizzare questo metodo anche per consentire la replica remota degli snapshot creati sul volume di lettura/scrittura \(sorgente\) su un sistema di archiviazione di destinazione.' 
---
= ModificaSnapshotGruppo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare `ModifyGroupSnapshot` per modificare gli attributi di un gruppo di snapshot.  È possibile utilizzare questo metodo anche per consentire la replica remota degli snapshot creati sul volume di lettura/scrittura (di origine) su un sistema di archiviazione di destinazione.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
enableReplication
 a| 
Utilizzare per abilitare la replica dello snapshot creato su un cluster remoto. Valori possibili:

* `true`: Lo snapshot verrà replicato nell'archivio remoto.
* `false`: Lo snapshot non verrà replicato nell'archivio remoto.

 a| 
booleano
 a| 
falso
 a| 
NO



 a| 
tempo di scadenza
 a| 
Specificare il tempo dopo il quale è possibile rimuovere lo snapshot.  Non può essere utilizzato con ritenzione.  Se non vengono specificati né expirationTime né retention sullo snapshot originale, lo snapshot non scadrà.  Il formato dell'ora è una stringa di data ISO 8601 per la scadenza basata sul tempo, altrimenti non scadrà.  Un valore di `null` fa sì che l'istantanea venga conservata in modo permanente.  Un valore fifo fa sì che lo snapshot venga conservato secondo il principio First-In-First-Out (FIFO), rispetto agli altri snapshot FIFO presenti nel volume.  L'API non funzionerà se non è disponibile spazio FIFO.
 a| 
Stringa di data ISO 8601
 a| 
Nessuno
 a| 
NO



 a| 
nome
 a| 
Il nome dello snapshot del gruppo.  Se non viene immesso alcun nome, vengono utilizzate la data e l'ora in cui è stato acquisito lo snapshot del gruppo.  La lunghezza massima consentita per il nome è di 255 caratteri.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
ID istantanea gruppo
 a| 
L'ID del gruppo di snapshot.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
snapMirrorLabel
 a| 
Etichetta utilizzata dal software SnapMirror per specificare la politica di conservazione degli snapshot su un endpoint SnapMirror .
 a| 
corda
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
groupSnapshot
 a| 
Oggetto contenente informazioni sullo snapshot del gruppo appena modificato.
 a| 
xref:reference_element_api_groupsnapshot.adoc[groupSnapshot]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "id": 695,
  "method": "ModifyGroupSnapshot",
  "params": {
    "groupSnapshotID": 3,
    "enableRemoteReplication": true,
    "expirationTime": "2016-04-08T22:46:25Z"
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 695,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-06T17:31:41Z",
      "groupSnapshotID": 3,
      "groupSnapshotUUID": "8b2e101d-c5ab-4a72-9671-6f239de49171",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-06T17:31:41Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2016-04-08T22:46:25Z",
          "groupID": 3,
          "groupSnapshotUUID": "8b2e101d-c5ab-4a72-9671-6f239de49171",
          "name": "grpsnap1-2",
          "snapshotID": 2,
          "snapshotUUID": "719b162c-e170-4d80-b4c7-1282ed88f4e1",
          "status": "done",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "grpsnap1",
      "status": "done"
    }
  }
}
----


== Nuovo dalla versione

9,6
