---
permalink: api/reference_element_api_getremotelogginghosts.html 
sidebar: sidebar 
keywords: remote,logging,hosts,host,get,getting,getremotelogginghosts 
summary: 'È possibile utilizzare il metodo GetRemoteLoggingHosts per ottenere l"elenco corrente dei server di registro.' 
---
= OttieniHost di registrazione remoti
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetRemoteLoggingHosts` metodo per ottenere l'elenco corrente dei server di registro.



== Parametri

Questo metodo non ha parametri di input.



== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
host remoti
 a| 
Elenco di informazioni su indirizzi IP e porte relative agli host configurati per ricevere informazioni di registrazione inoltrate.
 a| 
xref:reference_element_api_loggingserver.adoc[Server di registrazione]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "id": 3386609,
   "method": "GetRemoteLoggingHosts",
   "params": {}
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 3386609,
   "result": {
      "remoteHosts": [
         {
           "host": "172.16.1.20",
           "port": 10514
         },
         {
           "host": "172.16.1.25"
         }
      ]
   }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_setremotelogginghosts.adoc[Imposta host di registrazione remoti]
