---
permalink: api/reference_element_api_getvolumeefficiency.html 
sidebar: sidebar 
keywords: volume,volumes,get,getting,stats,measurements,efficiency,GetVolumeEfficiency 
summary: È possibile utilizzare il metodo GetVolumeEfficiency per ottenere informazioni su un volume.  Per calcolare la capacità viene utilizzato solo il volume fornito come parametro in questo metodo API. 
---
= OttieniEfficienzaVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetVolumeEfficiency` metodo per ottenere informazioni su un volume.  Per calcolare la capacità viene utilizzato solo il volume fornito come parametro in questo metodo API.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID volume
 a| 
Specifica il volume per cui viene calcolata la capacità.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
compressione
 a| 
Quantità di spazio risparmiata comprimendo i dati su un singolo volume.  Espresso come rapporto, dove 1 indica che i dati sono stati memorizzati senza essere compressi.
 a| 
galleggiante



 a| 
deduplicazione
 a| 
Quantità di spazio risparmiata su un singolo volume evitando di duplicare i dati.  Espresso come rapporto.
 a| 
galleggiante



 a| 
volumi mancanti
 a| 
I volumi che non è stato possibile interrogare per i dati di efficienza.  I volumi mancanti possono essere causati da Garbage Collection (GC) eseguito da meno di un'ora, da una temporanea perdita di rete o da servizi riavviati dopo il ciclo GC.
 a| 
array di interi



 a| 
thinProvisioning
 a| 
Rapporto tra lo spazio utilizzato e la quantità di spazio allocato per l'archiviazione dei dati.  Espresso come rapporto.
 a| 
galleggiante



 a| 
marca temporale
 a| 
L'ultima volta che sono stati raccolti dati sull'efficienza dopo GC.
 a| 
Stringa di dati ISO 8601

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "GetVolumeEfficiency",
   "params": {
      "volumeID": 606
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result": {
       "compression": 2.001591240821456,
       "deduplication": 1,
       "missingVolumes": [],
       "thinProvisioning": 1.009861932938856,
       "timestamp": "2014-03-10T16:06:33Z"
   }
}
----


== Nuovo dalla versione

9,6
