---
permalink: api/reference_element_api_getcompletestats.html 
sidebar: sidebar 
keywords:  
summary: 'L"ingegneria NetApp utilizza il metodo API GetCompleteStats per testare le nuove funzionalità.  I dati restituiti da GetCompleteStats non sono documentati, cambiano frequentemente e non se ne garantisce l"accuratezza.  Non utilizzare GetCompleteStats per raccogliere dati sulle prestazioni o per qualsiasi altra integrazione di gestione con un cluster di archiviazione che esegue il software Element.' 
---
= Ottieni statistiche complete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'ingegneria NetApp utilizza il `GetCompleteStats` Metodo API per testare nuove funzionalità.  I dati restituiti da `GetCompleteStats` non è documentato, cambia frequentemente e non se ne garantisce l'accuratezza.  Non dovresti usare `GetCompleteStats` per la raccolta di dati sulle prestazioni o qualsiasi altra integrazione di gestione con un cluster di storage che esegue il software Element.

Utilizzare i seguenti metodi API supportati per recuperare informazioni statistiche:

* xref:reference_element_api_getvolumestats.adoc[Ottieni statistiche sul volume]
* xref:reference_element_api_getclusterstats.adoc[Ottieni statistiche cluster]
* xref:reference_element_api_getnodestats.adoc[Ottieni statistiche nodo]
* xref:reference_element_api_getdrivestats.adoc[Ottieni statistiche di guida]




== Nuovo dalla versione

9,6
