---
permalink: api/reference_element_api_listinitiators.html 
sidebar: sidebar 
keywords: initiators,initiator,list,listing,listinitiators,iqn,wwpn,iqns,wwpns 
summary: 'È possibile utilizzare il metodo ListInitiators per ottenere l"elenco degli IQN degli iniziatori o dei nomi di porte mondiali \(WWPN\).' 
---
= Iniziatori di elenchi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListInitiators` metodo per ottenere l'elenco degli IQN iniziatori o dei nomi delle porte mondiali (WWPN).



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
iniziatori
 a| 
Un elenco di ID iniziatori da recuperare.  È possibile fornire questo parametro o il parametro startInitiatorID, ma non entrambi.
 a| 
array di interi
 a| 
Nessuno
 a| 
NO



 a| 
IDIniziatore di avvio
 a| 
ID dell'iniziatore da cui iniziare l'elenco.  È possibile fornire questo parametro o il parametro degli iniziatori, ma non entrambi.
 a| 
intero
 a| 
0
 a| 
NO



 a| 
limite
 a| 
Numero massimo di oggetti iniziatori da restituire.
 a| 
intero
 a| 
(illimitato)
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
iniziatori
 a| 
Elenco delle informazioni sull'iniziatore.
 a| 
xref:reference_element_api_initiator.adoc[iniziatore]vettore

|===


== Eccezioni

Questo metodo può avere la seguente eccezione:

|===


| Nome | Descrizione 


 a| 
xParametro non valido
 a| 
Generato se si includono sia i parametri startInitiatorID che initiator nella stessa chiamata al metodo.

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ListInitiators",
   "params": {},
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "initiators": [
      {
        "alias": "",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:c84ffd71216",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== Nuovo dalla versione

9,6
