---
permalink: api/reference_element_api_addkeyservertoproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,assigning to key provider,assign,addkeyservertoproviderkmip 
summary: 'È possibile utilizzare il metodo AddKeyServerToProviderKmip per assegnare un server di chiavi Key Management Interoperability Protocol \(KMIP\) al provider di chiavi specificato.  Durante l"assegnazione, il server viene contattato per verificarne la funzionalità.  Se il server delle chiavi specificato è già assegnato al fornitore delle chiavi specificato, non viene intrapresa alcuna azione e non viene restituito alcun errore.  È possibile rimuovere l"assegnazione utilizzando il metodo RemoveKeyServerFromProviderKmip.' 
---
= AggiungiKeyServerAlProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `AddKeyServerToProviderKmip` metodo per assegnare un server di chiavi KMIP (Key Management Interoperability Protocol) al fornitore di chiavi specificato.  Durante l'assegnazione, il server viene contattato per verificarne la funzionalità.  Se il server delle chiavi specificato è già assegnato al fornitore delle chiavi specificato, non viene intrapresa alcuna azione e non viene restituito alcun errore.  È possibile rimuovere l'assegnazione utilizzando `RemoveKeyServerFromProviderKmip` metodo.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID fornitore di chiavi
 a| 
ID del fornitore delle chiavi a cui assegnare il server delle chiavi.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
ID del server chiave
 a| 
L'ID del server delle chiavi da assegnare.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo non ha valore di ritorno.  L'assegnazione è considerata riuscita finché non viene restituito alcun errore.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "AddKeyServerToProviderKmip",
  "params": {
    "keyProviderID": 1,
    "keyServerID": 15
    },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


== Nuovo dalla versione

11,7
