---
permalink: api/reference_element_api_getkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,retrieving,get,retrieve 
summary: 'È possibile utilizzare il metodo GetKeyProviderKmip per recuperare informazioni sul provider di chiavi Key Management Interoperability Protocol \(KMIP\) specificato.' 
---
= GetKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetKeyProviderKmip` metodo per recuperare informazioni sul fornitore di chiavi KMIP (Key Management Interoperability Protocol) specificato.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID fornitore di chiavi
 a| 
ID dell'oggetto fornitore di chiavi KMIP da restituire.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
kmipKeyProvider
 a| 
Un oggetto contenente dettagli sul fornitore della chiave richiesto.
 a| 
link:reference_element_api_keyproviderkmip.html["Fornitore di chiaviKmip"]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "GetKeyProviderKmip",
  "params": {
    "keyProviderID": 15
    },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result":
    {
    "kmipKeyProvider": {
        "keyProviderID": 15,
        "kmipCapabilities": "SSL",
        "keyProviderIsActive": true,
        "keyServerIDs": [
            1
        ],
        "keyProviderName": "ProviderName"
    }
   }
}
----


== Nuovo dalla versione

11,7
