---
permalink: api/reference_element_api_modifysnapmirrorrelationship.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,relationship,modifysnapmirrorrelationship 
summary: È possibile utilizzare ModifySnapMirrorRelationship per modificare gli intervalli in cui si verifica uno snapshot pianificato.  Utilizzando questo metodo è anche possibile eliminare o mettere in pausa una pianificazione. 
---
= Modificare la relazione SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare `ModifySnapMirrorRelationship` per modificare gli intervalli in cui si verifica uno snapshot pianificato.  Utilizzando questo metodo è anche possibile eliminare o mettere in pausa una pianificazione.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
destinazioneVolume
 a| 
Il volume di destinazione nella relazione SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Nessuno
 a| 
SÌ



 a| 
maxTransferRate
 a| 
Specifica la velocità massima di trasferimento dati tra i volumi in kilobyte al secondo.  Il valore predefinito, 0, è illimitato e consente alla relazione SnapMirror di utilizzare completamente la larghezza di banda di rete disponibile.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
NomePolitica
 a| 
Specifica il nome del criterio ONTAP SnapMirror per la relazione.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
Nome programma
 a| 
Nome della pianificazione cron preesistente sul sistema ONTAP utilizzata per aggiornare la relazione SnapMirror .
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
snapMirrorEndpointID
 a| 
ID endpoint del sistema di archiviazione ONTAP remoto che comunica con il cluster di archiviazione Element.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
snapMirrorRelationship
 a| 
Un oggetto contenente gli attributi di relazione SnapMirror modificati.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Nuovo dalla versione

10,1
