---
permalink: api/reference_element_api_checkpingonvlan.html 
sidebar: sidebar 
keywords: VLAN,pre-deployment,network,validation,validate,validating,check,checking,CheckPingOnVlan 
summary: 'È possibile utilizzare il metodo CheckPingOnVlan per testare la connettività di rete su una VLAN temporanea durante l"esecuzione della convalida di rete pre-distribuzione.  CheckPingOnVlan crea un"interfaccia VLAN temporanea, invia pacchetti ICMP a tutti i nodi nel cluster di archiviazione utilizzando l"interfaccia VLAN e quindi rimuove l"interfaccia.' 
---
= CheckPingOnVlan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `CheckPingOnVlan` Metodo per testare la connettività di rete su una VLAN temporanea durante l'esecuzione della convalida di rete pre-distribuzione. `CheckPingOnVlan` crea un'interfaccia VLAN temporanea, invia pacchetti ICMP a tutti i nodi nel cluster di archiviazione utilizzando l'interfaccia VLAN e quindi rimuove l'interfaccia.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
tentativi
 a| 
Specifica il numero di volte in cui il sistema deve ripetere il ping di prova.
 a| 
intero
 a| 
5
 a| 
NO



 a| 
ospiti
 a| 
Specifica un elenco separato da virgole di indirizzi o nomi host di dispositivi da sottoporre a ping.
 a| 
corda
 a| 
I nodi nel cluster
 a| 
NO



 a| 
interfaccia
 a| 
L'interfaccia (base) esistente da cui devono essere inviati i ping. Valori possibili:

* Bond10G: invia ping dall'interfaccia Bond10G.
* Bond1G: invia ping dall'interfaccia Bond1G.

 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
dimensione del pacchetto
 a| 
Specifica il numero di byte da inviare nel pacchetto ICMP inviato a ciascun IP.  Il numero di byte deve essere inferiore all'MTU massimo specificato nella configurazione di rete.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
pingTimeoutMsec
 a| 
Specifica il numero di millisecondi da attendere per ogni singola risposta ping.
 a| 
intero
 a| 
500 ms
 a| 
NO



 a| 
proibire la frammentazione
 a| 
Abilita il flag DF (Do not Fragment) per i pacchetti ICMP.
 a| 
booleano
 a| 
falso
 a| 
NO



 a| 
sourceAddressV4
 a| 
L'indirizzo IPv4 di origine da utilizzare nei pacchetti ping ICMP.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
sourceAddressV6
 a| 
L'indirizzo IPv6 di origine da utilizzare nei pacchetti ping ICMP.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
timeout totaleSec
 a| 
Specifica il tempo in secondi che il ping deve attendere per una risposta del sistema prima di emettere il successivo tentativo di ping o di terminare il processo.
 a| 
intero
 a| 
5
 a| 
NO



 a| 
virtualNetworkTag
 a| 
ID VLAN da utilizzare durante l'invio dei pacchetti ping.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
risultato
 a| 
Elenco di tutti gli IP con cui il nodo è riuscito a comunicare e statistiche di risposta al ping.
 a| 
Oggetto JSON

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
    "method": "CheckPingOnVlan",
    "params": {
        "interface": "Bond10G",
        "virtualNetworkTag": 4001,
        "sourceAddressV4": "192.168.41.4",
        "hosts": "192.168.41.2"
},
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "192.168.41.2": {
      "individualResponseCodes": [
        "Success",
        "Success",
        "Success",
        "Success",
        "Success"
      ],
      "individualResponseTimes": [
        "00:00:00.000373",
        "00:00:00.000098",
        "00:00:00.000097",
        "00:00:00.000074",
        "00:00:00.000075"
      ],
      "individualStatus": [
        true,
        true,
        true,
        true,
        true
      ],
      "interface": "Bond10G",
      "responseTime": "00:00:00.000143",
      "sourceAddressV4": "192.168.41.4",
      "successful": true,
      "virtualNetworkTag": 4001
    }
  }
}
----


== Nuovo dalla versione

11,1
