---
permalink: api/reference_element_api_createsnapmirrorendpoint_unmanaged.html 
sidebar: sidebar 
keywords: SnapMirror,endpoint,unmanaged,create,creating,CreateSnapMirrorEndpointUnmanaged 
summary: Il sistema di archiviazione software Element utilizza il metodo CreateSnapMirrorEndpointUnmanaged per consentire agli endpoint SnapMirror remoti e non gestiti di comunicare con un cluster di archiviazione Element.  Gli endpoint non gestiti non possono essere amministrati tramite le API Element SnapMirror .  Devono essere gestiti tramite software di gestione ONTAP o API. 
---
= CreateSnapMirrorEndpointUnmanaged
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il sistema di archiviazione software Element utilizza `CreateSnapMirrorEndpointUnmanaged` metodo per consentire agli endpoint SnapMirror remoti e non gestiti di comunicare con un cluster di archiviazione Element.  Gli endpoint non gestiti non possono essere amministrati tramite le API Element SnapMirror .  Devono essere gestiti tramite software di gestione ONTAP o API.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
Nome cluster
 a| 
Il nome dell'endpoint.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
indirizzi IP
 a| 
Elenco di indirizzi IP per un cluster di sistemi di archiviazione ONTAP che devono comunicare con questo cluster di archiviazione Element.
 a| 
matrice di stringhe
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
snapMirrorEndpoint
 a| 
L'endpoint SnapMirror appena creato.
 a| 
xref:reference_element_api_snapmirrorendpoint.adoc[snapMirrorEndpoint]

|===


== Nuovo dalla versione

10,3
