---
permalink: api/reference_element_api_startbulkvolumewrite.html 
sidebar: sidebar 
keywords: volume,bulk,start,starting,write,session,startbulkvolumewrite 
summary: È possibile utilizzare il metodo StartBulkVolumeWrite per avviare una sessione di scrittura di massa su un volume specificato. 
---
= StartBulkVolumeWrite
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `StartBulkVolumeWrite` metodo per avviare una sessione di scrittura di volumi di grandi dimensioni su un volume specificato.

Su un volume possono essere eseguiti contemporaneamente solo due processi di volume di massa.  Quando si inizializza la sessione, i dati vengono scritti su un volume di archiviazione Element da una fonte di backup esterna.  L'accesso ai dati esterni avviene tramite un server web in esecuzione su un nodo di archiviazione Element.  Le informazioni sull'interazione con il server per l'accesso ai dati esterni vengono trasmesse tramite uno script in esecuzione sul sistema di archiviazione.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
formato
 a| 
Il formato dei dati del volume.  Può essere:

* `uncompressed`: Ogni byte del volume viene restituito senza alcuna compressione.
* `native`: Vengono restituiti dati opachi, più piccoli e più efficienti da archiviare e scrivere in una successiva scrittura di volume di massa.

 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
ID volume
 a| 
ID del volume su cui scrivere.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
sceneggiatura
 a| 
Il nome di uno script eseguibile.  Se non viene specificato alcun nome di script, la chiave e l'URL sono necessari per accedere ai nodi di archiviazione Element.  Lo script viene eseguito sul nodo primario e la chiave e l'URL vengono restituiti allo script in modo che sia possibile contattare il server Web locale.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
Parametri di script
 a| 
Parametri JSON da passare allo script.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
NO



 a| 
attributi
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON. link:reference_element_api_attributes.html["Saperne di più"].
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
asyncHandle
 a| 
ID del processo asincrono da verificare per verificarne il completamento.
 a| 
intero



 a| 
chiave
 a| 
Chiave opaca che identifica in modo univoco la sessione.
 a| 
corda



 a| 
URL
 a| 
URL per accedere al server web del nodo.
 a| 
corda

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "StartBulkVolumeWrite",
   "params": {
      "volumeID" : 5,
      "format"  : "native",
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id" : 1,
   "result" : {
      "asyncHandle" : 1,
      "key" : "11eed8f086539205beeaadd981aad130",
      "url" : "https://127.0.0.1:44000/"
   }
}
----


== Nuovo dalla versione

9,6
