---
permalink: api/reference_element_api_modifysnapmirrorendpoint_unmanaged.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,endpoint,modifysnapmirrorendpoint 
summary: 'Il software Element utilizza questa versione del metodo ModifySnapMirrorEndpoint per modificare gli attributi del nome del cluster di archiviazione o dell"indirizzo IP per un endpoint SnapMirror non gestito.  Gli endpoint non gestiti non possono essere amministrati tramite le API Element SnapMirror .  Devono essere gestiti tramite software di gestione ONTAP o API.' 
---
= ModifySnapMirrorEndpoint (non gestito)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il software Element utilizza questa versione del `ModifySnapMirrorEndpoint` Metodo per modificare gli attributi del nome del cluster di archiviazione o dell'indirizzo IP per un endpoint SnapMirror non gestito.  Gli endpoint non gestiti non possono essere amministrati tramite le API Element SnapMirror .  Devono essere gestiti tramite software di gestione ONTAP o API.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
SnapMirrorEndpointID
 a| 
L'endpoint SnapMirror da modificare.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
Nome cluster
 a| 
Il nuovo nome dell'endpoint.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
indirizzi IP
 a| 
Il nuovo elenco di indirizzi IP per un cluster di sistemi di archiviazione ONTAP che dovrebbero comunicare con questo cluster di archiviazione Element.
 a| 
matrice di stringhe
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
snapMirrorEndpoint
 a| 
Informazioni sull'endpoint SnapMirror modificato.
 a| 
xref:reference_element_api_snapmirrorendpoint.adoc[snapMirrorEndpoint]

|===


== Nuovo dalla versione

10,3
