---
permalink: api/reference_element_api_removevirtualnetwork.html 
sidebar: sidebar 
keywords: virtual,network,networks,remove,removing,removevirtualnetwork 
summary: È possibile utilizzare il metodo RemoveVirtualNetwork per rimuovere una rete virtuale aggiunta in precedenza. 
---
= RimuoviVirtualNetwork
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `RemoveVirtualNetwork` metodo per rimuovere una rete virtuale aggiunta in precedenza.


NOTE: Questo metodo richiede come parametro il virtualNetworkID o il virtualNetworkTag, ma non entrambi.


NOTE: Non è possibile rimuovere una rete virtuale se ad essa sono associati degli iniziatori.  Per prima cosa, dissociare gli iniziatori, quindi rimuovere la rete virtuale.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID di rete virtuale
 a| 
ID di rete che identifica la rete virtuale da rimuovere.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
virtualNetworkTag
 a| 
Tag di rete che identifica la rete virtuale da rimuovere.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo non ha valori di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "RemoveVirtualNetwork",
  "params": {
     "virtualNetworkID": 5
    }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result": {}
}
----


== Nuovo dalla versione

9,6
