---
permalink: api/reference_element_api_addclusteradmin.html 
sidebar: sidebar 
keywords: addclusteradmin,cluster,admin,administrator,adding,add 
summary: 'È possibile utilizzare il metodo AddClusterAdmin per aggiungere un nuovo account amministratore del cluster.  Un amministratore del cluster può gestire il cluster tramite l"API e gli strumenti di gestione.  Gli amministratori del cluster sono completamente separati e non correlati agli account tenant standard.' 
---
= AggiungiClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `AddClusterAdmin` metodo per aggiungere un nuovo account amministratore del cluster.  Un amministratore del cluster può gestire il cluster tramite l'API e gli strumenti di gestione.  Gli amministratori del cluster sono completamente separati e non correlati agli account tenant standard.

Ogni amministratore del cluster può essere limitato a un sottoinsieme dell'API.  Dovresti utilizzare più account di amministrazione del cluster per utenti e applicazioni diversi.  Come buona pratica, è consigliabile concedere a ciascun amministratore del cluster le autorizzazioni minime necessarie; ciò riduce il potenziale impatto della compromissione delle credenziali.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
accesso
 a| 
Controlla quali metodi può utilizzare l'amministratore del cluster.
 a| 
matrice di stringhe
 a| 
Nessuno
 a| 
SÌ



 a| 
accettareEula
 a| 
Accettare il Contratto di licenza con l'utente finale.  Impostare su true per aggiungere un account amministratore del cluster al sistema.  Se omesso o impostato su false, la chiamata al metodo fallisce.
 a| 
booleano
 a| 
Nessuno
 a| 
SÌ



 a| 
attributi
 a| 
Elenco di coppie nome/valore nel formato oggetto JSON.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
NO



 a| 
password
 a| 
Password utilizzata per autenticare l'amministratore di questo cluster.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
nome utente
 a| 
Nome utente univoco per questo amministratore del cluster.  Deve avere una lunghezza compresa tra 1 e 1024 caratteri.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
ID amministratore cluster
 a| 
ClusterAdminID per l'amministratore del cluster appena creato.
 a| 
intero

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "AddClusterAdmin",
  "params": {
    "username": "joeadmin",
    "password": "68!5Aru268)$",
    "attributes": {},
    "acceptEula": true,
    "access": ["volumes", "reporting", "read"]
  },
  "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id":1,
  "result" : {
    "clusterAdminID": 2
   }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_app_b_access_control.adoc[Controllo degli accessi]
