---
permalink: api/reference_element_api_app_b_access_control.html 
sidebar: sidebar 
keywords: access,control,type 
summary: I metodi API Element disponibili variano in base al tipo di accesso impostato. 
---
= Controllo degli accessi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
I metodi API Element disponibili variano in base al tipo di accesso impostato.


NOTE: Sono disponibili tipi di accesso tramite l'API che non sono disponibili nell'interfaccia utente di Element.



== conti

Per il tipo di accesso agli account sono disponibili i seguenti metodi:

|===


 a| 
Aggiungi account



 a| 
OttieniAccountPerID



 a| 
Modifica Account



 a| 
OttieniAccountPerNome



 a| 
ElencoAccount



 a| 
Ottieni efficienza dell'account



 a| 
RimuoviAccount

|===


== amministratore

Tutti i metodi sono disponibili per il tipo di accesso amministratore.



== ClusterAdmin

Per il tipo di accesso amministratore del cluster sono disponibili i seguenti metodi:

|===


 a| 
AggiungiClusterAdmin



 a| 
ListBackupTargets



 a| 
AggiungiIniziatoriAlGruppoAccessoVolume



 a| 
ListBulkVolumeJobs



 a| 
AggiungiLdapClusterAdmin



 a| 
ListClusterAdmins



 a| 
AggiungiVirtualNetwork



 a| 
ListClusterPairs



 a| 
AggiungiVirtualNetwork



 a| 
ListNodeFibreChannelPortInfo



 a| 
Aggiungi volume a gruppo di accesso al volume



 a| 
ListBackupTargets



 a| 
Clona più volumi



 a| 
ListDriveHardware



 a| 
CompleteClusterPairing



 a| 
ListFibreChannelSessions



 a| 
CompleteVolumePairing



 a| 
ListFibreChannelPortInfo



 a| 
Crea destinazione di backup



 a| 
ListGroupSnapshots



 a| 
Crea programma



 a| 
ListActivePairedVolumes



 a| 
Crea istantanea



 a| 
Modifica destinazione backup



 a| 
Crea pacchetto di supporto



 a| 
ModificaClusterAdmin



 a| 
Crea Cluster Support Bundle



 a| 
ModificaSnapshotGruppo



 a| 
Crea istantanea di gruppo



 a| 
Modificasogliacompleta del cluster



 a| 
Crea gruppo di accesso al volume



 a| 
ModificaVolumeAccessGroup



 a| 
Elimina tutti i pacchetti di supporto



 a| 
ModifyVolumeAccessGroupLunAssignments



 a| 
EliminaSnapshot



 a| 
Modifica coppia di volumi



 a| 
EliminaSnapshot di Gruppo



 a| 
Modificare la rete virtuale



 a| 
DeleteVolumeAccessGroup



 a| 
RimuoviClusterAdmin



 a| 
Disabilita la crittografia a riposo



 a| 
RemoveVolumePair



 a| 
Disabilita l'autenticazione LDAP



 a| 
RimuoviVirtualNetwork



 a| 
Disabilita Snmp



 a| 
RimuoviVolumiDaVolumeAccessGroup



 a| 
Abilita crittografia a riposo



 a| 
RemoveInitiatorsFromVolumeAccessGroup



 a| 
Abilita autenticazione LDAP



 a| 
RollbackToSnapshot



 a| 
AbilitaSnmp



 a| 
RollbackToGroupSnapshot



 a| 
Ottieni destinazione di backup



 a| 
SetLoginSessionInfo



 a| 
Ottieni soglia completa del cluster



 a| 
ImpostaNtpInfo



 a| 
OttieniClusterMasterNodeID



 a| 
SetSnmpACL



 a| 
OttieniConfigurazioneHardware



 a| 
ImpostaSnmpInfo



 a| 
OttieniLdapConfiguration



 a| 
ImpostaSnmpTrapInfo



 a| 
Ottieni informazioni sulla sessione di accesso



 a| 
Imposta host di registrazione remoti



 a| 
Ottieni informazioni Ntp



 a| 
Fermare



 a| 
Ottieni informazioni Nvram



 a| 
StartBulkVolumeRead



 a| 
Ottieni statistiche grezze



 a| 
StartBulkVolumeWrite



 a| 
OttieniSnmpACL



 a| 
StartClusterPairing



 a| 
GetVolumeAccessGroupEfficiency



 a| 
StartVolumePairing



 a| 
GetVolumeAccessLunAssignments



 a| 
TestLdapAuthentication



 a| 
OttieniVirtualNetwork



 a| 

|===


== unità

Per il tipo di accesso alle unità sono disponibili i seguenti metodi:

|===


 a| 
ListDrives



 a| 
Rimuovi unità



 a| 
Aggiungi unità



 a| 
SecureEraseDrives

|===


== nodi

Per il tipo di accesso ai nodi sono disponibili i seguenti metodi:

|===


 a| 
Aggiungi nodi



 a| 
Elenco nodi in sospeso



 a| 
ListActiveNodes



 a| 
Rimuovi nodi

|===


== Leggere

Per il tipo di accesso in lettura sono disponibili i seguenti metodi:

|===


 a| 
OttieniAccountPerID



 a| 
ListCloneJobs



 a| 
OttieniAccountPerNome



 a| 
ElencoVolumiEliminati



 a| 
Ottieni risultato asincrono



 a| 
ListDriveHardware



 a| 
Ottieni capacità cluster



 a| 
ListDrives



 a| 
OttieniQoS predefinito



 a| 
ElencoEventi



 a| 
Ottieni statistiche di guida



 a| 
ElencoISCSISessioni



 a| 
Ottieni l'aggiornamento del software



 a| 
Elenco nodi in sospeso



 a| 
Ottieni statistiche sul volume



 a| 
ListSyncJobs



 a| 
ElencoAccount



 a| 
ListVolumeAccessGroups



 a| 
ListActiveNodes



 a| 
ListVolumeStatsByAccount



 a| 
ListActiveNodes



 a| 
ListVolumeStatsByVolume



 a| 
ListActiveVolumes



 a| 
ListVolumeStatsByVolumeAccessGroup



 a| 
Elenca tutti i nodi



 a| 
ListVolumesForAccount



 a| 
ListBackupTargets

|===


== segnalazione

Per il tipo di accesso alla segnalazione sono disponibili i seguenti metodi:

|===


 a| 
ClearClusterFaults



 a| 
OttieniEfficienzaVolume



 a| 
Ottieni efficienza dell'account



 a| 
Ottieni statistiche sul volume



 a| 
Ottieni capacità cluster



 a| 
ListCloneJobs



 a| 
OttieniClusterHardwareInfo



 a| 
ListClusterFaults



 a| 
Ottieni informazioni sul cluster



 a| 
ListClusterPairs



 a| 
OttieniClusterMasterNodeID



 a| 
ListDriveHardware



 a| 
Ottieni statistiche cluster



 a| 
ElencoEventi



 a| 
Ottieni informazioni sull'hardware dell'unità



 a| 
ElencoISCSISessioni



 a| 
Ottieni statistiche di guida



 a| 
ListSchedules



 a| 
OttieniConfigurazione di rete



 a| 
ElencoServizi



 a| 
Ottieni informazioni hardware del nodo



 a| 
ListSyncJobs



 a| 
Ottieni statistiche nodo



 a| 
ElencoRetiVirtuali



 a| 
OttieniSnmpInfo



 a| 
ListVolumeStatsByAccount



 a| 
OttieniSnmpTrapInfo



 a| 
ListVolumeStatsByVolume



 a| 
GetVolumeAccessGroupEfficiency



 a| 
ListVolumeStatsByVolumeAccessGroup

|===


== repository

Il metodo ListAllNodes è disponibile per il tipo di accesso ai repository.



== volumi

Per il tipo di accesso ai volumi sono disponibili i seguenti metodi:

|===


 a| 
Crea volume



 a| 
Elimina volume



 a| 
Modifica destinazione backup



 a| 
CloneVolume



 a| 
DeleteVolumePairing



 a| 
ModificaVolumi



 a| 
Clona più volumi



 a| 
Ottieni destinazione di backup



 a| 
Modifica coppia di volumi



 a| 
Crea destinazione di backup



 a| 
OttieniQoS predefinito



 a| 
PurgeDeletedVolume



 a| 
Crea istantanea



 a| 
ListActiveVolumes



 a| 
RimuoviBackupTarget



 a| 
Crea istantanea di gruppo



 a| 
ListBackupTarget



 a| 
RemoveVolumePair



 a| 
CompleteVolumePairing



 a| 
ListGroupSnapshots



 a| 
RipristinaVolumeEliminato



 a| 
Clona più volumi



 a| 
ListVolumesForAccount



 a| 
RollbackToGroupSnapshot



 a| 
EliminaSnapshot di Gruppo



 a| 
ElencoVolumiEliminati



 a| 
RollbackToSnapshot



 a| 
EliminaSnapshot



 a| 
ListGroupSnapshots



 a| 
StartBulkVolumeRead



 a| 
StartBulkVolumeWrite



 a| 
StartVolumePairing



 a| 
AggiornaStatoVolumeMassuale

|===


== scrivere

Per il tipo di accesso in scrittura sono disponibili i seguenti metodi:

|===


 a| 
Aggiungi unità



 a| 
Rimuovi nodi



 a| 
Aggiungi nodi



 a| 
RimuoviAccount



 a| 
Aggiungi account



 a| 
RimuoviVolumiDaVolumeAccessGroup



 a| 
AggiungiVolumeAGruppoAccessoVolume



 a| 
RemoveInitiatorsFromVolumeAccessGroup



 a| 
AggiungiIniziatoriAlGruppoAccessoVolume



 a| 
DeleteVolumeAccessGroup



 a| 
Crea gruppo di accesso al volume



 a| 
Elimina volume



 a| 
ModificaVolumeAccessGroup



 a| 
RipristinaVolumeEliminato



 a| 
Modifica Account



 a| 
PurgeDeletedVolume



 a| 
Crea volume



 a| 
ModificaVolume



 a| 
CloneVolume



 a| 
Ottieni risultato asincrono



 a| 
Rimuovi unità

|===
.Informazioni correlate
link:../storage/concept_system_manage_manage_cluster_administrator_users.html#view-cluster-admin-details["Scopri i tipi di accesso disponibili nell'interfaccia utente di Element"]
