---
permalink: api/reference_element_api_node_getnodefipsdrivesreport.html 
sidebar: sidebar 
keywords: individual,fips,feature,support,info,report,get,getting,getnodefipsdrivesreport,drive 
summary: 'È possibile utilizzare il metodo GetNodeFipsDrivesReport per verificare lo stato della capacità di crittografia dell"unità FIPS 140-2 di un singolo nodo nel cluster di archiviazione.  È necessario eseguire questo metodo su un singolo nodo di archiviazione.' 
---
= Ottieni report sui drive dei nodi Fips
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetNodeFipsDrivesReport` metodo per verificare lo stato della capacità di crittografia dell'unità FIPS 140-2 di un singolo nodo nel cluster di archiviazione.  È necessario eseguire questo metodo su un singolo nodo di archiviazione.



== Parametro

Questo metodo non ha parametri di input.



== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
fipsDrives
 a| 
Un oggetto JSON contenente lo stato del supporto delle funzionalità FIPS 140-2 per questo nodo. Valori possibili:

* Nessuno: il nodo non è compatibile con FIPS.
* Parziale: il nodo supporta FIPS, ma non tutte le unità nel nodo sono unità FIPS.
* Pronto: il nodo è compatibile con FIPS e tutte le unità nel nodo sono unità FIPS (oppure non sono presenti unità).

 a| 
corda

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "GetNodeFipsDrivesReport",
  "params": {},
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
    "id": 1,
    "result": {
        "fipsDrives": "None"
    }
}
----


== Nuovo dalla versione

11,5
