---
permalink: api/reference_element_api_listclusteradmins.html 
sidebar: sidebar 
keywords: admin,admins,cluster,list,listing,listclusteradmins 
summary: 'È possibile utilizzare il metodo ListClusterAdmins per restituire l"elenco di tutti gli amministratori del cluster.' 
---
= ListClusterAdmins
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListClusterAdmins` metodo per restituire l'elenco di tutti gli amministratori del cluster.

Possono esserci più account di amministratore del cluster con diversi livelli di autorizzazione.  Nel sistema può esserci un solo amministratore del cluster primario.  L'amministratore primario del cluster è l'amministratore creato al momento della creazione del cluster.  Gli amministratori LDAP possono essere creati anche durante la configurazione di un sistema LDAP sul cluster.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
mostraNascosto
 a| 
Mostra gli utenti amministratori del cluster nascosti, come l'amministratore SNMP.
 a| 
booleano
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
amministratori del cluster
 a| 
Informazioni su tutti gli amministratori di cluster e LDAP esistenti per un cluster.
 a| 
xref:reference_element_api_clusteradmin.adoc[ClusterAdmin]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ListClusterAdmins",
   "params": {},
    "showHidden": true
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
"id":1,
"result":{
  "clusterAdmins":[
     {
       "access":[
           "administrator"
       ],
       "attributes":null,
       "authMethod":"Cluster",
       "clusterAdminID":1,
       "username":"admin"
   },
   {
       "access":[
           "read",
           "administrator"
       ],
       "attributes":{
       },
       "authMethod":"Ldap",
       "clusterAdminID":7,
       "username":"john.smith"
   },
   {
       "access":[
           "read",
           "administrator"
       ],
       "attributes":{},
       "authMethod":"Ldap",
       "clusterAdminID":6,
       "username":"cn=admin1 jones,ou=ptusers,c=prodtest,dc=solidfire,dc=net"
       }
     ]
   }
}
----


== Nuovo dalla versione

9,6
