---
permalink: api/reference_element_api_resyncsnapmirrorrelationship.html 
sidebar: sidebar 
keywords: SnapMirror,relationship,resync,resyncing,ResyncSnapMirrorRelationship 
summary: 'L"interfaccia utente Web del software Element utilizza il metodo ResyncSnapMirrorRelationship per stabilire o ristabilire una relazione mirror tra un endpoint di origine e uno di destinazione.  Quando si risincronizza una relazione, il sistema rimuove gli snapshot sul volume di destinazione che sono più recenti della copia snapshot comune, quindi monta il volume di destinazione come volume di protezione dati con la copia snapshot comune come copia snapshot esportata.' 
---
= ResyncSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web del software Element utilizza `ResyncSnapMirrorRelationship` metodo per stabilire o ristabilire una relazione mirror tra un endpoint di origine e uno di destinazione.  Quando si risincronizza una relazione, il sistema rimuove gli snapshot sul volume di destinazione che sono più recenti della copia snapshot comune, quindi monta il volume di destinazione come volume di protezione dati con la copia snapshot comune come copia snapshot esportata.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
snapMirrorEndpointID
 a| 
ID endpoint del sistema di archiviazione ONTAP remoto che comunica con il cluster di archiviazione Element.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
destinazioneVolume
 a| 
Il volume di destinazione nella relazione SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Nessuno
 a| 
SÌ



 a| 
maxTransferRate
 a| 
Specifica la velocità massima di trasferimento dati tra i volumi in kilobyte al secondo.  Il valore predefinito, 0, è illimitato e consente alla relazione SnapMirror di utilizzare completamente la larghezza di banda di rete disponibile.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
sorgenteVolume
 a| 
Il volume sorgente nella relazione SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
snapMirrorRelationship
 a| 
Un oggetto contenente informazioni sulla relazione SnapMirror risincronizzata.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Nuovo dalla versione

10,1
