---
permalink: api/reference_element_api_enableidpauthentication.html 
sidebar: sidebar 
keywords: IdP,idp,authentication,enable 
summary: 'È possibile utilizzare il metodo EnableIdpAuthentication per abilitare il supporto per l"autenticazione tramite IdP di terze parti per il cluster.  Una volta abilitata l"autenticazione IdP, gli amministratori LDAP e del cluster non saranno più in grado di accedere al cluster tramite le interfacce utente supportate e tutte le sessioni autenticate attive verranno invalidate/disconnesse.  Solo gli utenti autenticati da IdP di terze parti possono accedere al cluster tramite le interfacce utente supportate.' 
---
= Abilita autenticazione Idp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `EnableIdpAuthentication` metodo per abilitare il supporto per l'autenticazione tramite IdP di terze parti per il cluster.  Una volta abilitata l'autenticazione IdP, gli amministratori LDAP e del cluster non saranno più in grado di accedere al cluster tramite le interfacce utente supportate e tutte le sessioni autenticate attive verranno invalidate/disconnesse.  Solo gli utenti autenticati da IdP di terze parti possono accedere al cluster tramite le interfacce utente supportate.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
idpConfigurationID
 a| 
UUID per la configurazione dell'IdP di terze parti.  Se esiste una sola configurazione IdP, l'impostazione predefinita è abilitare tale configurazione.  Se si dispone di un solo IdpConfiguration, non è necessario fornire il parametro idpConfigurationID.
 a| 
UUID
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo non ha valori di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "EnableIdpAuthentication",
  "params": {
    "idpConfigurationID": "f983c602-12f9-4c67-b214-bf505185cfed",
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
"result": {}
}
----


== Nuovo dalla versione

12,0
