---
permalink: api/reference_element_api_modifykeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,modifying,modify,change,edit 
summary: 'È possibile utilizzare il metodo ModifyKeyServerKmip per modificare un server di chiavi Key Management Interoperability Protocol \(KMIP\) esistente con gli attributi specificati.  Sebbene l"unico parametro obbligatorio sia keyServerID, una richiesta contenente solo keyServerID non eseguirà alcuna azione e non restituirà alcun errore.  Tutti gli altri parametri specificati sostituiranno i valori esistenti per il server delle chiavi con il keyServerID specificato.  Durante l"operazione viene contattato il server delle chiavi per verificarne il funzionamento.  È possibile specificare più nomi host o indirizzi IP con il parametro kmipKeyServerHostnames, ma solo se i server chiave sono in una configurazione in cluster.' 
---
= ModifyKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ModifyKeyServerKmip` metodo per modificare un server di chiavi KMIP (Key Management Interoperability Protocol) esistente con gli attributi specificati.  Sebbene l'unico parametro obbligatorio sia keyServerID, una richiesta contenente solo keyServerID non eseguirà alcuna azione e non restituirà alcun errore.  Tutti gli altri parametri specificati sostituiranno i valori esistenti per il server delle chiavi con il keyServerID specificato.  Durante l'operazione viene contattato il server delle chiavi per verificarne il funzionamento.  È possibile specificare più nomi host o indirizzi IP con il parametro kmipKeyServerHostnames, ma solo se i server chiave sono in una configurazione in cluster.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID del server chiave
 a| 
ID del server chiavi KMIP da modificare.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
kmipCaCertificate
 a| 
Il certificato della chiave pubblica della CA radice del server delle chiavi esterno.  Verrà utilizzato per verificare il certificato presentato dal server delle chiavi esterno nella comunicazione TLS.  Per i cluster di server chiave in cui i singoli server utilizzano CA diverse, fornire una stringa concatenata contenente i certificati radice di tutte le CA.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
kmipClientCertificate
 a| 
Un certificato PKCS#10 X.509 codificato Base64 in formato PEM utilizzato dal client Solidfire KMIP.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
kmipKeyServerHostnames
 a| 
Matrice dei nomi host o degli indirizzi IP associati a questo server di chiavi KMIP.  È necessario fornire più nomi host o indirizzi IP solo se i server chiave sono in una configurazione cluster.
 a| 
matrice di stringhe
 a| 
Nessuno
 a| 
NO



 a| 
kmipKeyServerName
 a| 
Il nome del server delle chiavi KMIP.  Questo nome viene utilizzato solo a scopo di visualizzazione e non deve essere univoco.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
kmipKeyServerPort
 a| 
Il numero di porta associato a questo server di chiavi KMIP (in genere 5696).
 a| 
intero
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
kmipKeyServer
 a| 
Un oggetto contenente dettagli sul server delle chiavi appena modificato.
 a| 
link:reference_element_api_keyserverkmip.html["KeyServerKmip"]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ModifyKeyServerKmip",
  "params": {
    "keyServerID": 15
    "kmipCaCertificate": "CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
    "kmipClientCertificate": "kirWmnWXbj9T/UWZYB2oK0z5...",
    "kmipKeyServerHostnames" : ["server1.hostname.com", "server2.hostname.com"],
    "kmipKeyServerName" : "keyserverName",
    "kmipKeyServerPort" : 5696
  },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"CPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":1
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"kirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Nuovo dalla versione

11,7
