---
permalink: api/reference_element_api_deleteauthsession.html 
sidebar: sidebar 
keywords: authentication sessions,delete 
summary: 'È possibile utilizzare il metodo DeleteAuthSession per eliminare una singola sessione di autenticazione.  Se l"utente chiamante non è presente nel ClusterAdmins/Administrator AccessGroup, è possibile eliminare solo la sessione di autenticazione appartenente all"utente chiamante.' 
---
= DeleteAuthSession
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `DeleteAuthSession` metodo per eliminare una singola sessione di autenticazione utente.  Se l'utente chiamante non è presente nel ClusterAdmins/Administrator AccessGroup, è possibile eliminare solo la sessione di autenticazione appartenente all'utente chiamante.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID sessione
 a| 
Identificatore univoco per la sessione di autenticazione da eliminare.
 a| 
UUID
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
sessione
 a| 
Informazioni sulla sessione per l'autorizzazione all'eliminazione.
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
    "method": "DeleteAuthSession",
    "params": {
        "sessionID": "a862a8bb-2c5b-4774-a592-2148e2304713"
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
    "id": 1,
    "result": {
        "session": {
            "accessGroupList": [
                "administrator"
            ],
            "authMethod": "Cluster",
            "clusterAdminIDs": [
                1
            ],
            "finalTimeout": "2020-04-09T17:51:30Z",
            "idpConfigVersion": 0,
            "lastAccessTimeout": "2020-04-06T18:21:33Z",
            "sessionCreationTime": "2020-04-06T17:51:30Z",
            "sessionID": "a862a8bb-2c5b-4774-a592-2148e2304713",
            "username": "admin"
        }
    }
}
----


== Nuovo dalla versione

12,0
