---
permalink: api/reference_element_api_listvolumestatsbyvolumeaccessgroup.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,access,group,listvolumestatsbyvolumeaccessgroup,activity 
summary: 'È possibile utilizzare il metodo ListVolumeStatsByVolumeAccessGroup per elencare le misurazioni totali dell"attività per tutti i volumi che sono membri dei gruppi di accesso al volume specificati.' 
---
= ListVolumeStatsByVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListVolumeStatsByVolumeAccessGroup` metodo per elencare le misurazioni dell'attività totale per tutti i volumi che sono membri dei gruppi di accesso al volume specificati.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
includeVirtualVolumes
 a| 
Per impostazione predefinita, i volumi virtuali sono inclusi nella risposta.  Per escludere i volumi virtuali, impostare su false.
 a| 
booleano
 a| 
VERO
 a| 
NO



 a| 
volumeAccessGroups
 a| 
Un array di VolumeAccessGroupID per i quali viene restituita l'attività del volume.  Se omesso, vengono restituite le statistiche per tutti i gruppi di accesso al volume.
 a| 
array di interi
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
volumeStats
 a| 
Elenco delle informazioni sull'attività del volume per tutti i volumi nel gruppo di accesso al volume specificato.*Nota:* il membro volumeID è 0 per ogni voce, perché i valori rappresentano la somma di tutti i volumi di proprietà dell'account.
 a| 
xref:reference_element_api_volumestats.adoc[volumeStats]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ListVolumeStatsByVolumeAccessGroup",
    "params": {"volumeAccessGroups": [1]},
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 0,
        "nonZeroBlocks": 149366393,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T21:04:10.712370Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [
            1
        ],
        "volumeID": 0,
        "volumeSize": 1073741824000,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 112777607
      }
    ]
  }
}
----


== Nuovo dalla versione

9,6
