---
permalink: api/reference_element_api_testconnectensemble.html 
sidebar: sidebar 
keywords: test,testing,connectivity,ensemble,testconnectensemble 
summary: 'È possibile utilizzare il metodo TestConnectEnsemble per verificare la connettività con un insieme di database specificato.  Per impostazione predefinita, utilizza l"ensemble per il cluster a cui è associato il nodo.  In alternativa, è possibile fornire un insieme diverso per testare la connettività.' 
---
= TestConnectEnsemble
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `TestConnectEnsemble` metodo per verificare la connettività con un insieme di database specificato.  Per impostazione predefinita, utilizza l'ensemble per il cluster a cui è associato il nodo.  In alternativa, è possibile fornire un insieme diverso per testare la connettività.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


| insieme | Un elenco separato da virgole di indirizzi IP di cluster di nodi ensemble per i test di connettività. | corda | Nessuno | NO 
|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


| dettagli  a| 
Oggetti restituiti:

* `nodes`: (oggetto) Un elenco di ciascun nodo dell'ensemble nel test e i risultati dei test.
* `duration`: (stringa) Tempo necessario per eseguire il test.
* `result`: (stringa) I risultati dell'intero test.

| Oggetto JSON 
|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "TestConnectEnsemble",
  "params": {},
  "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result": {
      "details": {
         "nodes":  {
            "1:10.10.20.70": "Passed",
            "2:10.10.20.71": "Passed",
            "3:10.10.20.72": "Passed",
            "4:10.10.20.73": "Passed",
            "5:10.10.20.74": "Passed"
        }
      },
        "duration": "00:00:00:756072",
        "result": "Passed"
   }
}
----


== Nuovo dalla versione

9,6
