---
permalink: api/reference_element_api_listevents.html 
sidebar: sidebar 
keywords: cluster,list,listing,event,events,listevents 
summary: È possibile utilizzare il metodo ListEvents per elencare gli eventi rilevati nel cluster, ordinati dal più vecchio al più recente. 
---
= ElencoEventi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListEvents` metodo per elencare gli eventi rilevati sul cluster, ordinati dal più vecchio al più recente.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID unità
 a| 
Specifica che verranno restituiti solo gli eventi con questo ID unità.
 a| 
intero
 a| 
0
 a| 
NO



 a| 
endEventID
 a| 
Identifica la fine di un intervallo di ID evento da restituire.
 a| 
intero
 a| 
(illimitato)
 a| 
NO



 a| 
endPublishTime
 a| 
Specifica che verranno restituiti solo gli eventi pubblicati prima di questo orario.
 a| 
corda
 a| 
0
 a| 
NO



 a| 
endReportTime
 a| 
Specifica che verranno restituiti solo gli eventi segnalati prima di questo orario.
 a| 
corda
 a| 
0
 a| 
NO



 a| 
tipoevento
 a| 
Specifica il tipo di eventi da restituire.  Vederexref:reference_element_api_event.adoc[evento] per possibili tipi di eventi.
 a| 
corda
 a| 
0
 a| 
NO



 a| 
maxEventi
 a| 
Specifica il numero massimo di eventi da restituire.
 a| 
intero
 a| 
(illimitato)
 a| 
NO



 a| 
ID nodo
 a| 
Specifica che verranno restituiti solo gli eventi con questo ID nodo.
 a| 
intero
 a| 
 a| 



 a| 
ID servizio
 a| 
Specifica che verranno restituiti solo gli eventi con questo ID servizio.
 a| 
 a| 
 a| 



 a| 
ID evento di avvio
 a| 
Identifica l'inizio di una serie di eventi da restituire.
 a| 
intero
 a| 
0
 a| 
NO



 a| 
inizioPubblicazioneOra
 a| 
Specifica che verranno restituiti solo gli eventi pubblicati dopo questo orario.
 a| 
corda
 a| 
0
 a| 
NO



 a| 
startReportTime
 a| 
Specifica che verranno restituiti solo gli eventi segnalati dopo questo orario.
 a| 
corda
 a| 
0
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
eventi
 a| 
Elenco degli eventi.
 a| 
xref:reference_element_api_event.adoc[evento]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ListEvents",
   "params": {
   },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id":1,
  "result":{
    "events":[
       {
          "details":
            {
              "paramGCGeneration":1431550800,
              "paramServiceID":2
            },
          "driveID":0,
          "eventID":2131,
          "eventInfoType":"gcEvent",
          "message":"GC Cluster Coordination Complete",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.361354Z",
          "timeOfReport":"2015-05-13T21:00:02.361269Z"
       },{
          "details":
               {
                  "eligibleBS":[5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,24,25,26,27,28,29,30,31,40,41,42,43,44,45,46,47,52,53,54,55,56,57,58,59,60],
                  "generation":1431550800,
                  "participatingSS":[23,35,39,51]
               },
          "driveID":0,
          "eventID":2130,
          "eventInfoType":"gcEvent",
          "message":"GCStarted",
          "nodeID":0,
          "serviceID":2,
          "severity":0,
          "timeOfPublish":"2015-05-13T21:00:02.354128Z",
          "timeOfReport":"2015-05-13T21:00:02.353894Z"
       },{
          "details":"",
          "driveID":0,
          "eventID":2129,
          "eventInfoType":"tSEvent",
          "message":"return code:2 t:41286 tt:41286 qcc:1 qd:1 qc:1 vrc:1 tt:2 ct:Write etl:524288",
          "nodeID":0,
          "serviceID":0,
          "severity":0,
          "timeOfPublish":"2015-05-13T20:45:21.586483Z",
          "timeOfReport":"2015-05-13T20:45:21.586311Z"
       }
     ]
   }
}
----


== Nuovo dalla versione

9,6
