---
permalink: api/reference_element_api_createsnapmirrorendpoint.html 
sidebar: sidebar 
keywords: SnapMirror,endpoints,endpoint,creating,create,CreateSnapMirrorEndpoint 
summary: 'L"interfaccia utente Web di Element utilizza il metodo CreateSnapMirrorEndpoint per creare una relazione con un endpoint SnapMirror remoto.' 
---
= CreaSnapMirrorEndpoint
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente web Element utilizza `CreateSnapMirrorEndpoint` metodo per creare una relazione con un endpoint SnapMirror remoto.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
gestioneIP
 a| 
Indirizzo IP di gestione dell'endpoint remoto SnapMirror .
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
nome utente
 a| 
Nome utente di gestione per il sistema ONTAP .
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
password
 a| 
La password di gestione per il sistema ONTAP .
 a| 
corda
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
snapMirrorEndpoint
 a| 
L'endpoint SnapMirror appena creato.
 a| 
xref:reference_element_api_snapmirrorendpoint.adoc[snapMirrorEndpoint]

|===


== Nuovo dalla versione

10,0
