---
permalink: api/reference_element_api_getnodestats.html 
sidebar: sidebar 
keywords: node,get,getting,stats,getnodestats 
summary: 'È possibile utilizzare il metodo GetNodeStats per recuperare le misurazioni dell"attività di alto livello per un singolo nodo.' 
---
= Ottieni statistiche nodo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetNodeStats` metodo per recuperare le misurazioni dell'attività di alto livello per un singolo nodo.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID nodo
 a| 
Specifica l'ID del nodo per il quale verranno restituite le statistiche.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
nodeStats
 a| 
Informazioni sull'attività del nodo.
 a| 
xref:reference_element_api_nodestats.adoc[nodeStats]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "GetNodeStats",
   "params": {
     "nodeID": 5
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id" : 1,
   "result" : {
     "nodeStats": {
       "cBytesIn": 1579657943924,
       "cBytesOut": 1683056745816,
       "count": 119529,
       "cpu": 0,
       "cpuTotal": 56289,
       "mBytesIn": 475476878,
       "mBytesOut": 269270423,
       "networkUtilizationCluster": 0,
       "networkUtilizationStorage": 0,
       "nodeHeat": {
         "primaryTotalHeat": 0.00098,
         "recentPrimaryTotalHeat": 0.00099,
         "recentTotalHeat": 0.00099,
         "totalHeat": 0.00098
       },
       "readLatencyUSecTotal": 10125300382,
       "readOps": 15640075,
       "sBytesIn": 1579657943924,
       "sBytesOut": 1683056745816,
       "ssLoadHistogram": {
         "Bucket0": 4873,
         "Bucket1To19": 6301620,
         "Bucket20To39": 396452,
         "Bucket40To59": 142,
         "Bucket60To79": 0,
         "Bucket80To100": 0
       },
       "timestamp": "2024-03-04T20:13:22.105428Z",
       "usedMemory": 106335510528,
       "writeLatencyUSecTotal": 7314512535,
       "writeOps": 59154830
     }
   }
}
----


== Nuovo dalla versione

9,6
