---
permalink: api/reference_element_api_listvirtualvolumebindings.html 
sidebar: sidebar 
keywords: virtual,volume,vvol,cluster,bound,protocol,endpoint,binding,bindings,list,listing,listvirtualvolumebindings 
summary: È possibile utilizzare il metodo ListVirtualVolumeBindings per ottenere un elenco di tutti i volumi virtuali nel cluster associati agli endpoint del protocollo. 
---
= ListVirtualVolumeBindings
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListVirtualVolumeBindings` metodo per ottenere un elenco di tutti i volumi virtuali nel cluster associati agli endpoint del protocollo.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
virtualVolumeBindingIDs
 a| 
Un elenco di ID di associazione di volumi virtuali per i quali recuperare informazioni.  Se si omette questo parametro, il metodo restituisce informazioni su tutti i binding dei volumi virtuali.
 a| 
array di interi
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
legature
 a| 
Un elenco di oggetti che descrivono tutti i volumi virtuali nel cluster associati agli endpoint del protocollo.
 a| 
xref:reference_element_api_binding_vvols.adoc[legame]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ListVirtualVolumeBindings",
    "params": {
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "bindings": [
      {
        "protocolEndpointID": "5dd53da0-b9b7-43f9-9b7e-b41c2558e92b",
        "protocolEndpointInBandID": "naa.6f47acc2000000016a67746700000000",
        "protocolEndpointType": "SCSI",
        "virtualVolumeBindingID": 177,
        "virtualVolumeHostID": "564de1a4-9a99-da0f-8b7c-3a41dfd64bf1",
        "virtualVolumeID": "269d3378-1ca6-4175-a18f-6d4839e5c746",
        "virtualVolumeSecondaryID": "0xe200000000a6"
      }
    ]
  }
}
----


== Nuovo dalla versione

9,6
