---
permalink: api/reference_element_api_listclusterpairs.html 
sidebar: sidebar 
keywords: cluster,pair,pairs,paired,list,listing,listclusterpairs 
summary: 'È possibile utilizzare il metodo ListClusterPairs per elencare tutti i cluster associati al cluster corrente.  Questo metodo restituisce informazioni sulle coppie di cluster attive e in sospeso, come statistiche sulla coppia corrente, nonché sulla connettività e sulla latenza (in millisecondi) della coppia di cluster.' 
---
= ListClusterPairs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListClusterPairs` metodo per elencare tutti i cluster associati al cluster corrente.  Questo metodo restituisce informazioni sulle coppie di cluster attive e in sospeso, come statistiche sulla coppia corrente, nonché sulla connettività e sulla latenza (in millisecondi) della coppia di cluster.



== Parametro

Questo metodo non ha parametri di input:



== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
clusterPairs
 a| 
Informazioni su ciascun cluster accoppiato.
 a| 
xref:reference_element_api_clusterpair.adoc[clusterPair]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ListClusterPairs",
   "params": {
      },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
 "id": 1,
 "result": {
   "clusterPairs": [
     {
      "clusterName": "cluster2",
      "clusterPairID": 3,
      "clusterPairUUID": "9866fbeb-c2f8-4df3-beb9-58a5c4e49c9b",
      "clusterUUID": 5487,
      "latency": 1,
      "mvip": "172.1.1.5",
      "status": "Connected"
      "version": "8.0.0.1361"
     },
     {
      "clusterName": "cluster3",
      "clusterPairID": 2,
      "clusterPairUUID": "8132a699-ce82-41e0-b406-fb914f976042",
      "clusterUUID": 1383,
      "latency": 1,
      "mvip": "172.1.1.6",
      "status": "Connected"
      "version": "8.0.0.1361"
     }
   ]
 }
----


== Nuovo dalla versione

9,6
