---
permalink: api/reference_element_api_volumeaccessgroup.html 
sidebar: sidebar 
keywords: object,objects,volumeAccessGroup 
summary: 'L"oggetto volumeAccessGroup contiene informazioni su uno specifico gruppo di accesso al volume.  È possibile recuperare un elenco di queste informazioni per tutti i gruppi di accesso con il metodo API ListVolumeAccessGroups.' 
---
= volumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto volumeAccessGroup contiene informazioni su uno specifico gruppo di accesso al volume.  È possibile recuperare un elenco di queste informazioni per tutti i gruppi di accesso con il metodo API `ListVolumeAccessGroups` .



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
attributi
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON



 a| 
volumi eliminati
 a| 
Matrice di volumi eliminati dal gruppo di accesso al volume e non ancora eliminati dal sistema.
 a| 
array di interi



 a| 
ID iniziatore
 a| 
Un elenco di ID degli iniziatori mappati al gruppo di accesso al volume.
 a| 
array di interi



 a| 
iniziatori
 a| 
Matrice di iniziatori IQN/WWPN univoci mappati al gruppo di accesso al volume.
 a| 
matrice di stringhe



 a| 
nome
 a| 
Nome del gruppo di accesso al volume.
 a| 
corda



 a| 
volumeAccessGroupID
 a| 
Identificatore univoco VolumeAccessGroupID per il gruppo di accesso al volume.
 a| 
intero



 a| 
volumi
 a| 
Un elenco di VolumeID appartenenti al gruppo di accesso al volume.
 a| 
array di interi

|===


== Trova maggiori informazioni

xref:reference_element_api_listvolumeaccessgroups.adoc[ListVolumeAccessGroups]
