---
permalink: api/reference_element_api_signsshkeys.html 
sidebar: sidebar 
keywords: ssh, sign key 
summary: Dopo aver abilitato ssh su un nodo o cluster, è possibile utilizzare il metodo SignSshKeys per accedere a una shell su un nodo come sfadmin o sfreadonly. sfreadonly è un nuovo account utente a partire da Element 12.5 che consente la risoluzione iniziale dei problemi su un nodo, ma non dispone dei privilegi per eseguire comandi elevati. 
---
= SignSshKeys
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo che SSH è abilitato sul cluster utilizzandolink:../api/reference_element_api_enablessh.html["Metodo EnableSSH"] , puoi usare il `SignSshKeys` metodo per ottenere l'accesso a una shell su un nodo.

A partire dall'elemento 12.5, `sfreadonly` è un nuovo account di sistema che consente la risoluzione dei problemi di base su un nodo.  Questa API consente l'accesso SSH utilizzando `sfreadonly` account di sistema su tutti i nodi del cluster.


WARNING: Salvo diversa indicazione da parte del supporto NetApp , qualsiasi modifica al sistema non è supportata, invalidando il contratto di supporto e potendo causare instabilità o inaccessibilità dei dati.

Dopo aver utilizzato il metodo, è necessario copiare il portachiavi dalla risposta, salvarlo sul sistema che avvierà la connessione SSH, quindi eseguire il seguente comando:

[listing]
----
ssh -i <identity_file> sfreadonly@<node_ip>
----
 `identity_file`è un file da cui viene letta l'identità (chiave privata) per l'autenticazione con chiave pubblica e `node_ip` è l'indirizzo IP del nodo.  Per maggiori informazioni su `identity_file` , vedere la pagina man di SSH.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
durata
 a| 
Numero intero da 1 a 24 che indica il numero di ore per cui la chiave firmata è valida.  Se la durata non è specificata, viene utilizzato il valore predefinito.
 a| 
intero
 a| 
1
 a| 
NO



 a| 
chiave pubblica
 a| 
Se specificato, questo parametro restituirà solo signed_public_key anziché creare un portachiavi completo per l'utente.


NOTE: Chiavi pubbliche inviate tramite la barra degli URL in un browser con `+` vengono interpretati come segni spaziati e di interruzione.
 a| 
corda
 a| 
Nullo
 a| 
NO



 a| 
sfadmin
 a| 
Consente l'accesso all'account shell sfadmin quando si effettua la chiamata API con accesso al cluster supportAdmin o quando il nodo non si trova in un cluster.
 a| 
booleano
 a| 
Falso
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
stato_keygen
 a| 
Contiene l'identità nella chiave firmata, i principali consentiti e le date di inizio e fine valide per la chiave.
 a| 
corda



 a| 
chiave privata
 a| 
Un valore di chiave SSH privata viene restituito solo se l'API sta generando un portachiavi completo per l'utente finale.


NOTE: Il valore è codificato in Base64; è necessario decodificare il valore quando viene scritto in un file per garantire che venga letto come una chiave privata valida.
 a| 
corda



 a| 
chiave pubblica
 a| 
Un valore di chiave SSH pubblica viene restituito solo se l'API sta generando un portachiavi completo per l'utente finale.


NOTE: Quando si passa un parametro public_key al metodo API, solo il `signed_public_key` il valore viene restituito nella risposta.
 a| 
corda



 a| 
chiave pubblica firmata
 a| 
La chiave pubblica SSH risultante dalla firma della chiave pubblica, indipendentemente dal fatto che sia stata fornita dall'utente o generata tramite API.
 a| 
corda

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
    "method": "SignSshKeys",
    "params": {
        "duration": 2,
        "publicKey":<string>
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": null,
  "result": {
    "signedKeys": {
      "keygen_status": <keygen_status>,
      "signed_public_key": <signed_public_key>
    }
  }
}
----
In questo esempio, viene firmata e restituita una chiave pubblica valida per la durata (1-24 ore).



== Nuovo dalla versione

12,5
