---
permalink: api/reference_element_api_getontapversioninfo.html 
sidebar: sidebar 
keywords: ontap,version,info,information,get,getting,api,support,getontapversioninfo 
summary: 'L"interfaccia utente Web di Element utilizza GetOntapVersionInfo per ottenere informazioni sul supporto della versione API dal cluster ONTAP in una relazione SnapMirror .' 
---
= GetOntapVersionInfo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente web Element utilizza `GetOntapVersionInfo` per ottenere informazioni sul supporto della versione API dal cluster ONTAP in una relazione SnapMirror .



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
snapMirrorEndpointID
 a| 
Se specificato, il sistema elenca le informazioni sulla versione dell'endpoint con lo snapMirrorEndpointID specificato.  Se non specificato, il sistema elenca le informazioni sulla versione di tutti gli endpoint SnapMirror noti.
 a| 
intero
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
ontapVersionInfo
 a| 
Informazioni sulla versione software dell'endpoint ONTAP .
 a| 
xref:reference_element_api_ontapversioninfo.adoc[ontapVersionInfo]vettore

|===


== Nuovo dalla versione

10,1
