---
permalink: api/reference_element_api_enableclusterssh.html 
sidebar: sidebar 
keywords: SSH,enabling,enable,cluster,EnableClusterSsh 
summary: È possibile utilizzare il metodo EnableClusterSsh per abilitare il servizio SSH su tutti i nodi nel cluster di archiviazione. 
---
= AbilitaClusterSsh
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `EnableClusterSsh` metodo per abilitare il servizio SSH su tutti i nodi nel cluster di archiviazione.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
durata
 a| 
Periodo di tempo per cui il servizio SSH rimarrà abilitato.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
risultato
 a| 
Un oggetto JSON contenente lo stato del servizio SSH per il cluster di archiviazione, il tempo rimanente prima che SSH venga disabilitato e lo stato del servizio SSH per ciascun nodo.
 a| 
Oggetto JSON

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "EnableClusterSsh",
  "params": {
      "duration"  : "02:00:00.00"
  },
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Nuovo dalla versione

10,3
