---
permalink: api/reference_element_api_createkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,creating,create 
summary: 'È possibile utilizzare il metodo CreateKeyProviderKmip per creare un provider di chiavi Key Management Interoperability Protocol \(KMIP\) con il nome specificato.  Un fornitore di chiavi definisce un meccanismo e una posizione per recuperare le chiavi di autenticazione.  Quando si crea un nuovo fornitore di chiavi KMIP, non gli viene assegnato alcun server di chiavi KMIP.  Per creare un server di chiavi KMIP, utilizzare il metodo CreateKeyServerKmip.  Per assegnarlo a un provider, vedere AddKeyServerToProviderKmip.' 
---
= CreateKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `CreateKeyProviderKmip` metodo per creare un fornitore di chiavi KMIP (Key Management Interoperability Protocol) con il nome specificato.  Un fornitore di chiavi definisce un meccanismo e una posizione per recuperare le chiavi di autenticazione.  Quando si crea un nuovo fornitore di chiavi KMIP, non gli viene assegnato alcun server di chiavi KMIP.  Per creare un server di chiavi KMIP, utilizzare `CreateKeyServerKmip` metodo.  Per assegnarlo a un fornitore, vedere `AddKeyServerToProviderKmip` .



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
Nome del fornitore di chiavi
 a| 
Nome da associare al fornitore di chiavi KMIP creato.  Questo nome viene utilizzato solo a scopo di visualizzazione e non deve essere univoco.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
kmipKeyProvider
 a| 
Un oggetto contenente dettagli sul fornitore di chiavi appena creato.
 a| 
link:reference_element_api_keyproviderkmip.html["Fornitore di chiaviKmip"]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "CreateKeyProviderKmip",
  "params": {
    "keyProviderName": "ProviderName",
    },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result":
      {
    "kmipKeyProvider": {
        "keyProviderName": "ProviderName",
        "keyProviderIsActive": true,
        "kmipCapabilities": "SSL",
        "keyServerIDs": [
            15
        ],
        "keyProviderID": 1
    }
}
}
----


== Nuovo dalla versione

11,7
