---
permalink: api/reference_element_api_attributes.html 
sidebar: sidebar 
keywords: QoS,object,Quality,Service 
summary: 'Molte delle richieste e delle risposte API utilizzano sia oggetti che tipi semplici.  Gli oggetti sono una raccolta di coppie chiave-valore, in cui il valore è un tipo semplice o eventualmente un altro oggetto.  Gli attributi sono coppie nome-valore personalizzate che possono essere impostate dall"utente negli oggetti JSON.  Alcuni metodi consentono di aggiungere attributi durante la creazione o la modifica di oggetti.' 
---
= Attributi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Molte delle richieste e delle risposte API utilizzano sia oggetti che tipi semplici.  Gli oggetti sono una raccolta di coppie chiave-valore, in cui il valore è un tipo semplice o eventualmente un altro oggetto.  Gli attributi sono coppie nome-valore personalizzate che possono essere impostate dall'utente negli oggetti JSON.  Alcuni metodi consentono di aggiungere attributi durante la creazione o la modifica di oggetti.

Esiste un limite di 1000 byte per gli oggetti attributo codificati.



== Membro dell'oggetto

Questo oggetto contiene il seguente membro:

|===
| Nome | Descrizione | Tipo 


 a| 
attributi
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON

|===


== Richiedi esempio

Il seguente esempio di richiesta utilizza il metodo AddClusterAdmin:

[listing]
----
{
   "method": "AddClusterAdmin",
   "params": {
      "username": "joeadmin",
      "password": "68!5Aru268)$",
      "access": [
         "volume",
         "reporting"
      ],
      "attributes": {
         "name1": "value1",
         "name2": "value2",
         "name3": "value3"
      }
   }
}
----