---
permalink: api/reference_element_api_listkeyserverskmip.html 
sidebar: sidebar 
keywords: KMIP,key server,key,server,listing,list,listkeyserverskmip 
summary: 'È possibile utilizzare il metodo ListKeyServersKmip per elencare tutti i server delle chiavi del protocollo KMIP (Key Management Interoperability Protocol) creati.  È possibile filtrare i risultati specificando parametri aggiuntivi.' 
---
= ListKeyServersKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListKeyServersKmip` metodo per elencare tutti i server chiave KMIP (Key Management Interoperability Protocol) creati.  È possibile filtrare i risultati specificando parametri aggiuntivi.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID fornitore di chiavi
 a| 
Se specificato, il metodo restituisce solo i server delle chiavi KMIP assegnati al provider delle chiavi KMIP specificato.  Se omesso, i server delle chiavi KMIP restituiti non verranno filtrati in base al fatto che siano assegnati o meno al fornitore di chiavi KMIP specificato.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
kmipAssignedProviderIsActive
 a| 
I filtri hanno restituito oggetti server chiave KMIP in base al loro stato attivo. Valori possibili:

* true: restituisce solo i server delle chiavi KMIP attivi (che forniscono le chiavi attualmente in uso).
* false: restituisce solo i server delle chiavi KMIP inattivi (che non forniscono chiavi e possono essere eliminati).


Se omesso, i server delle chiavi KMIP restituiti non vengono filtrati in base al fatto che siano attivi o meno.
 a| 
booleano
 a| 
Nessuno
 a| 
NO



 a| 
kmipHasProviderAssigned
 a| 
I filtri hanno restituito i server delle chiavi KMIP in base all'assegnazione o meno di un fornitore di chiavi KMIP. Valori possibili:

* true: restituisce solo i server di chiavi KMIP a cui è assegnato un provider di chiavi KMIP.
* false: restituisce solo i server di chiavi KMIP a cui non è assegnato un provider di chiavi KMIP.


Se omesso, i server delle chiavi KMIP restituiti non vengono filtrati in base all'assegnazione o meno di un provider di chiavi KMIP.
 a| 
booleano
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
kmipKeyServers
 a| 
L'elenco completo dei server chiave KMIP che sono stati creati.
 a| 
link:reference_element_api_keyserverkmip.html["KeyServerKmip"]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ListKeyServersKmip",
  "params": {},
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
    "kmipKeyServers": [
        {
            "kmipKeyServerName": "keyserverName",
            "kmipClientCertificate": "dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "keyServerID": 15,
            "kmipAssignedProviderIsActive": true,
            "kmipKeyServerPort": 5696,
            "kmipCaCertificate": "MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames": [
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID": 1
        }
    ]
}
----


== Nuovo dalla versione

11,7
