---
permalink: api/reference_element_api_disableclusterssh.html 
sidebar: sidebar 
keywords: SSH,disable,disabling,cluster,DisableClusterSsh 
summary: 'È possibile utilizzare il metodo DisableClusterSsh per disabilitare il servizio SSH per l"intero cluster di archiviazione.  Quando si aggiungono nodi al cluster di archiviazione, i nuovi nodi erediteranno questa impostazione a livello di cluster.' 
---
= DisabilitaClusterSsh
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `DisableClusterSsh` metodo per disabilitare il servizio SSH per l'intero cluster di archiviazione.  Quando si aggiungono nodi al cluster di archiviazione, i nuovi nodi erediteranno questa impostazione a livello di cluster.



== Parametro

Questo metodo non ha parametri di input.



== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
risultato
 a| 
Un oggetto JSON contenente lo stato del servizio SSH per il cluster di archiviazione, il tempo rimanente prima che SSH venga disabilitato e lo stato del servizio SSH per ciascun nodo.
 a| 
Oggetto JSON

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "DisableClusterSsh",
  "params": {
      },
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
	"id": 1,
	"result" : {
    "enabled": true,
    "timeRemaining": "00:43:21",
    "nodes": [
    {
        "nodeID": 1,
        "enabled": true
    },
    {
        "nodeID": 2,
        "enabled": true
    },
    {
        "nodeID": 3,
        "enabled": false
    },
    {
        "nodeID": 4,
        "enabled": false
    } ]
			}
	}
----


== Nuovo dalla versione

10,3
