---
permalink: api/reference_element_api_snapmirrorendpoint.html 
sidebar: sidebar 
keywords: object,objects,snapMirrorEndpoint 
summary: 'L"oggetto snapMirrorEndpoint contiene informazioni sui sistemi di archiviazione SnapMirror remoti che comunicano con il cluster di archiviazione Element.  È possibile recuperare queste informazioni con il metodo API ListSnapMirrorEndpoints.' 
---
= snapMirrorEndpoint
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto snapMirrorEndpoint contiene informazioni sui sistemi di archiviazione SnapMirror remoti che comunicano con il cluster di archiviazione Element.  È possibile recuperare queste informazioni con il metodo API ListSnapMirrorEndpoints.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
snapMirrorEndpointID
 a| 
Identificatore univoco per l'oggetto nel cluster locale.
 a| 
intero



 a| 
gestioneIP
 a| 
Indirizzo IP di gestione del cluster dell'endpoint.
 a| 
corda



 a| 
Nome cluster
 a| 
Nome del cluster ONTAP .  Questo valore viene automaticamente popolato con il valore di "`clusterName`" dall'oggetto snapMirrorClusterIdentity.
 a| 
corda



 a| 
nome utente
 a| 
Nome utente di gestione per il sistema ONTAP .
 a| 
corda



 a| 
indirizzi IP
 a| 
Elenco degli indirizzi IP di archiviazione intercluster per tutti i nodi del cluster.  È possibile ottenere questi indirizzi IP con il metodo ListSnapMirrorNetworkInterfaces.
 a| 
matrice di stringhe



 a| 
è Connesso
 a| 
Lo stato di connettività del collegamento di controllo al cluster ONTAP .
 a| 
booleano

|===