---
permalink: api/reference_element_api_getkeyserverkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,getting information,retrieving 
summary: 'È possibile utilizzare il metodo GetKeyServerKmip per restituire informazioni sul server delle chiavi del protocollo di interoperabilità della gestione delle chiavi (KMIP) specificato.' 
---
= GetKeyServerKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetKeyServerKmip` metodo per restituire informazioni sul server delle chiavi KMIP (Key Management Interoperability Protocol) specificato.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID del server chiave
 a| 
ID del server delle chiavi KMIP su cui restituire informazioni.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
kmipKeyServer
 a| 
Un oggetto contenente dettagli sul server delle chiavi richiesto.
 a| 
link:reference_element_api_keyserverkmip.html["KeyServerKmip"]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "GetKeyServerKmip",
  "params": {
     "keyServerID": 15
  },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result":
      {
        "kmipKeyServer": {
            "kmipCaCertificate":"MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/E...",
            "kmipKeyServerHostnames":[
                "server1.hostname.com", "server2.hostname.com"
            ],
            "keyProviderID":1,
            "kmipKeyServerName":"keyserverName",
            "keyServerID":15
            "kmipKeyServerPort":1,
            "kmipClientCertificate":"dKkkirWmnWXbj9T/UWZYB2oK0z5...",
            "kmipAssignedProviderIsActive":true
        }
    }
}
----


== Nuovo dalla versione

11,7
