---
permalink: api/reference_element_api_listvirtualnetworks.html 
sidebar: sidebar 
keywords: virtual,network,networks,listing,list,listvirtualnetworks 
summary: È possibile utilizzare il metodo ListVirtualNetworks per elencare tutte le reti virtuali configurate per il cluster. 
---
= ElencoRetiVirtuali
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListVirtualNetworks` metodo per elencare tutte le reti virtuali configurate per il cluster.

È possibile utilizzare questo metodo per verificare le impostazioni della rete virtuale nel cluster.  Per questo metodo non sono richiesti parametri.  Tuttavia, per filtrare i risultati, è possibile passare uno o più valori virtualNetworkID o virtualNetworkTag.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID di rete virtuale
 a| 
ID di rete per filtrare l'elenco per una singola rete virtuale.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
virtualNetworkTag
 a| 
Tag di rete per filtrare l'elenco per una singola rete virtuale.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
ID di rete virtuali
 a| 
ID di rete da includere nell'elenco.
 a| 
array di interi
 a| 
Nessuno
 a| 
NO



 a| 
virtualNetworkTags
 a| 
Tag di rete da includere nell'elenco.
 a| 
array di interi
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
reti virtuali
 a| 
Oggetto contenente indirizzi IP di reti virtuali.
 a| 
xref:reference_element_api_virtualnetwork.adoc[rete virtuale]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ListVirtualNetworks",
  "params": {
     "virtualNetworkIDs": [5,6]
   },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "virtualNetworks": [
   {
    "addressBlocks": [
   {
    "available": "11000000",
    "size": 8,
    "start": "10.26.250.207"
   }
 ],
    "attributes": null,
    "gateway": "10.26.250.254",
    "name": "2250",
    "namespace": false,
    "netmask": "255.255.255.0",
    "svip": "10.26.250.200",
    "virtualNetworkID": 2250
   },
   {
     "addressBlocks": [
   {
     "available": "11000000",
     "size": 8,
     "start": "10.26.241.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.241.254",
     "name": "2241",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.241.200",
     "virtualNetworkID": 2241
   },
  {
     "addressBlocks": [
  {
     "available": "11000000",
     "size": 8,
     "start": "10.26.240.207"
   }
  ],
     "attributes": null,
     "gateway": "10.26.240.254",
     "name": "2240",
     "namespace": false,
     "netmask": "255.255.255.0",
     "svip": "10.26.240.200",
     "virtualNetworkID": 2240
    },
   {
  }
 ]
}
----


== Nuovo dalla versione

9,6
