---
permalink: api/reference_element_api_getipmiconfig.html 
sidebar: sidebar 
keywords: hardware,sensor,config,configuration,get,getting,getipmiconfig 
summary: È possibile utilizzare il metodo GetIpmiConfig per recuperare informazioni sui sensori hardware dai sensori presenti nel nodo. 
---
= OttieniIpmiConfig
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetIpmiConfig` metodo per recuperare informazioni sui sensori hardware dai sensori presenti nel nodo.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo 


 a| 
tipo di telaio
 a| 
Utilizzato per visualizzare informazioni per ciascun tipo di chassis del nodo. Valori possibili:

* all: restituisce informazioni sui sensori per ogni tipo di telaio.
* {tipo di telaio}: restituisce informazioni sul sensore per un tipo di telaio specificato.

 a| 
corda

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
Nome del sensore
 a| 
Nome del sensore trovato.
 a| 
corda



 a| 
ID sensore univoco
 a| 
Identificatore univoco del sensore.
 a| 
corda

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "GetIpmiConfig",
  "params": {
     "chassisType"; "all"
     },
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
 "id": 1,
   "result": {
     "nodes": [
         {
           "nodeID": 1,
           "result": {
             "ipmiConfig": {
                "C220M4": [
                    {
                     "sensorName": "Fan1A RPM",
                     "uniqueSensorID": "29.1:0xf"
                    },
                    {
                      "sensorName": "Fan1B RPM",
                      "uniqueSensorID": "29.1:0x10"
                    },
                    {
                      "sensorName": "Fan2A RPM",
                      "uniqueSensorID": "29.2:0x11"
                    },
                    {
                      "sensorName": "Fan2B RPM",
                      "uniqueSensorID": "29.2:0x12"
                    },
                    {
                      "sensorName": "Fan3A RPM",
                      "uniqueSensorID": "29.3:0x13"
                    },
                    {
                      "sensorName": "Fan3B RPM",
                      "uniqueSensorID": "29.3:0x14"
                    },
                    {
                      "sensorName": "Fan4A RPM",
                      "uniqueSensorID": "29.4:0x15"
                    },
                    {
                      "sensorName": "Fan4B RPM",
                      "uniqueSensorID": "29.4:0x16"
                    },
                    {
                      "sensorName": "Fan5A RPM",
                      "uniqueSensorID": "29.5:0x17"
                    },
                    {
                      "sensorName": "Fan5B RPM",
                      "uniqueSensorID": "29.5:0x18"
                    },
                    {
                      "sensorName": "Fan6A RPM",
                      "uniqueSensorID": "29.6:0x19"
                    },
                    {
                      "sensorName": "Fan6B RPM",
                      "uniqueSensorID": "29.6:0x1a"
                    },
                    {
                      "sensorName": "Exhaust Temp",
                      "uniqueSensorID": "7.1:0x1"
                    },
                    {
                      "sensorName": "Inlet Temp",
                      "uniqueSensorID": "7.1:0x4"
                    },
                    {
                      "sensorName": "PS1",
                      "uniqueSensorID": "10.1:0x26"
                    },
                    {
                      "sensorName": "PS2",
                      "uniqueSensorID": "10.2:0x2c"
                    }
                ],
                "R620": [
                    {
                      "sensorName": "Fan1A RPM",
                      "uniqueSensorID": "7.1:0x30"
                    },
                    {
                      "sensorName": "Fan1B RPM",
                      "uniqueSensorID": "7.1:0x31"
                    },
                    {
                      "sensorName": "Fan2A RPM",
                      "uniqueSensorID": "7.1:0x32"
                    },
                    {
                      "sensorName": "Fan2B RPM",
                      "uniqueSensorID": "7.1:0x33"
                    },
                    {
                      "sensorName": "Fan3A RPM",
                      "uniqueSensorID": "7.1:0x34"
                    },
                    {
                      "sensorName": "Fan3B RPM",
                      "uniqueSensorID": "7.1:0x35"
                    },
                    {
                      "sensorName": "Fan4A RPM",
                      "uniqueSensorID": "7.1:0x36"
                    },
                    {
                      "sensorName": "Fan4B RPM",
                      "uniqueSensorID": "7.1:0x37"
                    },
                    {
                      "sensorName": "Fan5A RPM",
                      "uniqueSensorID": "7.1:0x38"
                    },
                    {
                      "sensorName": "Fan5B RPM",
                      "uniqueSensorID": "7.1:0x39"
                    },
                    {
                      "sensorName": "Fan6A RPM",
                      "uniqueSensorID": "7.1:0x3a"
                    },
                    {
                      "sensorName": "Fan6B RPM",
                      "uniqueSensorID": "7.1:0x3b"
                    },
                    {
                      "sensorName": "Fan7A RPM",
                      "uniqueSensorID": "7.1:0x3c"
                    },
                    {
                      "sensorName": "Fan7B RPM",
                      "uniqueSensorID": "7.1:0x3d"
                    },
                    {
                      "sensorName": "Exhaust Temp",
                      "uniqueSensorID": "7.1:0x1"
                    },
                    {
                      "sensorName": "Inlet Temp",
                      "uniqueSensorID": "7.1:0x4"
                    },
                    {
                      "sensorName": "PS1",
                      "uniqueSensorID": "10.1:0x62"
                    },
                    {
                      "sensorName": "PS2",
                      "uniqueSensorID": "10.2:0x63"
                    }
               ],
          }
----


== Nuovo dalla versione

9,6
