---
permalink: api/reference_element_api_protectiondomainresiliency.html 
sidebar: sidebar 
keywords: object,objects,protectionDomainResiliency 
summary: 'L"oggetto protectionDomainResiliency contiene lo stato di resilienza di questo cluster di archiviazione.  La resilienza indica la capacità del cluster di storage di ripristinarsi automaticamente da uno o più guasti, tutti all"interno di un singolo dominio di protezione del tipo di dominio di protezione associato.  Un cluster di storage è considerato ripristinato quando può continuare a leggere e scrivere dati nonostante il guasto di un singolo nodo di storage (uno stato noto come tolleranza del nodo).' 
---
= protezioneDomainResiliency
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto protectionDomainResiliency contiene lo stato di resilienza di questo cluster di archiviazione.  La resilienza indica la capacità del cluster di storage di ripristinarsi automaticamente da uno o più guasti, tutti all'interno di un singolo dominio di protezione del tipo di dominio di protezione associato.  Un cluster di storage è considerato ripristinato quando può continuare a leggere e scrivere dati nonostante il guasto di un singolo nodo di storage (uno stato noto come tolleranza del nodo).



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
schema di protezioneResilienze
 a| 
Un elenco di oggetti (uno per ogni schema di protezione) contenente informazioni sulla resilienza ai guasti per il tipo di dominio di protezione associato.
 a| 
xref:reference_element_api_protectionschemeresiliency.adoc[schema di protezioneResilienza]vettore



 a| 
singleFailureThresholdBytesForBlockData
 a| 
Numero massimo di byte che possono essere archiviati nel cluster di archiviazione prima di perdere la capacità di ripristinare automaticamente uno stato di tolleranza del nodo.
 a| 
intero



 a| 
GuastisostenibiliPerInsieme
 a| 
Numero previsto di guasti simultanei che possono verificarsi senza perdere la capacità di ripristinare automaticamente uno stato di tolleranza del nodo per il quorum dell'ensemble.
 a| 
intero

|===