---
permalink: api/reference_element_api_listsnapshots.html 
sidebar: sidebar 
keywords: snapshot,snapshots,list,listing,attributes,listsnapshots 
summary: È possibile utilizzare ListSnapshots per restituire gli attributi di ogni snapshot acquisito sul volume. 
---
= ListSnapshots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare `ListSnapshots` per restituire gli attributi di ogni snapshot acquisito sul volume.

Le informazioni sugli snapshot che risiedono nel cluster di destinazione verranno visualizzate nel cluster di origine quando questo metodo viene chiamato dal cluster di origine.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID volume
 a| 
Recupera gli snapshot per un volume.  Se volumeID non viene fornito, vengono restituiti tutti gli snapshot per tutti i volumi.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
ID istantanea
 a| 
Recupera informazioni per un singolo ID snapshot.
 a| 
intero
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
istantanee
 a| 
Informazioni su ogni snapshot per ogni volume.  Se volumeID non viene fornito, vengono restituiti tutti gli snapshot per tutti i volumi.  Gli snapshot che si trovano in un gruppo vengono restituiti con un ID gruppo.
 a| 
xref:reference_element_api_snapshot.adoc[istantanea]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ListSnapshots",
   "params": {
             "volumeID": "1"
       },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "snapshots": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2015-05-08T13:15:00Z",
          "enableRemoteReplication": true,
          "expirationReason": "None",
          "expirationTime": "2015-05-08T21:15:00Z",
          "groupID": 0,
          "groupSnapshotUUID": "00000000-0000-0000-0000-000000000000",
          "name": "Hourly",
          "remoteStatuses": [
              {
                "remoteStatus": "Present",
                "volumePairUUID": "237e1cf9-fb4a-49de-a089-a6a9a1f0361e"
              }
         ],
          "snapshotID": 572,
          "snapshotUUID": "efa98e40-cb36-4c20-a090-a36c48296c14",
          "status": "done",
          "totalSize": 10000269312,
          "volumeID": 1
        }
      ]
    }
  }
----


== Nuovo dalla versione

9,6
