---
permalink: api/reference_element_api_copyvolume.html 
sidebar: sidebar 
keywords: volume,volumes,CopyVolume,overwrite,overwriting,data 
summary: 'È possibile utilizzare il metodo CopyVolume per sovrascrivere il contenuto dei dati di un volume esistente con il contenuto dei dati di un altro volume \(o snapshot\).  Gli attributi del volume di destinazione, quali IQN, impostazioni QoS, dimensioni, account e appartenenza al gruppo di accesso al volume, non vengono modificati.  Il volume di destinazione deve già esistere e avere le stesse dimensioni del volume di origine.' 
---
= CopiaVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `CopyVolume` metodo per sovrascrivere il contenuto dei dati di un volume esistente con il contenuto dei dati di un altro volume (o snapshot).  Gli attributi del volume di destinazione, quali IQN, impostazioni QoS, dimensioni, account e appartenenza al gruppo di accesso al volume, non vengono modificati.  Il volume di destinazione deve già esistere e avere le stesse dimensioni del volume di origine.

È preferibile che i client smontino il volume di destinazione prima che l'operazione abbia inizio.  Se il volume di destinazione viene modificato durante l'operazione, le modifiche andranno perse.  Questa operazione può richiedere un tempo variabile per essere completata.  Puoi usare ilxref:reference_element_api_getasyncresult.adoc[Ottieni risultato asincrono] metodo per determinare quando il processo è terminato, exref:reference_element_api_listsyncjobs.adoc[ListSyncJobs] per vedere l'avanzamento della copia.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
dstVolumeID
 a| 
VolumeID del volume da sovrascrivere.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
ID volume
 a| 
VolumeID del volume da cui leggere.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
ID istantanea
 a| 
ID dello snapshot utilizzato come origine del clone.  Se non viene fornito alcun ID, viene utilizzato il volume attivo corrente.
 a| 
intero
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
asyncHandle
 a| 
Valore handle utilizzato per ottenere il risultato dell'operazione.
 a| 
intero



 a| 
cloneID
 a| 
CloneID per il volume appena clonato.
 a| 
intero

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "CopyVolume",
   "params": {
      "volumeID" : 3,
      "dstVolumeID" : 2
   },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "asyncHandle": 9,
    "cloneID": 5
  }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

* xref:reference_element_api_getasyncresult.adoc[Ottieni risultato asincrono]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]

