---
permalink: api/reference_element_api_getnetworkconfig.html 
sidebar: sidebar 
keywords: network,config,configuration,get,getting,getnetworkconfig 
summary: È possibile utilizzare il metodo GetNetworkConfig per visualizzare le informazioni sulla configurazione di rete per un nodo. 
---
= OttieniConfigurazione di rete
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetNetworkConfig` metodo per visualizzare le informazioni sulla configurazione di rete per un nodo.



== Parametri

Questo metodo non ha parametri di input.



== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
rete
 a| 
Tipi di connessione di rete e impostazioni correnti per ciascuna interfaccia di rete del nodo.
 a| 
xref:reference_element_api_network_all_interfaces.adoc[rete (tutte le interfacce)]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "GetNetworkConfig",
   "params": {},
   "id" : 1
}
----


== Esempio di risposta

Data la lunghezza di questo esempio di risposta, esso è documentato in un argomento supplementare.



== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_response_example_getnetworkconfig.adoc[OttieniConfigurazione di rete]
