---
permalink: api/reference_element_api_testkeyproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key provider,testing,test 
summary: 'È possibile utilizzare il metodo TestKeyProviderKmip per verificare se il provider di chiavi Key Management Interoperability Protocol (KMIP) specificato è raggiungibile e funziona normalmente.' 
---
= TestKeyProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `TestKeyProviderKmip` metodo per verificare se il fornitore di chiavi KMIP (Key Management Interoperability Protocol) specificato è raggiungibile e funziona normalmente.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID fornitore di chiavi
 a| 
L'ID del fornitore della chiave da testare.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo non ha valori di ritorno.  Il test è considerato riuscito finché non viene restituito alcun errore.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "TestKeyProviderKmip",
  "params": {
    "keyProviderID": 15
  },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


== Nuovo dalla versione

11,7
