---
permalink: api/reference_element_api_getfipsreport.html 
sidebar: sidebar 
keywords: fips,report,get,getting,getfipsreport,feature,support 
summary: È possibile utilizzare il metodo GetFipsReport per verificare lo stato di supporto della funzionalità di crittografia FIPS 140-2 di tutti i nodi nel cluster di archiviazione. 
---
= OttieniFipsReport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetFipsReport` metodo per verificare lo stato di supporto della funzionalità di crittografia FIPS 140-2 di tutti i nodi nel cluster di archiviazione.



== Parametro

Questo metodo non ha parametri di input.



== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
risultato
 a| 
Un oggetto JSON contenente lo stato del supporto delle funzionalità FIPS 140-2 per ogni nodo e informazioni di errore per ogni nodo che non ha risposto alla query.
 a| 
xref:reference_element_api_fipsreport.adoc[fipsReport]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "GetFipsReport",
  "params": {},
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
    "id": 1,
    "result": {
    "nodes": [
        {
           "nodeID": 1,
		   "fipsDrives": "None",
           "httpsEnabled": true
        },
        {
           "nodeID": 3,
		   "fipsDrives": "None",
           "httpsEnabled": true
        }
    ],
    "errorNodes": [
        {
           "nodeID": 2,
           "error": {
               "message": "The RPC timed out.",
               "name": "xRpcTimeout"
               }
        }
    ]
    }
}
----


== Nuovo dalla versione

10,3
