---
permalink: api/reference_element_api_getpatchinfo.html 
sidebar: sidebar 
keywords: get,patch,info,patches,getpatchinfo 
summary: È possibile utilizzare il metodo GetPatchInfo per ottenere informazioni sulle patch installate su un nodo. 
---
= Ottieni informazioni sulla patch
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetPatchInfo` metodo per ottenere informazioni sulle patch software Element installate su un nodo di archiviazione.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


| `force`  a| 
Forza l'esecuzione del metodo su tutti i nodi nel cluster di archiviazione.  Questa operazione è necessaria solo quando si invia l'API a un indirizzo IP del cluster anziché a un singolo nodo. Valori possibili:

* `true`
* `false`

| booleano | `false` | NO 
|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


| patch | Oggetto contenente informazioni sulle patch installate su questo nodo. | Oggetto JSON 
|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "GetPatchInfo",
   "params": {
      "force": false,
      },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
    "id": 1,
    "result": {
        "patches": {
          "SUST936": {
          "date": "Wed 09 Dec 2020 10:41:59 PM UTC",
          "description": "BMC fixes",
          "newFiles": [
              "None"
          ],
          "patchedFiles": [
              "Patched_file_1.bin",
              "Patched_file_2.dat",
              "Patched_file_3.tgz"
          ]
          }
        }
    }
}

----


== Nuovo dalla versione

12,3
