---
permalink: api/reference_element_api_purgedeletedvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,purge,purging,multiple,deleted,purgedeletedvolumes 
summary: È possibile utilizzare il metodo PurgeDeletedVolumes per eliminare immediatamente e definitivamente i volumi eliminati; è possibile utilizzare questo metodo per eliminare fino a 500 volumi contemporaneamente. 
---
= Elimina i volumi eliminati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `PurgeDeletedVolumes` Metodo per eliminare immediatamente e definitivamente i volumi eliminati; è possibile utilizzare questo metodo per eliminare fino a 500 volumi contemporaneamente.

È necessario eliminare i volumi utilizzando `DeleteVolumes` prima che possano essere eliminati.  I volumi vengono eliminati automaticamente dopo un certo periodo di tempo, pertanto in genere non è necessario utilizzare questo metodo.


NOTE: Se si eliminano contemporaneamente un gran numero di volumi o se ai volumi eliminati sono associati molti snapshot, il metodo potrebbe non funzionare e restituire l'errore "xDBConnectionLoss".  In tal caso, riprovare la chiamata al metodo con un numero inferiore di volumi.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


| volumeID | Un elenco di volumi ID da eliminare dal sistema. | array di interi | NO | NO 


| ID account | Un elenco di ID account.  Tutti i volumi di tutti gli account specificati vengono eliminati dal sistema. | array di interi | NO | NO 


| volumeAccessGroupIDs | Un elenco di volumeAccessGroupID.  Tutti i volumi di tutti i gruppi di accesso ai volumi specificati vengono eliminati dal sistema. | array di interi | NO | NO 
|===
*Nota:* è possibile specificare solo uno dei parametri sopra indicati per ogni chiamata al metodo.  Specificarne più di uno, o nessuno, genera un errore.



== Valori di ritorno

Questo metodo non ha valori di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "PurgeDeletedVolumes",
   "params": {
      "accountIDs" : [1, 2, 3]
   },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id" : 1,
  "result": {}
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_deletevolumes.adoc[EliminaVolumi]
