---
permalink: api/reference_element_api_deleteclusterinterfacepreference.html 
sidebar: sidebar 
keywords: cluster,interface,preferences,delete,deleting,DeleteClusterInterfacePreference 
summary: Il metodo DeleteClusterInterfacePreference consente ai sistemi integrati con cluster di archiviazione che eseguono il software Element di eliminare una preferenza di interfaccia cluster esistente.  Questo metodo è per uso interno. 
---
= DeleteClusterInterfacePreference
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IL `DeleteClusterInterfacePreference` Il metodo consente ai sistemi integrati con cluster di archiviazione che eseguono il software Element di eliminare una preferenza di interfaccia cluster esistente.  Questo metodo è per uso interno.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
nome
 a| 
Nome della preferenza dell'interfaccia del cluster da eliminare.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo non ha valore di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
	"method": "DeleteClusterInterfacePreference",
	"params": {
		"name": "prefname"
		},
	"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
    "id": 1,
    "result": {}
}
----


== Nuovo dalla versione

11,0
