---
permalink: api/reference_element_api_listpendingnodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,pending,nodes,node,listpendingnodes 
summary: È possibile utilizzare il metodo ListPendingNodes per elencare i nodi di archiviazione in sospeso nel sistema.  I nodi in sospeso sono nodi di archiviazione in esecuzione e configurati per unirsi al cluster di archiviazione, ma che non sono ancora stati aggiunti tramite il metodo API AddNodes. 
---
= Elenco nodi in sospeso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListPendingNodes` metodo per elencare i nodi di archiviazione in sospeso nel sistema.  I nodi in sospeso sono nodi di archiviazione in esecuzione e configurati per unirsi al cluster di archiviazione, ma che non sono ancora stati aggiunti tramite il metodo API AddNodes.



== Indirizzi di gestione IPv4 e IPv6

Notare che `ListPendingNodes` non elenca i nodi in sospeso che hanno tipi di indirizzo diversi per l'indirizzo IP di gestione (MIP) e l'indirizzo IP virtuale di gestione (MVIP).  Ad esempio, se un nodo in sospeso ha un MVIP IPv6 e un MIP IPv4, `ListPendingNodes` non includerà il nodo come parte del risultato.



== Parametri

Questo metodo non ha parametri di input.



== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
nodi in sospeso
 a| 
Elenco dei nodi in sospeso nel cluster.
 a| 
xref:reference_element_api_pendingnode.adoc[nodo in sospeso]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ListPendingNodes",
   "params": {},
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 3,
  "result": {
    "pendingNodes": [
      {
        "assignedNodeID": 0,
        "cip": "10.26.65.101",
        "cipi": "Bond10G",
        "compatible": true,
        "mip": "172.26.65.101",
        "mipi": "Bond1G",
        "name": "VWC-EN101",
        "pendingNodeID": 1,
        "platformInfo": {
          "chassisType": "R620",
          "cpuModel": "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
          "nodeMemoryGB": 72,
          "nodeType": "SF3010"
        },
        "sip": "10.26.65.101",
        "sipi": "Bond10G",
        "softwareVersion": "9.0.0.1554",
        "uuid": "4C4C4544-0048-4410-8056-C7C04F395931"
      }
    ]
  }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_addnodes.adoc[Aggiungi nodi]
