---
permalink: api/reference_element_api_setnodesupplementaltlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,set,setting,list,supplemental,setnodesupplementaltlsciphers,node 
summary: 'È possibile utilizzare il metodo SetNodeSupplementalTlsCiphers per specificare l"elenco dei cifrari TLS supplementari.  È possibile utilizzare questo comando sui nodi di gestione.' 
---
= SetNodeSupplementalTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `SetNodeSupplementalTlsCiphers` metodo per specificare l'elenco dei cifrari TLS supplementari.  È possibile utilizzare questo comando sui nodi di gestione.



== Parametro


NOTE: È necessario chiamare questo metodo sul nodo di gestione. Per esempio:

[listing]
----
https://<management node IP>:442/json-rpc/10.0
----
Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
Cifrari supplementari
 a| 
I nomi delle suite di cifratura supplementari utilizzano lo schema di denominazione OpenSSL.  L'uso dei nomi delle suite di cifratura non distingue tra maiuscole e minuscole.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
Cifrari obbligatori
 a| 
Elenco delle suite di cifratura TLS obbligatorie per il nodo.  Si tratta di cifrari sempre attivi sul nodo.
 a| 
corda



 a| 
Cifrari supplementari
 a| 
Elenco delle suite di cifratura TLS supplementari per il nodo.
 a| 
corda

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "SetNodeSupplementalTlsCiphers",
   "params": {
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id" : 1,
  "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----