---
permalink: api/reference_element_api_getclusterstate.html 
sidebar: sidebar 
keywords: cluster,state,getting,get,getclusterstate 
summary: È possibile utilizzare il metodo API GetClusterState per indicare se un nodo fa parte di un cluster oppure no. 
---
= Ottieni stato cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetClusterState` Metodo API per indicare se un nodo fa parte di un cluster oppure no.



== Parametri

Questo metodo non ha parametri di input.



== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
grappolo
 a| 
Nome del cluster.
 a| 
corda



 a| 
stato
 a| 
* Disponibile: il nodo non è stato configurato con un nome cluster.
* In sospeso: il nodo è in sospeso per un cluster denominato specifico e può essere aggiunto.
* Attivo: il nodo è un membro attivo di un cluster e non può essere aggiunto a un altro cluster.

 a| 
corda

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "GetClusterState",
   "params": {},
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id" : 1,
   "result" :
      "cluster" :  "Cluster101"
      "state" : "Active"
}
----


== Nuovo dalla versione

9,6
