---
permalink: api/reference_element_api_getdrivestats.html 
sidebar: sidebar 
keywords: drive,drives,stats,get,getting,getdrivestats 
summary: 'È possibile utilizzare il metodo GetDriveStats per ottenere misurazioni di attività di alto livello per una singola unità.  I valori sono cumulativi a partire dall"aggiunta dell"unità al cluster.  Alcuni valori sono specifici delle unità a blocchi.  Quando si esegue questo metodo, vengono restituiti dati statistici per i tipi di unità a blocchi o a metadati.' 
---
= Ottieni statistiche di guida
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetDriveStats` metodo per ottenere misurazioni di attività di alto livello per una singola unità.  I valori sono cumulativi a partire dall'aggiunta dell'unità al cluster.  Alcuni valori sono specifici delle unità a blocchi.  Quando si esegue questo metodo, vengono restituiti dati statistici per i tipi di unità a blocchi o a metadati.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID unità
 a| 
ID dell'unità per la richiesta.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
Statistiche di guida
 a| 
Informazioni sull'attività dell'unità per il driveID specificato.
 a| 
xref:reference_element_api_drivestats.adoc[Statistiche di guida]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "GetDriveStats",
   "params": {
     "driveID": 3
   },
   "id" : 1
}
----


== Esempio di risposta (blocco unità)

Questo metodo restituisce una risposta simile al seguente esempio per un'unità a blocchi:

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": {
      "driveID": 10,
      "failedDieCount": 0,
      "lifeRemainingPercent": 99,
      "lifetimeReadBytes": 26471661830144,
      "lifetimeWriteBytes": 13863852441600,
      "powerOnHours": 33684,
      "readBytes": 10600432105,
      "readOps": 5101025,
      "reallocatedSectors": 0,
      "reserveCapacityPercent": 100,
      "timestamp": "2016-10-17T20:23:45.456834Z",
      "totalCapacity": 300069052416,
      "usedCapacity": 6112226545,
      "usedMemory": 114503680,
      "writeBytes": 53559500896,
      "writeOps": 25773919
    }
  }
}
----


== Esempio di risposta (unità metadati del volume)

Questo metodo restituisce una risposta simile al seguente esempio per un'unità metadati del volume:

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": {
      "activeSessions": 8,
      "driveID": 12,
      "failedDieCount": 0,
      "lifeRemainingPercent": 100,
      "lifetimeReadBytes": 2308544921600,
      "lifetimeWriteBytes": 1120986464256,
      "powerOnHours": 16316,
      "readBytes": 1060152152064,
      "readOps": 258826209,
      "reallocatedSectors": 0,
      "reserveCapacityPercent": 100,
      "timestamp": "2016-10-17T20:34:52.456130Z",
      "totalCapacity": 134994670387,
      "usedCapacity": null,
      "usedMemory": 22173577216,
      "writeBytes": 353346510848,
      "writeOps": 86266238
    }
  }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_listdrives.adoc[ListDrives]
