---
permalink: api/reference_element_api_listsyncjobs.html 
sidebar: sidebar 
keywords: sync,synchronization,job,jobs,list,get,listing,getting,listsyncjobs 
summary: È possibile utilizzare il metodo ListSyncJobs per ottenere informazioni sui processi di sincronizzazione in esecuzione su un cluster di archiviazione Element.  Questo metodo restituisce informazioni sui processi di sincronizzazione slice, clone, block e remote. 
---
= ListSyncJobs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListSyncJobs` metodo per ottenere informazioni sui processi di sincronizzazione in esecuzione su un cluster di archiviazione Element.  Questo metodo restituisce informazioni sui processi di sincronizzazione slice, clone, block e remote.



== Parametri

Questo metodo non ha parametri di input.



== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
syncJobs
 a| 
Elenco di oggetti che descrivono i processi di sincronizzazione attualmente in esecuzione nel sistema.
 a| 
xref:reference_element_api_syncjob.adoc[sincronizzazioneJob]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ListSyncJobs",
   "params": { },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
    "id":1,
    "result":{
      "syncJobs":[
        {
           "bytesPerSecond":275314.8834458956,
           "currentBytes":178257920,
           "dstServiceID":36,
           "elapsedTime":289.4568382049871,
           "percentComplete":8.900523560209423,
           "remainingTime":2962.675921065957,
           "sliceID":5,
           "srcServiceID":16,
           "stage":"whole",
           "totalBytes":2002780160,
           "type":"slice"
       },
       {
           "bytesPerSecond":305461.3198607744,
           "cloneID":1,
           "currentBytes":81788928,
           "dstServiceID":16,
           "dstVolumeID":6,
           "elapsedTime":291.7847648200743,
           "nodeID":1,
           "percentComplete":8.167539267015707,
           "remainingTime":3280.708270981153,
           "sliceID":6,
           "srcServiceID":16,
           "srcVolumeID":5,
           "stage":"whole",
           "totalBytes":1001390080,
           "type":"clone"
        },
        {
           "blocksPerSecond":0,
           "branchType": "snapshot",
           "dstServiceID":8,
           "dstVolumeID":2,
           "elapsedTime":0,
           "percentComplete":0,
           "remainingTime":0,
           "sliceID":2,
           "stage":"metadata",
           "type":"remote"
       }
     ]
   }
}
----


== Nuovo dalla versione

9,6
