---
permalink: api/reference_element_api_modifyinitiators.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,initiators,initiator,attribute,attributes,modifyinitiators 
summary: È possibile utilizzare il metodo ModifyInitiators per modificare gli attributi di uno o più iniziatori esistenti. 
---
= ModificaIniziatori
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ModifyInitiators` metodo per modificare gli attributi di uno o più iniziatori esistenti.

Non è possibile modificare il nome di un iniziatore esistente.  Se è necessario modificare il nome di un iniziatore, eliminarlo prima con ilxref:reference_element_api_deleteinitiators.adoc[EliminaIniziatori] metodo e crearne uno nuovo con ilxref:reference_element_api_createinitiators.adoc[CreaIniziatori] metodo.

Se ModifyInitiators non riesce a modificare uno degli iniziatori forniti nel parametro, il metodo restituisce un errore e non modifica alcun iniziatore (non è possibile alcun completamento parziale).



== Parametro

Questo metodo ha il seguente parametro di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
iniziatori
 a| 
Un elenco di oggetti contenente le caratteristiche di ciascun iniziatore da modificare.  Possibili oggetti:

* `alias`: (Facoltativo) Un nuovo nome descrittivo da assegnare all'iniziatore.  (corda)
* `attributes`: (Facoltativo) Un nuovo set di attributi JSON da assegnare all'iniziatore.  (oggetto JSON)
* `chapUsername`: (Facoltativo) Un nuovo nome utente CHAP univoco per questo iniziatore.  (corda)
* `forceDuringUpgrade`: Completa la modifica dell'iniziatore durante un aggiornamento.
* `initiatorID`: (Obbligatorio) L'ID dell'iniziatore da modificare.  (numero intero)
* `initiatorSecret`: (Facoltativo) Un nuovo segreto CHAP utilizzato per autenticare l'iniziatore.  (corda)
* `requireChap`: (Facoltativo) Vero se CHAP è richiesto per questo iniziatore.  (booleano)
* `targetSecret`: (Facoltativo) Un nuovo segreto CHAP utilizzato per autenticare la destinazione (quando si utilizza l'autenticazione CHAP reciproca).  (corda)
* `virtualNetworkIDs`: (Facoltativo) L'elenco degli identificatori di rete virtuale associati a questo iniziatore.  Se si definiscono una o più reti virtuali, questo iniziatore potrà accedere solo a tali reti virtuali.  Se non si definisce alcuna rete virtuale, questo iniziatore può accedere a tutte le reti.
* `volumeAccessGroupID`: (Facoltativo) ID del gruppo di accesso al volume a cui deve essere aggiunto l'iniziatore.  Se l'iniziatore si trovava in precedenza in un gruppo di accesso al volume diverso, viene rimosso dal vecchio gruppo di accesso al volume.  Se questa chiave è presente ma è nulla, l'iniziatore viene rimosso dal suo attuale gruppo di accesso al volume, ma non viene inserito in nessun nuovo gruppo di accesso al volume.  (numero intero)

 a| 
Matrice di oggetti JSON
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
iniziatori
 a| 
Elenco di oggetti che descrivono gli iniziatori appena modificati.
 a| 
xref:reference_element_api_initiator.adoc[iniziatore]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "id": 6683,
  "method": "ModifyInitiators",
  "params": {
    "initiators": [
      {
        "initiatorID": 2,
        "alias": "alias1",
        "volumeAccessGroupID": null
      },
      {
        "initiatorID": 3,
        "alias": "alias2",
        "volumeAccessGroupID": 1
      }
    ]
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 6683,
  "result": {
    "initiators": [
      {
        "alias": "alias1",
        "attributes": {},
        "initiatorID": 2,
        "initiatorName": "iqn.1993-08.org.debian:01:395543635",
        "volumeAccessGroups": []
      },
      {
        "alias": "alias2",
        "attributes": {},
        "initiatorID": 3,
        "initiatorName": "iqn.1993-08.org.debian:01:935573135",
        "volumeAccessGroups": [
          1
        ]
      }
    ]
  }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

* xref:reference_element_api_createinitiators.adoc[CreaIniziatori]
* xref:reference_element_api_deleteinitiators.adoc[EliminaIniziatori]

