---
permalink: api/reference_element_api_listprotectiondomainlevels.html 
sidebar: sidebar 
keywords: list,listing,protection,domain,levels,level,listprotectiondomainlevels 
summary: È possibile utilizzare il metodo ListProtectionDomainLevels per elencare i livelli di tolleranza e resilienza del cluster di archiviazione.  I livelli di tolleranza indicano la capacità del cluster di continuare a leggere e scrivere dati in caso di guasto, mentre i livelli di resilienza indicano la capacità del cluster di storage di ripristinarsi automaticamente in seguito a uno o più guasti. 
---
= ListProtectionDomainLevels
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListProtectionDomainLevels` metodo per elencare i livelli di tolleranza e resilienza del cluster di archiviazione.  I livelli di tolleranza indicano la capacità del cluster di continuare a leggere e scrivere dati in caso di guasto, mentre i livelli di resilienza indicano la capacità del cluster di storage di ripristinarsi automaticamente in seguito a uno o più guasti.



== Parametro

Questo metodo non ha parametri di input.



== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
protectionDomainLevels
 a| 
Un elenco dei diversi livelli di dominio di protezione, ognuno dei quali fornisce informazioni sulla tolleranza e la resilienza del cluster di archiviazione.
 a| 
xref:reference_element_api_protectiondomainlevel.adoc[protezioneDomainLevel]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ListProtectionDomainLevels",
  "params": {},
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
	"id": 1,
	"result": {
		"protectionDomainLevels": [
			{
				"protectionDomainType": "node",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			},
			{
				"protectionDomainType": "chassis",
				"resiliency": {
					"protectionSchemeResiliencies": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"singleFailureThresholdBytesForBlockData": 0,
					"sustainableFailuresForEnsemble": 1
				},
				"tolerance": {
					"protectionSchemeTolerances": [
							{
								"protectionScheme": "doubleHelix",
								"sustainableFailuresForBlockData": 0,
								"sustainableFailuresForMetadata": 1
							}
					],
					"sustainableFailuresForEnsemble": 1
				}
			}
		]
	}
}
----


== Nuovo dalla versione

11,0
