---
permalink: api/reference_element_api_disableencryptionatrest.html 
sidebar: sidebar 
keywords: element, api, encryption, disable, disabling, at rest, rest, DisableEncryptionAtRest 
summary: È possibile utilizzare il metodo DisableEncryptionAtRest per rimuovere la crittografia precedentemente applicata al cluster tramite il metodo EnableEncryptionAtRest.  Questo metodo di disattivazione è asincrono e restituisce una risposta prima che la crittografia venga disabilitata.  È possibile utilizzare il metodo GetClusterInfo per interrogare il sistema e verificare quando il processo è stato completato. 
---
= Disabilita la crittografia a riposo
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `DisableEncryptionAtRest` metodo per rimuovere la crittografia precedentemente applicata al cluster utilizzando `EnableEncryptionAtRest` metodo.  Questo metodo di disattivazione è asincrono e restituisce una risposta prima che la crittografia venga disabilitata.  Puoi usare il `GetClusterInfo` metodo per interrogare il sistema per vedere quando il processo è stato completato.


TIP: Per visualizzare lo stato corrente della crittografia a riposo e/o della crittografia software a riposo sul cluster, utilizzarelink:../api/reference_element_api_getclusterinfo.html["metodo per ottenere informazioni sul cluster"] . Puoi usare il `GetSoftwareEncryptionAtRestInfo` link:../api/reference_element_api_getsoftwareencryptionatrestinfo.html["metodo per ottenere informazioni che il cluster utilizza per crittografare i dati a riposo"].


NOTE: Non è possibile utilizzare questo metodo per disattivare la crittografia software a riposo.  Per disabilitare la crittografia software a riposo, è necessariolink:reference_element_api_createcluster.html["creare un nuovo cluster"] con la crittografia software a riposo disabilitata.



== Parametri

Questo metodo non ha parametri di input.



== Valori di ritorno

Questo metodo non ha valori di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "DisableEncryptionAtRest",
   "params": {},
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id" : 1,
  "result" : {}
}
----


== Nuovo dalla versione

9,6

[discrete]
== Trova maggiori informazioni

* link:../api/reference_element_api_getclusterinfo.html["Ottieni informazioni sul cluster"]
* https://docs.netapp.com/us-en/element-software/index.html["Documentazione del software SolidFire ed Element"]
* https://docs.netapp.com/sfe-122/topic/com.netapp.ndc.sfe-vers/GUID-B1944B0E-B335-4E0B-B9F1-E960BF32AE56.html["Documentazione per le versioni precedenti dei prodotti NetApp SolidFire ed Element"^]

