---
permalink: api/reference_element_api_testconnectmvip.html 
sidebar: sidebar 
keywords: management,connection,test,testing,mvip,testconnectmvip 
summary: 'È possibile utilizzare il metodo TestConnectMvip per testare la connessione di gestione al cluster di archiviazione.  Il test esegue il ping dell"MVIP ed esegue un semplice metodo API per verificare la connettività.' 
---
= TestConnectMvip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `TestConnectMvip` metodo per testare la connessione di gestione al cluster di archiviazione.  Il test esegue il ping dell'MVIP ed esegue un semplice metodo API per verificare la connettività.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


| mvip | È possibile passare questo valore per testare la connessione di gestione di un MVIP diverso.  Non è necessario utilizzare questo valore quando si testa la connessione al cluster di destinazione. | corda | Nessuno | NO 
|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


| dettagli  a| 
Informazioni sull'operazione di test (oggetto JSON):

* `connected`: Indica se il test è riuscito a connettersi al MVIP (booleano)
* `mvip`: Il MVIP testato su (stringa)
* `pingBytes`: Dettagli dei test ping con 56 byte e 1500 byte (oggetto)
+
** `56`: Risultati del test ping da 56 byte (oggetto JSON):
+
*** `individualResponseTimes`: Elenco dei tempi di risposta da ciascun nodo dell'ensemble (array di stringhe)
*** `individualStatus`: Elenco dello stato del ping da ciascun nodo dell'ensemble (array booleano)
*** `responseTime`: Tempo medio di risposta al ping (stringa)
*** `successful`: Indica se il test ping ha avuto esito positivo (booleano)


** `1500`: Risultati del test ping da 1500 byte (oggetto JSON):
+
*** `individualResponseTimes`: Elenco dei tempi di risposta da ciascun nodo dell'ensemble (array di stringhe)
*** `individualStatus`: Elenco dello stato del ping da ciascun nodo dell'ensemble (array booleano)
*** `responseTime`: Tempo medio di risposta al ping (stringa)
*** `successful`: Se il test ping ha avuto esito positivo (booleano)


** `duration`: Tempo necessario per eseguire il test (stringa)
** `result`: Risultato del test nel suo complesso (stringa)



| Oggetto JSON 
|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "TestConnectMvip",
   "params": {
       "mvip" : "172.27.62.50"
       },
    "id":1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "details": {
      "connected": true,
      "mvip": "172.27.62.50",
      "pingBytes": {
        "1500": {
          "individualResponseTimes": [
            "00:00:00.000250",
            "00:00:00.000206",
            "00:00:00.000200",
            "00:00:00.000199",
            "00:00:00.000199"
         ],
          "individualStatus": [
             true,
             true,
             true,
             true,
             true
         ],
         "responseTime": "00:00:00.000211",
         "successful": true
       },
       "56": {
          "individualResponseTimes": [
            "00:00:00.000217",
            "00:00:00.000122",
            "00:00:00.000117",
            "00:00:00.000119",
            "00:00:00.000121"
         ],
         "individualStatus": [
            true,
            true,
            true,
            true,
            true
         ],
         "responseTime": "00:00:00.000139",
         "successful": true
        }
      }
    },
    "duration": "00:00:00.271244",
    "result": "Passed"
  }
}
----


== Nuovo dalla versione

9,6
