---
permalink: api/reference_element_api_clonevolume.html 
sidebar: sidebar 
keywords: volumes,volume,cloning,clone,CloneVolume 
summary: È possibile utilizzare il metodo CloneVolume per creare una copia di un volume.  Questo metodo è asincrono e potrebbe richiedere una quantità di tempo variabile per essere completato. 
---
= CloneVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `CloneVolume` metodo per creare una copia di un volume.  Questo metodo è asincrono e potrebbe richiedere una quantità di tempo variabile per essere completato.

Il processo di clonazione inizia immediatamente quando si effettua il `CloneVolume` richiesta ed è rappresentativo dello stato del volume quando viene emesso il metodo API.  Puoi usare ilxref:reference_element_api_getasyncresult.adoc[Ottieni risultato asincrono] metodo per determinare quando il processo di clonazione è completo e il nuovo volume è disponibile per le connessioni.  Puoi usarexref:reference_element_api_listsyncjobs.adoc[ListSyncJobs] per vedere i progressi nella creazione del clone.  Gli attributi iniziali e le impostazioni della qualità del servizio per il volume vengono ereditati dal volume clonato.  È possibile modificare queste impostazioni conxref:reference_element_api_modifyvolume.adoc[ModificaVolume] .


NOTE: I volumi clonati non ereditano l'appartenenza al gruppo di accesso al volume dal volume di origine.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
accesso
 a| 
Accesso consentito per il nuovo volume.  Se non viene specificato alcun valore, il valore di accesso non cambia. Valori possibili:

* `readOnly`: (Facoltativo) Sono consentite solo le operazioni di lettura.
* `readWrite`: (Facoltativo) Sono consentite letture e scritture.
* `locked`: (Facoltativo) Non sono consentite letture o scritture.  Se non specificato, viene utilizzato il valore di accesso del volume da clonare.
* `replicationTarget`: (Facoltativo) Identificare un volume come volume di destinazione per un set di volumi accoppiati.  Se il volume non è associato, lo stato di accesso è bloccato.

 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
attributi
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
NO



 a| 
enable512e
 a| 
Specifica se il nuovo volume deve utilizzare l'emulazione del settore a 512 byte.  Se non specificato, viene utilizzata l'impostazione del volume da clonare.
 a| 
booleano
 a| 
Impostazione del volume originale
 a| 
NO



 a| 
enableSnapMirrorReplication
 a| 
Determina se il volume può essere utilizzato per la replica con endpoint SnapMirror . Valori possibili:

* VERO
* falso

 a| 
booleano
 a| 
falso
 a| 
NO



 a| 
nome
 a| 
Nome del nuovo volume clonato; deve essere lungo da 1 a 64 caratteri.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
nuovoIDAccount
 a| 
AccountID per il proprietario del nuovo volume.  Se non specificato, viene utilizzato l'accountID del proprietario del volume da clonare.
 a| 
intero
 a| 
AccountID del proprietario del volume originale
 a| 
NO



 a| 
nuovaDimensione
 a| 
Nuova dimensione del volume, in byte.  Potrebbe essere maggiore o minore della dimensione del volume da clonare.  Se non specificato, la dimensione del volume non viene modificata.  La dimensione è arrotondata al MB più vicino.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
ID istantanea
 a| 
ID dello snapshot utilizzato come origine del clone.  Se non viene fornito alcun ID, viene utilizzato il volume attivo corrente.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
ID volume
 a| 
VolumeID per il volume da clonare.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
asyncHandle
 a| 
Valore handle utilizzato per ottenere il risultato dell'operazione.
 a| 
intero



 a| 
cloneID
 a| 
Il cloneID per il volume appena clonato.
 a| 
intero



 a| 
curva
 a| 
I valori della curva QoS applicati al clone.
 a| 
Oggetto JSON



 a| 
volume
 a| 
Un oggetto contenente informazioni sul volume appena clonato.
 a| 
xref:reference_element_api_volume.adoc[volume]



 a| 
ID volume
 a| 
VolumeID per il volume appena clonato.
 a| 
intero

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "CloneVolume",
   "params": {
      "volumeID" : 5,
      "name"  : "mysqldata-snapshot1",
      "access" : "readOnly"
   },
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
      "asyncHandle": 42,
      "cloneID": 37,
      "volume": {
          "access": "readOnly",
          "accountID": 1,
          "attributes": {},
          "blockSize": 4096,
          "createTime": "2016-03-31T22:26:03Z",
          "deleteTime": "",
          "enable512e": true,
          "iqn": "iqn.2010-01.com.solidfire:jyay.mysqldata-snapshot1.680",
          "name": "mysqldata-snapshot1",
          "purgeTime": "",
          "qos": {
              "burstIOPS": 100,
              "burstTime": 60,
              "curve": {
                  "4096": 100,
                  "8192": 160,
                  "16384": 270,
                  "32768": 500,
                  "65536": 1000,
                  "131072": 1950,
                  "262144": 3900,
                  "524288": 7600,
                  "1048576": 15000
              },
              "maxIOPS": 100,
              "minIOPS": 50
          },
          "scsiEUIDeviceID": "6a796179000002a8f47acc0100000000",
          "scsiNAADeviceID": "6f47acc1000000006a796179000002a8",
          "sliceCount": 0,
          "status": "init",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeAccessGroups": [],
          "volumeID": 680,
          "volumePairs": []
      },
      "volumeID": 680
  }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

* xref:reference_element_api_getasyncresult.adoc[Ottieni risultato asincrono]
* xref:reference_element_api_listsyncjobs.adoc[ListSyncJobs]
* xref:reference_element_api_modifyvolume.adoc[ModificaVolume]

