---
permalink: api/reference_element_api_modifyvolumepair.html 
sidebar: sidebar 
keywords: volume,pair,pairs,modify,modifying,edit,editing,changing,change,modifyvolumepair,paired 
summary: 'È possibile utilizzare il metodo ModifyVolumePair per sospendere o riavviare la replica tra una coppia di volumi.  Questo metodo è impostato sul volume di origine (il volume con accesso in lettura/scrittura).' 
---
= Modifica coppia di volumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ModifyVolumePair` metodo per mettere in pausa o riavviare la replica tra una coppia di volumi.  Questo metodo viene impostato sul volume sorgente (il volume con accesso in lettura/scrittura).



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID volume
 a| 
Numero identificativo del volume da modificare.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
in pausaManuale
 a| 
La replica remota può essere sospesa o riavviata sul volume di origine (lettura/scrittura). Valori possibili:

* vero: sospendi la replica del volume.
* false: riavvia la replica del volume.


Se non viene specificato alcun valore, non verrà eseguita alcuna modifica nella replica.
 a| 
booleano
 a| 
Nessuno
 a| 
NO



 a| 
modalità
 a| 
Modalità di replica del volume. Valori possibili:

* Asincrono: le scritture vengono riconosciute quando vengono completate localmente.  Il cluster non attende che le scritture vengano replicate sul cluster di destinazione.
* Sincronizzazione: la sorgente riconosce la scrittura quando i dati vengono archiviati localmente e sul cluster remoto.
* SnapshotsOnly: vengono replicati solo gli snapshot creati sul cluster di origine.  Le scritture attive dal volume di origine non vengono replicate.

 a| 
corda
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo non ha valore di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ModifyVolumePair",
  "params": {
    "pausedManual": false,
    "volumeID": 5,
    "mode": "sync"
   },
  "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id" : 1,
   "result" : {}
}
----


== Nuovo dalla versione

9,6
