---
permalink: api/reference_element_api_listpendingactivenodes.html 
sidebar: sidebar 
keywords: cluster,list,listing,pending,active,node,nodes,listpendingactivenodes 
summary: 'È possibile utilizzare il metodo ListPendingActiveNodes per elencare i nodi nel cluster che si trovano nello stato PendingActive, tra gli stati in sospeso e attivo.  I nodi in questo stato vengono riportati all"immagine di fabbrica.' 
---
= Elenco nodi attivi in sospeso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListPendingActiveNodes` metodo per elencare i nodi nel cluster che si trovano nello stato PendingActive, tra gli stati in sospeso e attivo.  I nodi in questo stato vengono riportati all'immagine di fabbrica.



== Parametri

Questo metodo non ha parametri di input.



== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
pendingActiveNodes
 a| 
Elenco di oggetti che contengono informazioni dettagliate su tutti i nodi PendingActive nel sistema.
 a| 
xref:reference_element_api_pendingactivenode.adoc[pendingActiveNode]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ListPendingActiveNodes",
   "params": {},
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  id: null,
  result: {
    pendingActiveNodes: [
    {
      activeNodeKey: "5rPHP3lTAO",
      assignedNodeID: 5,
      asyncHandle: 2,
      cip: "10.10.5.106",
      mip: "192.168.133.106",
      pendingNodeID: 1,
      platformInfo: {
        chassisType: "R620",
        cpuModel: "Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz",
        nodeMemoryGB: 72,
        nodeType: "SF3010"
      },
     sip: "10.10.5.106",
     softwareVersion: "9.0.0.1077"
    }
    ]
  }
}
----


== Nuovo dalla versione

9,6
