---
permalink: api/reference_element_api_createqospolicy.html 
sidebar: sidebar 
keywords: QoS,policy,policies,create,creating 
summary: È possibile utilizzare il metodo CreateQoSPolicy per creare un oggetto QoSPolicy che sarà possibile applicare in seguito a un volume al momento della creazione o della modifica.  Una policy QoS ha un ID univoco, un nome e impostazioni QoS. 
---
= Crea politica QoSP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `CreateQoSPolicy` metodo per creare un oggetto QoSPolicy che è possibile applicare in seguito a un volume al momento della creazione o della modifica.  Una policy QoS ha un ID univoco, un nome e impostazioni QoS.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
nome
 a| 
Nome della policy QoS, ad esempio oro, platino o argento.
 a| 
corda
 a| 
Nessuno
 a| 
SÌ



 a| 
qualità
 a| 
Le impostazioni QoS rappresentate da questa policy.
 a| 
xref:reference_element_api_qos.adoc[Qualità del servizio]
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
Politica QOS
 a| 
L'oggetto QoSPolicy appena creato.
 a| 
xref:reference_element_api_qospolicy.adoc[Politica QoSP]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "id": 68,
  "method": "CreateQoSPolicy",
  "params": {
    "name": "bronze",
    "qos": {
      "minIOPS": 50,
      "maxIOPS": 15000,
      "burstIOPS": 15000
    }
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 68,
  "result": {
    "qosPolicy": {
      "name": "bronze",
      "qos": {
        "burstIOPS": 15000,
        "burstTime": 60,
        "curve": {
          "4096": 100,
          "8192": 160,
          "16384": 270,
          "32768": 500,
          "65536": 1000,
          "131072": 1950,
          "262144": 3900,
          "524288": 7600,
          "1048576": 15000
        },
        "maxIOPS": 15000,
        "minIOPS": 50
      },
      "qosPolicyID": 2,
      "volumeIDs": []
    }
  }
}
----


== Nuovo dalla versione

10,0
