---
permalink: api/reference_element_api_listvolumes.html 
sidebar: sidebar 
keywords: volume,volumes,list,listing,listvolumes 
summary: 'È possibile utilizzare il metodo ListVolumes per ottenere un elenco dei volumi presenti in un cluster.  È possibile specificare i volumi che si desidera restituire nell"elenco utilizzando i parametri disponibili.' 
---
= ElencoVolumi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListVolumes` metodo per ottenere un elenco dei volumi presenti in un cluster.  È possibile specificare i volumi che si desidera restituire nell'elenco utilizzando i parametri disponibili.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
conti
 a| 
Vengono restituiti solo i volumi di proprietà degli account specificati qui.  Mutuamente esclusivi con il parametro volumeIDs.
 a| 
array di interi
 a| 
Nessuno
 a| 
NO



 a| 
includeVirtualVolumes
 a| 
Per impostazione predefinita, i volumi virtuali sono inclusi nella risposta.  Per escludere i volumi virtuali, impostare su false.
 a| 
booleano
 a| 
VERO
 a| 
NO



 a| 
è accoppiato
 a| 
Restituisce i volumi accoppiati o non accoppiati. Valori possibili:

* true: restituisce tutti i volumi accoppiati.
* false: restituisce tutti i volumi non accoppiati.

 a| 
booleano
 a| 
Nessuno
 a| 
NO



 a| 
limite
 a| 
Consente di impostare il numero massimo di risultati di volume restituiti.  Mutuamente esclusivi con il parametro volumeIDs.
 a| 
intero
 a| 
10000
 a| 
NO



 a| 
startVolumeID
 a| 
Vengono restituiti solo i volumi con un ID maggiore o uguale a questo valore.  Mutuamente esclusivi con il parametro volumeIDs.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
volumeID
 a| 
Un elenco di ID volume.  Se si specifica questo parametro, gli altri parametri operano solo su questo set di volumi.  Mutuamente esclusivi con i parametri accounts, startVolumeID e limit.
 a| 
array di interi
 a| 
NO
 a| 
NO



 a| 
NomeVolume
 a| 
Vengono restituite solo le informazioni sull'oggetto volume che corrispondono al nome del volume.
 a| 
corda
 a| 
NO
 a| 
NO



 a| 
volumeStatus
 a| 
Vengono restituiti solo i volumi con uno stato uguale al valore dello stato. Valori possibili:

* creazione
* creazione di istantanee
* attivo
* cancellato

 a| 
corda
 a| 
NO
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
volumi
 a| 
Elenco dei volumi.
 a| 
xref:reference_element_api_volume.adoc[volume]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ListVolumes",
    "params": {
        "volumeIDs": [1],
        "volumeStatus": "active",
        "isPaired": "false"
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
    "id": 1,
    "result": {
        "volumes": [
            {
                "access": "readWrite",
                "accountID": 1,
                "attributes": {},
                "blockSize": 4096,
                "createTime": "2016-03-28T14:39:05Z",
                "deleteTime": "",
                "enable512e": true,
                "iqn": "iqn.2010-01.com.solidfire:testvolume1.1",
                "name": "testVolume1",
                "purgeTime": "",
                "qos": {
                    "burstIOPS": 15000,
                    "burstTime": 60,
                    "curve": {
                        "4096": 100,
                        "8192": 160,
                        "16384": 270,
                        "32768": 500,
                        "65536": 1000,
                        "131072": 1950,
                        "262144": 3900,
                        "524288": 7600,
                        "1048576": 15000
                    },
                    "maxIOPS": 15000,
                    "minIOPS": 50
                },
                "scsiEUIDeviceID": "6a79617900000001f47acc0100000000",
                "scsiNAADeviceID": "6f47acc1000000006a79617900000001",
                "sliceCount": 1,
                "status": "active",
                "totalSize": 5000658944,
                "virtualVolumeID": null,
                "volumeAccessGroups": [],
                "volumeID": 1,
                "volumePairs": []
            }
        ]
    }
}
----


== Nuovo dalla versione

9,6
