---
permalink: api/reference_element_api_modifyvolume.html 
sidebar: sidebar 
keywords: volumes,volume,modifying,modify,change,changing,edit,editing,modifyvolume,settings 
summary: È possibile utilizzare il metodo ModifyVolume per modificare le impostazioni di un volume esistente.  È possibile apportare modifiche a un volume alla volta e le modifiche verranno applicate immediatamente. 
---
= ModificaVolume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ModifyVolume` metodo per modificare le impostazioni su un volume esistente.  È possibile apportare modifiche a un volume alla volta e le modifiche verranno applicate immediatamente.

Se non si specificano i valori QoS quando si modifica un volume, questi rimangono invariati rispetto a prima della modifica.  È possibile recuperare i valori QoS predefiniti per un volume appena creato eseguendo il comando `GetDefaultQoS` metodo.

Quando è necessario aumentare le dimensioni di un volume replicato, procedere nel seguente ordine per evitare errori di replica:

. Aumentare le dimensioni del volume con l'accesso replicationTarget.
. Aumentare le dimensioni della sorgente o del volume con accesso readWrite.


Assicurarsi che i volumi di destinazione e di origine abbiano le stesse dimensioni.


NOTE: Se si modifica lo stato di accesso in bloccato o replicationTarget, tutte le connessioni iSCSI esistenti vengono terminate.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID volume
 a| 
VolumeID del volume da modificare.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
accesso
 a| 
Accesso consentito per il volume. Valori possibili:

* `readOnly`: Sono consentite solo le operazioni di lettura.
* `readWrite`: Sono consentite letture e scritture.
* `locked`: Non sono consentite letture o scritture.  Se non specificato, il valore di accesso non cambia.
* `replicationTarget`: Identifica un volume come volume di destinazione per un set di volumi accoppiati.  Se il volume non è associato, lo stato di accesso è bloccato.  Se non viene specificato alcun valore, il valore di accesso non cambia.
* `snapMirrorTarget`: Identifica un volume come volume di destinazione per la replica SnapMirror .

 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
ID account
 a| 
L'accountID a cui viene riassegnato il volume.  Se non viene specificato alcun nome, verrà utilizzato il nome dell'account precedente.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
associare alla politica QoSP
 a| 
Associare il volume al criterio QoS specificato. Valori possibili:

* `true`: associa il volume alla policy QoS specificata nel parametro QoSPolicyID.
* `false`: Non associare il volume alla policy QoS specificata nel parametro QoSPolicyID.  Se impostato su false, qualsiasi associazione di policy esistente viene rimossa, indipendentemente dal fatto che si specifichi una policy QoS nel parametro QoSPolicy.

 a| 
booleano
 a| 
Nessuno
 a| 
NO



 a| 
attributi
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
NO



 a| 
createTime
 a| 
Una stringa di data ISO 8601 da impostare come data di creazione del nuovo volume.  Obbligatorio se setCreateTime è impostato su true.
 a| 
Stringa ISO 8601
 a| 
Nessuno
 a| 
NO



 a| 
dontMoveforIopsRebalance
 a| 
Impedisce lo spostamento di un volume durante il bilanciamento del carico con IOPS effettivi.  Questa impostazione è disponibile a partire da Element 12.8 ed è efficace solo quandolink:reference_element_api_enablefeature.html["VolumeLoadBalanceOnActualIOPS"] è abilitato. Valori possibili:

* `true`: Il volume non bilancia il carico in base agli IOPS effettivi.
* `false`: Il volume bilancia il carico in base agli IOPS effettivi.


*Nota*: il bilanciamento per l'alta disponibilità (guasto del nodo) ha la precedenza su `VolumeLoadBalanceOnActualIOPS` E `dontMoveforIopsRebalance` .
| booleano | falso | NO 


 a| 
enableSnapMirrorReplication
 a| 
Determina se il volume può essere utilizzato per la replica con endpoint SnapMirror . Valori possibili:

* `true`
* `false`

 a| 
booleano
 a| 
falso
 a| 
NO



| fifoSize | Specifica il numero massimo di snapshot First-In-First-Out (FIFO) supportati dal volume.  Si noti che gli snapshot FIFO e non FIFO utilizzano entrambi lo stesso pool di slot snapshot disponibili su un volume.  Utilizzare questa opzione per limitare il consumo di snapshot FIFO degli slot snapshot disponibili.  Si noti che non è possibile modificare questo valore in modo che sia inferiore al conteggio attuale degli snapshot FIFO. | intero | Nessuno | NO 


| minFifoSize | Specifica il numero di slot snapshot riservati solo per snapshot First-In-First-Out (FIFO).  Poiché gli snapshot FIFO e non FIFO condividono lo stesso pool, il parametro minFifoSize riduce della stessa quantità il numero totale di possibili snapshot non FIFO.  Si noti che non è possibile modificare questo valore in modo che entri in conflitto con il conteggio attuale degli snapshot non FIFO. | intero | Nessuno | NO 


 a| 
modalità
 a| 
Modalità di replica del volume. Valori possibili:

* `asynch`: Attende che il sistema riconosca che i dati sono memorizzati sulla sorgente prima di scriverli sulla destinazione.
* `sync`: Non attende la conferma della trasmissione dei dati dalla sorgente per iniziare a scrivere i dati sulla destinazione.

 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
qualità
 a| 
Le nuove impostazioni di qualità del servizio per questo volume.  Se non specificato, le impostazioni QoS non vengono modificate. Valori possibili:

* `minIOPS`
* `maxIOPS`
* `burstIOPS`

 a| 
xref:reference_element_api_qos.adoc[Qualità del servizio]
 a| 
Nessuno
 a| 
NO



 a| 
qosPolicyID
 a| 
ID del criterio le cui impostazioni QoS devono essere applicate ai volumi specificati.  Questo parametro è mutuamente esclusivo con il parametro qos.
 a| 
intero
 a| 
Nessuno
 a| 
NO



 a| 
impostaCreateTime
 a| 
Impostare su true per modificare la data registrata della creazione del volume.
 a| 
booleano
 a| 
Nessuno
 a| 
NO



 a| 
dimensione totale
 a| 
La nuova dimensione del volume in byte.  1000000000 equivale a 1 GB.  La dimensione è arrotondata al megabyte più vicino.  Questo parametro può essere utilizzato solo per aumentare le dimensioni di un volume.
 a| 
intero
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
volume
 a| 
Oggetto contenente informazioni sul volume appena modificato.
 a| 
xref:reference_element_api_volume.adoc[volume]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ModifyVolume",
  "params": {
     "volumeID": 319,
     "access": "readWrite",
     "dontMoveForIopsRebalance": false
     },
     "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
      "volume": {
          "access": "readWrite",
          "accountID":22,
          "attributes": {},
          "blockSize": 4096,
          "createTime": "2024-04-01T19:39:40Z",
          "currentProtectionScheme": "doubleHelix",
          "deleteTime": "",
          "dontMoveForIopsRebalance": false,
          "enable512e": false,
          "enableSnapMirrorReplication": false,
          "fifoSize": 24,
          "iqn": "iqn.2010-01.com.solidfire:3eeu.suite40.319",
          "lastAccessTime": "2024-04-02T12:41:34Z",
          "lastAccessTimeIO": "2024-04-01T20:41:19Z",
          "minFifoSize": 0,
          "name": "suite40",
          "previousProtectionScheme": null,
          "purgeTime": "",
          "qos": {
              "burstIOPS": 27000,
              "burstTime": 60,
              "curve": {
                  "1048576": 15000,
                  "131072": 1950,
                  "16384": 270,
                  "262144": 3900,
                  "32768": 500, "4096": 100,
                  "524288": 7600,
                  "65536": 1000,
                  "8192": 160
              },
              "maxIOPS": 27000,
              "minIOPS": 500
          },
          "qosPolicyID": null,
          "scsiEUIDeviceID": "336565750000013ff47acc0100000000",
          "scsiNAADeviceID": "6f47acc100000000336565750000013f",
          "sliceCount": 1,
          "status": "active",
          "totalSize": 1000000716800,
          "virtualVolumeID": null,
          "volumeAccessGroups": [
          22
          ],
          "volumeConsistencyGroupUUID": "3003109e-6e75-444c-8cee-470d641a09c3",
          "volumeID": 319,
          "volumePairs": [],
          "volumeUUID": "78203136-b0eb-454b-9f67-2c867ec7d7bb"
      }
  }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_getdefaultqos.adoc[OttieniQoS predefinito]
