---
permalink: api/reference_element_api_rollbacktogroupsnapshot.html 
sidebar: sidebar 
keywords: rollbacktogroupsnapshot,snapshot,group,individual,creating,create,roll,back,rollback,roll back,existing 
summary: È possibile utilizzare RollbackToGroupSnapshot per ripristinare tutti i singoli volumi in un gruppo di snapshot allo snapshot individuale di ciascun volume. 
---
= RollbackToGroupSnapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare `RollbackToGroupSnapshot` per ripristinare tutti i singoli volumi in un gruppo di snapshot allo snapshot individuale di ciascun volume.

Il rollback a uno snapshot di gruppo crea uno snapshot temporaneo di ciascun volume all'interno dello snapshot di gruppo.

[NOTE]
====
* La creazione di uno snapshot è consentita se il cluster è pieno nella fase 1, 2 o 3.  Gli snapshot non vengono creati quando il livello di riempimento del cluster è pari a 4 o 5.
* Il rollback dei volumi in uno snapshot di gruppo potrebbe non riuscire quando è in corso la sincronizzazione delle sezioni.  Riprova `RollbackToGroupSnapshot` al termine della sincronizzazione.


====


== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
`groupSnapshotID`
 a| 
ID univoco dello snapshot del gruppo.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
`attributes`
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
NO



 a| 
`name`
 a| 
Nome per lo snapshot di gruppo dello stato corrente del volume che viene creato se `saveCurrentState` è impostato su vero.  Se non si specifica un nome, il nome degli snapshot (gruppo e volume individuale) verrà impostato su un timestamp dell'ora in cui si è verificato il rollback.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
`saveCurrentState`
 a| 
Specifica se salvare o meno l'immagine del volume attivo precedente.  Valori validi:

* `true`: Viene mantenuta l'immagine del volume attivo precedente.
* `false`: L'immagine del volume attivo precedente viene eliminata.

 a| 
booleano
 a| 
falso
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
membri
 a| 
Un array contenente i volumiID e gli snapshotID dei membri dello snapshot di gruppo.  Valori:

* checksum: una piccola rappresentazione in forma di stringa dei dati nello snapshot memorizzato.  Questo checksum può essere utilizzato in seguito per confrontare altri snapshot e rilevare errori nei dati.  (corda)
* snapshotID: ID univoco di uno snapshot da cui viene creato il nuovo snapshot.  Lo snapshotID deve essere uno snapshot sul volume specificato.  (numero intero)
* volumeID: ID del volume di origine per lo snapshot.  (numero intero)

 a| 
Matrice di oggetti JSON



 a| 
ID istantanea gruppo
 a| 
Se `saveCurrentState` è stato impostato su false, questo valore è nullo.

Se `saveCurrentState` è stato impostato su true, l'ID univoco dello snapshot di gruppo appena creato.
 a| 
intero



 a| 
groupSnapshot
 a| 
Se `saveCurrentState` è stato impostato su false, questo valore è nullo.

Se `saveCurrentState` è stato impostato su true, un oggetto contenente informazioni sullo snapshot del gruppo che `RollbackToGroupSnapshot` appena tornato a.
 a| 
xref:reference_element_api_groupsnapshot.adoc[groupSnapshot]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "id": 438,
  "method": "RollbackToGroupSnapshot",
  "params": {
    "groupSnapshotID": 1,
    "name": "grpsnap1",
    "saveCurrentState": true
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 438,
  "result": {
    "groupSnapshot": {
      "attributes": {},
      "createTime": "2016-04-06T17:27:17Z",
      "groupSnapshotID": 1,
      "groupSnapshotUUID": "468fe181-0002-4b1d-ae7f-8b2a5c171eee",
      "members": [
        {
          "attributes": {},
          "checksum": "0x0",
          "createTime": "2016-04-06T17:27:17Z",
          "enableRemoteReplication": false,
          "expirationReason": "None",
          "expirationTime": null,
          "groupID": 1,
          "groupSnapshotUUID": "468fe181-0002-4b1d-ae7f-8b2a5c171eee",
          "name": "2016-04-06T17:27:17Z",
          "snapshotID": 4,
          "snapshotUUID": "03563c5e-51c4-4e3b-a256-a4d0e6b7959d",
          "status": "done",
          "totalSize": 1000341504,
          "virtualVolumeID": null,
          "volumeID": 2
        }
      ],
      "name": "2016-04-06T17:27:17Z",
      "status": "done"
    },
    "groupSnapshotID": 3,
    "members": [
      {
        "checksum": "0x0",
        "snapshotID": 2,
        "snapshotUUID": "719b162c-e170-4d80-b4c7-1282ed88f4e1",
        "volumeID": 2
      }
    ]
  }
}
----


== Nuovo dalla versione

9,6
