---
permalink: api/reference_element_api_snapshot.html 
sidebar: sidebar 
keywords: object,objects,snapshot 
summary: 'L"oggetto snapshot contiene informazioni su uno snapshot creato per un volume.  È possibile utilizzare il metodo API ListSnapshots per recuperare un elenco di informazioni snapshot per un volume o per tutti i volumi.  L"oggetto include informazioni sullo snapshot attivo e su ogni snapshot creato per un volume.' 
---
= istantanea
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto snapshot contiene informazioni su uno snapshot creato per un volume.  Puoi usare il `ListSnapshots` Metodo API per recuperare un elenco di informazioni snapshot per un volume o per tutti i volumi.  L'oggetto include informazioni sullo snapshot attivo e su ogni snapshot creato per un volume.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
attributi
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON



 a| 
somma di controllo
 a| 
Una piccola rappresentazione in forma di stringa dei dati nello snapshot memorizzato.  Questo checksum può essere utilizzato in seguito per confrontare altri snapshot e rilevare errori nei dati.
 a| 
corda



 a| 
createTime
 a| 
Ora in formato UTC+0 in cui è stato creato lo snapshot.
 a| 
Stringa di data ISO 8601



 a| 
enableReplication
 a| 
Identifica se lo snapshot è abilitato per la replica remota.
 a| 
booleano



 a| 
motivo di scadenza
 a| 
Indica come viene impostata la scadenza dello snapshot. Valori possibili:

* API: il tempo di scadenza viene impostato tramite l'API.
* Nessuno: non è impostata alcuna scadenza.
* Test: il tempo di scadenza è impostato per il test.
* fifo: la scadenza avviene secondo il principio first-in-first-out.

 a| 
corda



 a| 
tempo di scadenza
 a| 
Ora in cui questo snapshot scadrà e verrà eliminato dal cluster.
 a| 
Stringa di data ISO 8601



 a| 
ID gruppo
 a| 
ID del gruppo se lo snapshot è membro di uno snapshot di gruppo.
 a| 
intero



 a| 
groupsnapshotUUID
 a| 
Contiene informazioni su ogni snapshot del gruppo.  Ciascuno di questi membri avrà un parametro UUID per l'UUID dello snapshot.
 a| 
corda



 a| 
instanceCreateTime
 a| 
Ora in cui è stato creato lo snapshot sul cluster locale.
 a| 
Stringa di data ISO 8601



 a| 
instanceSnapshotUUID
 a| 
ID univoco universale dello snapshot sul cluster locale.  Questo ID non viene replicato in altri cluster.
 a| 
corda



 a| 
nome
 a| 
Nome univoco assegnato allo snapshot.  Se non viene specificato alcun nome, il nome è il timestamp in formato UTC+0 del momento in cui è stato creato lo snapshot.
 a| 
corda



 a| 
Stati remoti
 a| 
Un array contenente l'identificatore universale e lo stato di replica di ogni snapshot remoto sul cluster di destinazione, così come visualizzato dal cluster di origine.
 a| 
xref:reference_element_api_remoteclustersnapshotstatus.adoc[remoteClusterSnapshotStatus]vettore



 a| 
snapMirrorLabel
 a| 
Etichetta utilizzata dal software SnapMirror per specificare i criteri di conservazione degli snapshot sugli endpoint SnapMirror .  Se non impostato, questo valore è nullo.
 a| 
corda



 a| 
ID istantanea
 a| 
ID univoco di uno snapshot esistente.
 a| 
corda



 a| 
snapshotUUID
 a| 
L'ID univoco universale di uno snapshot esistente.  Quando lo snapshot viene replicato tra i cluster, questo ID viene replicato insieme ad esso e viene utilizzato per identificare lo snapshot tra i cluster.
 a| 
corda



 a| 
stato
 a| 
Stato attuale dello snapshot. Valori possibili:

* Sconosciuto: si è verificato un errore durante l'ottenimento dello stato dello snapshot.
* Preparazione: questo snapshot è in fase di preparazione per l'uso e non è ancora scrivibile.
* RemoteSyncing: questo snapshot viene replicato da un cluster remoto.
* Fatto: la preparazione o la replica di questo snapshot sono state completate e ora è utilizzabile.
* Attivo: questo snapshot è il ramo attivo.
* Clonazione: questo snapshot è coinvolto in un'operazione CopyVolume.

 a| 
corda



 a| 
dimensione totale
 a| 
La dimensione totale in byte dello snapshot.
 a| 
intero



 a| 
virtualVolumeID
 a| 
ID del volume virtuale associato a questo snapshot.
 a| 
UUID



 a| 
ID volume
 a| 
ID del volume da cui è stato creato lo snapshot.
 a| 
intero



 a| 
NomeVolume
 a| 
Nome del volume al momento della creazione dello snapshot.
 a| 
corda

|===


== Trova maggiori informazioni

xref:reference_element_api_listsnapshots.adoc[ListSnapshots]
