---
permalink: api/reference_element_api_removekeyserverfromproviderkmip.html 
sidebar: sidebar 
keywords: KMIP,key server,unassigning,removing,remove,unassign,removekeyserverfromproviderkmip 
summary: 'È possibile utilizzare il metodo RemoveKeyServerFromProviderKmip per annullare l"assegnazione del server delle chiavi Key Management Interoperability Protocol \(KMIP\) specificato al provider a cui era assegnato.  È possibile annullare l"assegnazione di un server di chiavi al suo provider, a meno che non sia l"ultimo e il suo provider sia attivo (che fornisce chiavi attualmente in uso).  Se il server delle chiavi specificato non è assegnato a un provider, non viene intrapresa alcuna azione e non viene restituito alcun errore.' 
---
= RemoveKeyServerFromProviderKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `RemoveKeyServerFromProviderKmip` metodo per annullare l'assegnazione del server delle chiavi KMIP (Key Management Interoperability Protocol) specificato al provider a cui era assegnato.  È possibile annullare l'assegnazione di un server di chiavi al suo provider, a meno che non sia l'ultimo e il suo provider sia attivo (che fornisce chiavi attualmente in uso).  Se il server delle chiavi specificato non è assegnato a un provider, non viene intrapresa alcuna azione e non viene restituito alcun errore.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID del server chiave
 a| 
ID del server delle chiavi KMIP da annullare l'assegnazione.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo non ha valori di ritorno.  La rimozione è considerata riuscita finché non viene restituito alcun errore.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "RemoveKeyServerFromProviderKmip",
  "params": {
    "keyServerID": 1
   },
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result":
      {}
    }
}
----


== Nuovo dalla versione

11,7
