---
permalink: api/reference_element_api_getaccountefficiency.html 
sidebar: sidebar 
keywords: accounts,account,efficiency,get,getting,GetAccountEfficiency 
summary: 'È possibile utilizzare GetAccountEfficiency per ottenere statistiche sull"efficienza di un account di volume.  Questo metodo restituisce informazioni sull"efficienza solo per l"account fornito come parametro.' 
---
= Ottieni efficienza dell'account
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare `GetAccountEfficiency` per ottenere statistiche di efficienza su un account di volume.  Questo metodo restituisce informazioni sull'efficienza solo per l'account fornito come parametro.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID account
 a| 
Specifica l'account del volume per il quale vengono restituite le statistiche sull'efficienza.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
compressione
 a| 
Quantità di spazio risparmiata dalla compressione dei dati per tutti i volumi nell'account.  Espresso come rapporto in cui il valore "1" indica che i dati sono stati memorizzati senza compressione.
 a| 
galleggiante



 a| 
deduplicazione
 a| 
Quantità di spazio risparmiata evitando di duplicare i dati per tutti i volumi dell'account.  Espresso come rapporto.
 a| 
galleggiante



 a| 
volumi mancanti
 a| 
I volumi che non è stato possibile interrogare per i dati di efficienza.  I volumi mancanti possono essere causati dal fatto che il ciclo di Garbage Collection (GC) è stato eseguito meno di un'ora prima, da una perdita temporanea della connettività di rete o da servizi riavviati dopo il ciclo GC.
 a| 
array di interi



 a| 
thinProvisioning
 a| 
Rapporto tra lo spazio utilizzato e la quantità di spazio allocato per l'archiviazione dei dati.  Espresso come rapporto.
 a| 
galleggiante



 a| 
marca temporale
 a| 
L'ultima volta che i dati sull'efficienza sono stati raccolti dopo la Garbage Collection (GC), nel formato UTC+0.
 a| 
Stringa di data ISO 8601

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "GetAccountEfficiency",
   "params": {
     "accountID": 3
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result": {
       "compression": 2.020468042933262,
       "deduplication": 2.042488619119879,
       "missingVolumes": [],
       "thinProvisioning": 1.010087163391013,
       "timestamp": "2014-03-10T14:06:02Z"
   }
}
----


== Nuovo dalla versione

9,6
