---
permalink: api/reference_element_api_response_object_members.html 
sidebar: sidebar 
keywords: response,object,member 
summary: 'Ogni corpo di risposta dell"API del software Element è costituito dalle seguenti parti di base:' 
---
= Membri dell'oggetto di risposta
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Ogni corpo di risposta dell'API del software Element è costituito dalle seguenti parti di base:

|===
| Nome | Descrizione | Tipo 


 a| 
risultato
 a| 
L'oggetto restituito dal metodo.  Il sistema restituisce un oggetto con membri denominati corrispondenti al valore di ritorno documentato per il metodo.  Questo membro non è presente se si è verificato un errore.
 a| 
Oggetto JSON



 a| 
errore
 a| 
L'oggetto restituito quando si verifica un errore.  Questo membro è presente solo se si è verificato un errore.
 a| 
Oggetto



 a| 
id
 a| 
Un identificatore utilizzato per abbinare la richiesta alla risposta, come fornito nella richiesta.
 a| 
stringa o intero



 a| 
parametri non utilizzati
 a| 
Un messaggio di avviso indica che almeno un parametro errato è stato passato al metodo API e non è stato utilizzato.
 a| 
Oggetto

|===