---
permalink: api/reference_element_api_setsnmpacl.html 
sidebar: sidebar 
keywords: setsnmpACL,set,setting,snmp,acl,permissions,access,control,list 
summary: È possibile utilizzare il metodo SetSnmpACL per configurare le autorizzazioni di accesso SNMP sui nodi del cluster.  I valori impostati con questa interfaccia si applicano a tutti i nodi del cluster e i valori passati sostituiscono tutti i valori impostati in qualsiasi precedente chiamata a SetSnmpACL.  Si noti inoltre che i valori impostati con questa interfaccia sostituiscono tutti i valori network o usmUsers impostati con SetSnmpInfo. 
---
= SetSnmpACL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `SetSnmpACL` metodo per configurare le autorizzazioni di accesso SNMP sui nodi del cluster.  I valori impostati con questa interfaccia si applicano a tutti i nodi del cluster e i valori passati sostituiscono tutti i valori impostati in qualsiasi chiamata precedente a `SetSnmpACL` .  Si noti inoltre che i valori impostati con questa interfaccia sostituiscono tutti i valori di rete o usmUsers impostati con `SetSnmpInfo` metodo.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
reti
 a| 
Elenco delle reti e tipo di accesso che hanno ai server SNMP in esecuzione sui nodi del cluster.  Per i possibili valori di rete, vedere l'oggetto di rete SNMP.  Questo parametro è obbligatorio se SNMP v3 è disabilitato.
 a| 
xref:reference_element_api_network_snmp.adoc[rete]
 a| 
Nessuno
 a| 
NO



 a| 
Utenti usm
 a| 
Elenco degli utenti e tipo di accesso di cui dispongono ai server SNMP in esecuzione sui nodi del cluster.  Questo parametro è obbligatorio se SNMP v3 è abilitato.
 a| 
xref:reference_element_api_usmuser.adoc[usmUser]
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo non ha valori di ritorno.



== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "SetSnmpACL",
  "params": {
    "usmUsers"  : [
      {
         "name": "jdoe",
         "access": "rouser",
         "secLevel": "priv",
         "password": "mypassword",
         "passphrase": "mypassphrase",
      }
    ]
  },
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id" : 1,
  "result" : {}
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_setsnmpinfo.adoc[ImpostaSnmpInfo]
