---
permalink: api/reference_element_api_modifystoragecontainer.html 
sidebar: sidebar 
keywords: virtual,volume,storage,container,vvol,modify,modifying,change,changing,edit,editing 
summary: È possibile utilizzare il metodo ModifyStorageContainer per apportare modifiche a un contenitore di archiviazione di volumi virtuali esistente. 
---
= ModificaContenitore di archiviazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ModifyStorageContainer` metodo per apportare modifiche a un contenitore di archiviazione di volumi virtuali esistente.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
storageContainerID
 a| 
ID univoco del contenitore di archiviazione del volume virtuale da modificare.
 a| 
UUID
 a| 
Nessuno
 a| 
SÌ



 a| 
iniziatoreSegreto
 a| 
Il nuovo segreto per l'autenticazione CHAP per l'iniziatore.
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
targetSecret
 a| 
Il nuovo segreto per l'autenticazione CHAP per la destinazione.
 a| 
corda
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
contenitore di stoccaggio
 a| 
Informazioni sul contenitore di archiviazione appena creato.
 a| 
xref:reference_element_api_storagecontainer.adoc[contenitore di stoccaggio]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ModifyStorageContainer",
    "params": {
      "storageContainerID": "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1",
      "targetSecret": "O,IM;tOQdn9$JJ*8"
    },
    "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "storageContainer": {
      "accountID": 8,
      "initiatorSecret": "T$|5TO>2IY5sk4@k",
      "name": "doctest1",
      "protocolEndpointType": "SCSI",
      "status": "active",
      "storageContainerID": "6c95e24f-9f0b-4793-affb-5a4bc6c3d7e1",
      "targetSecret": "O,IM;tOQdn9$JJ*8"
    }
  }
}
----


== Nuovo dalla versione

9,6
