---
permalink: api/reference_element_api_listkeyproviderskmip.html 
sidebar: sidebar 
keywords: KMIP,key providers,key,provider,retrieving,listing,list,retrieve,listkeyproviderskmip 
summary: 'È possibile utilizzare il metodo ListKeyProvidersKmip per recuperare un elenco di tutti i provider di chiavi Key Management Interoperability Protocol \(KMIP\) esistenti.  È possibile filtrare l"elenco specificando parametri aggiuntivi.' 
---
= ListKeyProvidersKmip
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListKeyProvidersKmip` metodo per recuperare un elenco di tutti i fornitori di chiavi KMIP (Key Management Interoperability Protocol) esistenti.  È possibile filtrare l'elenco specificando parametri aggiuntivi.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
keyProviderIsActive
 a| 
I filtri hanno restituito oggetti server chiave KMIP in base al loro stato attivo. Valori possibili:

* true: restituisce solo i provider di chiavi KMIP attivi (che forniscono chiavi attualmente in uso).
* false: restituisce solo i provider di chiavi KMIP inattivi (che non forniscono chiavi e possono essere eliminati).


Se omesso, i provider di chiavi KMIP restituiti non vengono filtrati in base al fatto che siano attivi.
 a| 
booleano
 a| 
Nessuno
 a| 
NO



 a| 
kmipKeyProviderHasServerAssigned
 a| 
I filtri hanno restituito i provider di chiavi KMIP in base al fatto che abbiano o meno un server di chiavi KMIP assegnato. Valori possibili:

* true: restituisce solo i provider di chiavi KMIP a cui è assegnato un server di chiavi KMIP.
* false: restituisce solo i provider di chiavi KMIP a cui non è assegnato un server di chiavi KMIP.


Se omesso, i provider di chiavi KMIP restituiti non vengono filtrati in base all'assegnazione o meno di un server di chiavi KMIP.
 a| 
booleano
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
kmipKeyProviders
 a| 
Un elenco dei fornitori di chiavi KMIP che sono stati creati.
 a| 
link:reference_element_api_keyproviderkmip.html["Fornitore di chiaviKmip"]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "ListKeyProvidersKmip",
  "params": {},
"id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result":
    {
    "kmipKeyProviders": [
        {
            "keyProviderID": 15,
            "kmipCapabilities": "SSL",
            "keyProviderIsActive": true,
            "keyServerIDs": [
                1
            ],
            "keyProviderName": "KeyProvider1"
        }
    ]
}
}
----


== Nuovo dalla versione

11,7
