---
permalink: api/reference_element_api_getpendingoperation.html 
sidebar: sidebar 
keywords: get,getting,pending,operation,getpendingoperation 
summary: 'È possibile utilizzare il metodo GetPendingOperation per rilevare un"operazione su un nodo attualmente in corso.  Questo metodo può essere utilizzato anche per segnalare il completamento di un"operazione.' 
---
= Ottieni operazione in sospeso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetPendingOperation` metodo per rilevare un'operazione su un nodo attualmente in corso.  Questo metodo può essere utilizzato anche per segnalare il completamento di un'operazione.



== Parametri

Questo metodo non ha parametri di input.



== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
in attesa di
 a| 
Valori possibili:

* vero: l'operazione è ancora in corso.
* falso:
+
L'operazione non è più in corso.


 a| 
booleano



 a| 
operazione
 a| 
Nome dell'operazione in corso o completata.
 a| 
corda

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "GetPendingOperation",
   "params": {},
   "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id" : 1,
   "result" : {
      "pendingOperation" : {
         "pending" : "true",
         "operation" : "TestDrivesInternal",
      }
   }
}
----


== Nuovo dalla versione

9,6
