---
permalink: api/reference_element_api_protectiondomaintolerance.html 
sidebar: sidebar 
keywords: object,objects,protectionDomainTolerance 
summary: 'L"oggetto protectionDomainTolerance contiene informazioni sulla capacità del cluster di archiviazione di continuare a leggere e scrivere dati in caso di uno o più guasti, tutti all"interno di un singolo dominio di protezione del tipo di dominio di protezione associato.' 
---
= protezioneDominioTolleranza
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto protectionDomainTolerance contiene informazioni sulla capacità del cluster di archiviazione di continuare a leggere e scrivere dati in caso di uno o più guasti, tutti all'interno di un singolo dominio di protezione del tipo di dominio di protezione associato.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
Scheme di protezione Tolleranze
 a| 
Un elenco di oggetti (uno per ogni schema di protezione) contenente informazioni sulla tolleranza ai guasti per il tipo di dominio di protezione associato.
 a| 
xref:reference_element_api_protectionschemetolerance.adoc[schema di protezione Tolleranza]vettore



 a| 
GuastisostenibiliPerInsieme
 a| 
Numero di guasti simultanei all'interno del tipo di dominio di protezione associato che possono verificarsi senza perdere il quorum dell'ensemble.
 a| 
intero

|===