---
permalink: api/reference_element_api_listvolumestatsbyaccount.html 
sidebar: sidebar 
keywords: volumes,volume,stats,list,listing,account,listvolumestatsbyaccount,activity 
summary: 'È possibile utilizzare il metodo ListVolumeStatsByAccount per elencare le misurazioni dell"attività di volume di alto livello per ogni account.  I valori vengono sommati da tutti i volumi posseduti dall"account.' 
---
= ListVolumeStatsByAccount
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListVolumeStatsByAccount` metodo per elencare le misurazioni dell'attività di volume di alto livello per ogni account.  I valori vengono sommati da tutti i volumi posseduti dall'account.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
includeVirtualVolumes
 a| 
Per impostazione predefinita, i volumi virtuali sono inclusi nella risposta.  Per escludere i volumi virtuali, impostare su false.
 a| 
booleano
 a| 
VERO
 a| 
NO



 a| 
conti
 a| 
Un elenco di ID account per i quali restituire le statistiche del volume.  Se omesso, vengono restituite le statistiche per tutti gli account.
 a| 
array di interi
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
volumeStats
 a| 
Elenco delle informazioni sull'attività del volume per ciascun account.*Nota:* il membro volumeID è 0 per ciascuna voce, poiché i valori rappresentano la somma di tutti i volumi posseduti dall'account.
 a| 
xref:reference_element_api_volumestats.adoc[volumeStats]vettore

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
"method": "ListVolumeStatsByAccount",
  "params": {"accounts": [3]},
  "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeStats": [
      {
        "accountID": 3,
        "nonZeroBlocks": 155040175,
        "readBytes": 3156273328128,
        "readBytesLastSample": 0,
        "readOps": 770574543,
        "readOpsLastSample": 0,
        "samplePeriodMSec": 500,
        "timestamp": "2016-10-17T20:42:26.231661Z",
        "unalignedReads": 0,
        "unalignedWrites": 0,
        "volumeAccessGroups": [],
        "volumeID": 0,
        "volumeSize": 1127428915200,
        "writeBytes": 1051988406272,
        "writeBytesLastSample": 0,
        "writeOps": 256833107,
        "writeOpsLastSample": 0,
        "zeroBlocks": 120211025
      }
    ]
  }
}
----


== Nuovo dalla versione

9,6
