---
permalink: api/reference_element_api_binding_vvols.html 
sidebar: sidebar 
keywords: binding,object,objects,volume,volumes,virtual 
summary: 'L"oggetto di associazione contiene informazioni sull"associazione per un volume virtuale.  È possibile recuperare un elenco di queste informazioni per tutti i volumi virtuali utilizzando il metodo API ListVirtualVolumeBindings.' 
---
= rilegatura (volumi virtuali)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto di associazione contiene informazioni sull'associazione per un volume virtuale.  È possibile recuperare un elenco di queste informazioni per tutti i volumi virtuali utilizzando `ListVirtualVolumeBindings` Metodo API.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
`protocolEndpointID`
 a| 
ID univoco dell'endpoint del protocollo.
 a| 
UUID



 a| 
`protocolEndpointInBandID`
 a| 
scsiNAADeviceID dell'endpoint del protocollo.
 a| 
corda



 a| 
`protocolEndpointType`
 a| 
Il tipo di endpoint del protocollo.  SCSI è l'unico valore restituito per il tipo di endpoint del protocollo.
 a| 
corda



 a| 
`virtualVolumeBindingID`
 a| 
ID univoco dell'oggetto di associazione del volume virtuale.
 a| 
intero



 a| 
`virtualVolumeHostID`
 a| 
ID univoco dell'host del volume virtuale.
 a| 
UUID



 a| 
`virtualVolumeID`
 a| 
ID univoco del volume virtuale.
 a| 
UUID



 a| 
`virtualVolumeSecondaryID`
 a| 
ID secondario del volume virtuale.
 a| 
corda

|===


== Trova maggiori informazioni

* xref:reference_element_api_listvirtualvolumebindings.adoc[ListVirtualVolumeBindings]
* xref:reference_element_api_protocolendpoint.adoc[protocolloEndpoint]

