---
permalink: api/reference_element_api_pendingnode.html 
sidebar: sidebar 
keywords: object,objects,pendingNode 
summary: 'L"oggetto pendingNode contiene informazioni su un nodo che può essere aggiunto a un cluster.  Utilizzare il metodo API ListPendingNodes per restituire un elenco di queste informazioni per tutti i nodi in sospeso.  È possibile aggiungere uno qualsiasi dei nodi elencati a un cluster utilizzando il metodo API AddNodes.' 
---
= nodo in sospeso
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'oggetto pendingNode contiene informazioni su un nodo che può essere aggiunto a un cluster.  Utilizzare il `ListPendingNodes` Metodo API per restituire un elenco di queste informazioni per tutti i nodi in sospeso.  È possibile aggiungere uno qualsiasi dei nodi elencati a un cluster utilizzando `AddNodes` Metodo API.



== Membri dell'oggetto

Questo oggetto contiene i seguenti membri:

|===
| Nome | Descrizione | Tipo 


 a| 
cipi
 a| 
L'indirizzo IP del cluster assegnato al nodo.
 a| 
corda



 a| 
activeNodeKey
 a| 
Una chiave univoca che consente al nodo di unirsi automaticamente al cluster dopo l'installazione corretta del software.
 a| 
corda



 a| 
IDNodoassegnato
 a| 
L'ID nodo assegnato al nodo.
 a| 
corda



 a| 
asyncHandle
 a| 
L'handle del metodo asincrono che è possibile utilizzare per interrogare lo stato dell'operazione.
 a| 
intero



 a| 
Nometelaio
 a| 
Identifica in modo univoco uno chassis; identico per tutti i nodi in un singolo chassis.
 a| 
corda



 a| 
cip
 a| 
L'indirizzo IP del cluster assegnato al nodo.
 a| 
corda



 a| 
mip
 a| 
L'indirizzo IP di gestione assegnato al nodo.
 a| 
corda



 a| 
NodoSlot
 a| 
Per le piattaforme HCI, la lettera corrispondente allo slot dello chassis in cui si trova questo nodo ("A", "B", "C" o "D").  Per le piattaforme di archiviazione, questo valore è nullo.
 a| 
corda



 a| 
pendingActiveNodeID
 a| 
ID del nodo in sospeso.
 a| 
intero



 a| 
informazioni sulla piattaforma
 a| 
Informazioni hardware per il nodo.  Membri:

* chassisType: la piattaforma hardware del nodo.
* cpuModel: modello di CPU della piattaforma hardware.
* nodeMemoryGB: quantità di memoria installata nella piattaforma fisica in GB.
* nodeType: il nome del modello del nodo.
* platformConfigVersion: la versione del software configurata per questo hardware del nodo.

 a| 
Oggetto JSON



 a| 
ruolo
 a| 
Il ruolo del nodo nel cluster. Valori possibili:

* Gestione
* Magazzinaggio
* Calcolare
* Testimone

 a| 



 a| 
sorso
 a| 
L'indirizzo IP di archiviazione (iSCSI) assegnato al nodo.
 a| 
corda



 a| 
versione software
 a| 
La versione corrente del software Element in esecuzione sul nodo.
 a| 
corda

|===


== Trova maggiori informazioni

* xref:reference_element_api_addnodes.adoc[Aggiungi nodi]
* xref:reference_element_api_listpendingnodes.adoc[Elenco nodi in sospeso]

