---
permalink: api/reference_element_api_listdrivestats.html 
sidebar: sidebar 
keywords: cluster,list,listing,drive,drives,stats,statistics,listdrivestats 
summary: 'È possibile utilizzare il metodo ListDriveStats per elencare le misurazioni delle attività di alto livello per più unità nel cluster.  Per impostazione predefinita, questo metodo restituisce statistiche per tutte le unità nel cluster e queste misurazioni sono cumulative a partire dall"aggiunta dell"unità al cluster.  Alcuni valori restituiti da questo metodo sono specifici delle unità a blocchi, mentre altri sono specifici delle unità a metadati.' 
---
= ListDriveStats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListDriveStats` metodo per elencare le misurazioni dell'attività di alto livello per più unità nel cluster.  Per impostazione predefinita, questo metodo restituisce statistiche per tutte le unità nel cluster e queste misurazioni sono cumulative a partire dall'aggiunta dell'unità al cluster.  Alcuni valori restituiti da questo metodo sono specifici delle unità a blocchi, mentre altri sono specifici delle unità a metadati.



== Parametro

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
unità
 a| 
Elenco degli ID unità (driveID) per i quali restituire le statistiche dell'unità.  Se si omette questo parametro, vengono restituite le misurazioni per tutte le unità.
 a| 
array di interi
 a| 
Nessuno
 a| 
NO

|===


== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
Statistiche di guida
 a| 
Elenco delle informazioni sull'attività dell'unità per ciascuna unità.
 a| 
xref:reference_element_api_drivestats.adoc[Statistiche di guida]vettore



 a| 
errori
 a| 
Questo elenco contiene il driveID e il messaggio di errore associato.  È sempre presente e vuoto se non ci sono errori.
 a| 
Matrice di oggetti JSON

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "id": 1,
  "method": "ListDriveStats",
  "params": {
    "drives":[22,23]
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "driveStats": [
      {
        "driveID": 22,
        "failedDieCount": 0,
        "lifeRemainingPercent": 84,
        "lifetimeReadBytes": 30171004403712,
        "lifetimeWriteBytes": 103464755527680,
        "powerOnHours": 17736,
        "readBytes": 14656542,
         "readOps": 3624,
        "reallocatedSectors": 0,
        "reserveCapacityPercent": 100,
        "timestamp": "2016-03-01T00:19:24.782735Z",
        "totalCapacity": 300069052416,
        "usedCapacity": 1783735635,
        "usedMemory": 879165440,
        "writeBytes": 2462169894,
        "writeOps": 608802
      }
    ],
    "errors": [
      {
        "driveID": 23,
        "exception": {
          "message": "xStatCheckpointDoesNotExist",
          "name": "xStatCheckpointDoesNotExist"
        }
      }
    ]
  }
}
----


== Nuovo dalla versione

9,6



== Trova maggiori informazioni

xref:reference_element_api_getdrivestats.adoc[Ottieni statistiche di guida]
