---
permalink: api/reference_element_api_quiescesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: snapmirror,relationship,relationships,quiesce,quiescing,quiescescnapmirrorrelationship 
summary: 'L"interfaccia utente Web del software Element utilizza il metodo QuiesceSnapMirrorRelationship per disabilitare i futuri trasferimenti di dati per una relazione SnapMirror .  Se è in corso un trasferimento, lo stato della relazione diventa "quiescent" fino al completamento del trasferimento.  Se il trasferimento in corso viene interrotto, non verrà riavviato.  È possibile riattivare i trasferimenti di dati per la relazione utilizzando il metodo API ResumeSnapMirrorRelationship.' 
---
= QuiesceSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web del software Element utilizza `QuiesceSnapMirrorRelationship` metodo per disabilitare i futuri trasferimenti di dati per una relazione SnapMirror .  Se è in corso un trasferimento, lo stato della relazione diventa "quiescent" fino al completamento del trasferimento.  Se il trasferimento in corso viene interrotto, non verrà riavviato.  È possibile riattivare i trasferimenti di dati per la relazione utilizzando `ResumeSnapMirrorRelationship` Metodo API.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
snapMirrorEndpointID
 a| 
ID endpoint del sistema di archiviazione ONTAP remoto che comunica con il cluster di archiviazione Element.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
destinazioneVolume
 a| 
Il volume di destinazione nella relazione SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeinfo]
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
snapMirrorRelationship
 a| 
Un oggetto contenente informazioni sulla relazione SnapMirror inattiva.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Nuovo dalla versione

10,1
