---
permalink: api/reference_element_api_initializesnapmirrorrelationship.html 
sidebar: sidebar 
keywords: snapmirror,relationship,relationships,initialize,initializing,initializesnapmirrorrelationship 
summary: 'L"interfaccia utente Web del software Element utilizza il metodo InitializeSnapMirrorRelationship per inizializzare il volume di destinazione in una relazione SnapMirror eseguendo un trasferimento di base iniziale tra cluster.' 
---
= InizializzaSnapMirrorRelationship
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web del software Element utilizza `InitializeSnapMirrorRelationship` Metodo per inizializzare il volume di destinazione in una relazione SnapMirror eseguendo un trasferimento di base iniziale tra cluster.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
snapMirrorEndpointID
 a| 
L'ID del sistema ONTAP remoto.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
destinazioneVolume
 a| 
Il volume di destinazione nella relazione SnapMirror .
 a| 
xref:reference_element_api_snapmirrorvolumeinfo.adoc[snapMirrorVolumeInfo]
 a| 
Nessuno
 a| 
SÌ



 a| 
maxTransferRate
 a| 
Specifica la velocità massima di trasferimento dati tra i volumi in kilobyte al secondo.  Il valore predefinito, 0, è illimitato e consente alla relazione SnapMirror di utilizzare completamente la larghezza di banda di rete disponibile.
 a| 
intero
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
snapMirrorRelationship
 a| 
Informazioni sulla relazione SnapMirror inizializzata.
 a| 
xref:reference_element_api_snapmirrorrelationship.adoc[snapMirrorRelationship]

|===


== Nuovo dalla versione

10,1
