---
permalink: api/reference_element_api_removevolumesfromvolumeaccessgroup.html 
sidebar: sidebar 
keywords: remove,removing,volume,volumes,access,group,removevolumesfromvolumeaccessgroup 
summary: È possibile utilizzare il metodo RemoveVolumesFromVolumeAccessGroup per rimuovere volumi da un gruppo di accesso al volume specificato. 
---
= RimuoviVolumiDaVolumeAccessGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `RemoveVolumesFromVolumeAccessGroup` metodo per rimuovere volumi da un gruppo di accesso al volume specificato.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
volumeAccessGroupID
 a| 
VolumeAccessGroupID da cui rimuovere i volumi.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
volumi
 a| 
VolumeID dei volumi da rimuovere dal gruppo di accesso al volume.
 a| 
array di interi
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
volumeAccessGroup
 a| 
Un oggetto contenente informazioni sul gruppo di accesso al volume appena modificato.
 a| 
xref:reference_element_api_volumeaccessgroup.adoc[volumeAccessGroup]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "RemoveVolumesFromVolumeAccessGroup",
   "params": {
      "volumeAccessGroupID": 96,
      "volumes": [1,2]
   },
   "id": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroup": {
      "attributes": {},
      "deletedVolumes": [
        346
      ],
      "initiatorIDs": [
        116,
        117
      ],
      "initiators": [
        "iqn.1993-08.org.debian:01:181324777",
        "iqn.1993-08.org.debian:01:181324888"
      ],
      "name": "northbanktest",
      "volumeAccessGroupID": 96,
      "volumes": []
    }
  }
}
----


== Nuovo dalla versione

9,6
