---
permalink: api/reference_element_api_getnodeactivetlsciphers.html 
sidebar: sidebar 
keywords: tls,cipher,ciphers,get,getting,getnodeactivetlsciphers,accepted 
summary: È possibile utilizzare il metodo GetNodeActiveTlsCiphers su un singolo nodo per ottenere un elenco dei cifrari TLS attualmente accettati su questo nodo.  È possibile utilizzare questo metodo sui nodi di gestione e di archiviazione. 
---
= GetNodeActiveTlsCiphers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetNodeActiveTlsCiphers` su un singolo nodo per ottenere un elenco dei cifrari TLS attualmente accettati su questo nodo.  È possibile utilizzare questo metodo sui nodi di gestione e di archiviazione.



== Parametro

Questo metodo non ha parametri di input.



== Valori di ritorno

Questo metodo ha i seguenti valori di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
Cifrari obbligatori
 a| 
Elenco delle suite di cifratura TLS obbligatorie per il nodo.  Si tratta di cifrari sempre attivi sul nodo.
 a| 
corda



 a| 
Cifrari supplementari
 a| 
Elenco delle suite di cifratura TLS supplementari per il nodo.
 a| 
corda

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "method": "GetNodeActiveTlsCiphers",
  "params": {},
  "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
      "id" : 1,
      "result" : {
        "mandatoryCiphers": [
            "DHE-RSA-AES256-SHA256",
            "DHE-RSA-AES256-GCM-SHA384",
            "ECDHE-RSA-AES256-SHA384",
            "ECDHE-RSA-AES256-GCM-SHA384"
        ],
        "supplementalCiphers": [
            "DHE-RSA-AES128-SHA256",
            "DHE-RSA-AES128-GCM-SHA256",
            "ECDHE-RSA-AES128-SHA256",
            "ECDHE-RSA-AES128-GCM-SHA256"
        ]
    }
}
----