---
permalink: api/reference_element_api_modifysnapmirrorendpoint.html 
sidebar: sidebar 
keywords: modify,modifying,edit,editing,change,changing,snapmirror,endpoint,modifysnapmirrorendpoint 
summary: 'L"interfaccia utente Web del software Element utilizza il metodo ModifySnapMirrorEndpoint per modificare il nome e gli attributi di gestione di un endpoint SnapMirror .' 
---
= ModificaSnapMirrorEndpoint
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interfaccia utente Web del software Element utilizza `ModifySnapMirrorEndpoint` Metodo per modificare il nome e gli attributi di gestione per un endpoint SnapMirror .



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
SnapMirrorEndpointID
 a| 
L'endpoint SnapMirror da modificare.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
gestioneIP
 a| 
Il nuovo indirizzo IP di gestione per il sistema ONTAP .
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
nome utente
 a| 
Il nuovo nome utente di gestione per il sistema ONTAP .
 a| 
corda
 a| 
Nessuno
 a| 
NO



 a| 
password
 a| 
La nuova password di gestione per il sistema ONTAP .
 a| 
corda
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
snapMirrorEndpoint
 a| 
Informazioni sull'endpoint SnapMirror modificato.
 a| 
xref:reference_element_api_snapmirrorendpoint.adoc[snapMirrorEndpoint]

|===


== Nuovo dalla versione

10,0
