---
permalink: api/reference_element_api_listauthsessionbyclusteradmin.html 
sidebar: sidebar 
keywords: cluster admin,sessions,auth sessions,list 
summary: È possibile utilizzare il metodo ListAuthSessionsByClusterAdmin per elencare tutte le sessioni di autenticazione associate al ClusterAdminID specificato.  Se il ClusterAdminID specificato è mappato a un gruppo di utenti, verranno elencate tutte le sessioni di autenticazione per tutti i membri di quel gruppo. 
---
= ListAuthSessionsByClusterAdmin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ListAuthSessionsByClusterAdmin` metodo per elencare tutte le sessioni di autenticazione associate allo specificato `ClusterAdminID` .  Se specificato `ClusterAdminID` se si associa a un gruppo di utenti, verranno elencate tutte le sessioni di autenticazione per tutti i membri di quel gruppo.



== Parametri

Questo metodo ha il seguente parametro di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
ID amministratore cluster
 a| 
Identificatore univoco per l'amministratore del cluster.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ

|===


== Valori di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
sessioni
 a| 
Elenco delle informazioni sulla sessione per le sessioni di autenticazione.
 a| 
link:reference_element_api_authsessioninfo.html["authSessionInfo"]

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
    "method": "ListAuthSessionsByClusterAdmin",
    "clusterAdminID": 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
"sessions": [
      {
        "accessGroupList": [
          "administrator"
        ],
        "authMethod": "Cluster",
        "clusterAdminIDs": [
          1
        ],
        "finalTimeout": "2020-03-14T19:21:24Z",
        "idpConfigVersion": 0,
        "lastAccessTimeout": "2020-03-11T19:51:24Z",
        "sessionCreationTime": "2020-03-11T19:21:24Z",
        "sessionID": "b12bfc64-f233-44df-8b9f-6fb6c011abf7",
        "username": "admin"
      }
    ]
}
----


== Nuovo dalla versione

12,0
