---
permalink: api/reference_element_api_modifyvolumeaccessgrouplunassignments.html 
sidebar: sidebar 
keywords: volumes,volume,defining,define,modify,modifying,edit,editing,change,changing,modifyvolumeaccessgrouplunassignments,access,group,lun,assignment 
summary: È possibile utilizzare il metodo ModifyVolumeAccessGroupLunAssignments per definire assegnazioni LUN personalizzate per volumi specifici. 
---
= ModifyVolumeAccessGroupLunAssignments
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `ModifyVolumeAccessGroupLunAssignments` metodo per definire assegnazioni LUN personalizzate per volumi specifici.

Questo metodo modifica solo i valori LUN impostati sul parametro lunAssignments nel gruppo di accesso al volume.  Tutte le altre assegnazioni LUN rimangono invariate.

I valori di assegnazione LUN devono essere univoci per i volumi in un gruppo di accesso al volume.  Non è possibile definire valori LUN duplicati all'interno di un gruppo di accesso al volume.  Tuttavia, è possibile utilizzare nuovamente gli stessi valori LUN in gruppi di accesso al volume diversi.


NOTE: I valori LUN validi sono compresi tra 0 e 16383.  Il sistema genera un'eccezione se si passa un valore LUN al di fuori di questo intervallo.  Nessuna delle assegnazioni LUN specificate viene modificata se si verifica un'eccezione.

ATTENZIONE:

Se si modifica l'assegnazione di un LUN per un volume con I/O attivo, l'I/O potrebbe essere interrotto.  Prima di modificare le assegnazioni LUN del volume, è necessario modificare la configurazione del server.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===


| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
volumeAccessGroupID
 a| 
ID univoco del gruppo di accesso al volume per il quale verranno modificate le assegnazioni LUN.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
lunAssignments
 a| 
Gli ID del volume con i nuovi valori LUN assegnati.
 a| 
array di interi
 a| 
Nessuno
 a| 
SÌ

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===


| Nome | Descrizione | Tipo 


 a| 
volumeAccessGroupLunAssignments
 a| 
Un oggetto contenente i dettagli delle assegnazioni LUN del gruppo di accesso al volume modificato.
 a| 
Oggetto JSON

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
   "method": "ModifyVolumeAccessGroupLunAssignments",
   "params": {
       "volumeAccessGroupID" : 218,
       "lunAssignments" : [
           {"volumeID" : 832, "lun" : 0},
           {"volumeID" : 834, "lun" : 1}
        ]
    },
    "id" : 1
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
  "id": 1,
  "result": {
    "volumeAccessGroupLunAssignments": {
      "deletedLunAssignments": [],
      "lunAssignments": [
        {
          "lun": 0,
          "volumeID": 832
        },
        {
          "lun": 1,
          "volumeID": 834
        }
      ],
      "volumeAccessGroupID": 218
    }
  }
}
----


== Nuovo dalla versione

9,6
