---
permalink: api/reference_element_api_getbackuptarget.html 
sidebar: sidebar 
keywords: backup,target,targets,get,getting,GetBackupTarget 
summary: È possibile utilizzare il metodo GetBackupTarget per restituire informazioni su una destinazione di backup specifica creata. 
---
= Ottieni destinazione di backup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puoi usare il `GetBackupTarget` Metodo per restituire informazioni su una destinazione di backup specifica che hai creato.



== Parametri

Questo metodo ha i seguenti parametri di input:

|===
| Nome | Descrizione | Tipo | Valore predefinito | Necessario 


 a| 
attributi
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON
 a| 
Nessuno
 a| 
NO



 a| 
backupTargetID
 a| 
Identificatore univoco assegnato alla destinazione del backup.
 a| 
intero
 a| 
Nessuno
 a| 
SÌ



 a| 
nome
 a| 
Nome della destinazione del backup.
 a| 
corda
 a| 
Nessuno
 a| 
NO

|===


== Valore di ritorno

Questo metodo ha il seguente valore di ritorno:

|===
| Nome | Descrizione | Tipo 


 a| 
backupTarget
 a| 
Elenco di coppie nome-valore nel formato oggetto JSON.
 a| 
Oggetto JSON

|===


== Richiedi esempio

Le richieste per questo metodo sono simili al seguente esempio:

[listing]
----
{
  "id": 1,
  "method": "GetBackupTarget",
  "params": {
      "backupTargetID": 1
  }
}
----


== Esempio di risposta

Questo metodo restituisce una risposta simile al seguente esempio:

[listing]
----
{
   "id": 1,
   "result": {
     "backupTarget": {
     "attributes" : {
        "size" : 100
     },
     "backupTargetID" : 1,
     "name" : "mytargetbackup"
    }
  }
}
----


== Nuovo dalla versione

9,6
